// Code generated by shared/contract/cmd/contractgen; DO NOT EDIT.
// Source: shared/contract/schema/*.schema.json
#pragma once

#include <string_view>

namespace velox::contract::fields {

// job_payload_v2.schema.json
inline constexpr std::string_view AUDIO_LANGUAGE_FOR_SRT = "audio_language_for_srt";
inline constexpr std::string_view CHANNEL_ID = "channel_id";
inline constexpr std::string_view COMPILED_RENDER_PLAN_JSON = "compiled_render_plan_json";
inline constexpr std::string_view COMPILED_RENDER_PLAN_SHA256 = "compiled_render_plan_sha256";
inline constexpr std::string_view CONTRACT_VERSION = "contract_version";
inline constexpr std::string_view CORRELATION_ID = "correlation_id";
inline constexpr std::string_view CREATED_AT = "created_at";
inline constexpr std::string_view DELIVERY_PLAN = "delivery_plan";
inline constexpr std::string_view DRIVE_OUTPUT_FOLDER = "drive_output_folder";
inline constexpr std::string_view EFFECT = "effect";
inline constexpr std::string_view IMAGE_SOURCE_MAP = "image_source_map";
inline constexpr std::string_view ITEMS = "items";
inline constexpr std::string_view JOB_FINGERPRINT = "job_fingerprint";
inline constexpr std::string_view JOB_ID = "job_id";
inline constexpr std::string_view JOB_RUN_ID = "job_run_id";
inline constexpr std::string_view JOB_TYPE = "job_type";
inline constexpr std::string_view LAYERS = "layers";
inline constexpr std::string_view MANIFEST_REF = "manifest_ref";
inline constexpr std::string_view MANIFEST_SHA256 = "manifest_sha256";
inline constexpr std::string_view ORIENTATION = "orientation";
inline constexpr std::string_view OUTPUT_PATH = "output_path";
inline constexpr std::string_view OUTPUT_VIDEO_ID = "output_video_id";
inline constexpr std::string_view PAYLOAD_CONTRACT_VERSION = "payload_contract_version";
inline constexpr std::string_view PRIORITY = "priority";
inline constexpr std::string_view RENDER_MANIFEST = "render_manifest";
inline constexpr std::string_view RENDER_PLAN_JSON = "render_plan_json";
inline constexpr std::string_view RENDER_PLAN_SHA256 = "render_plan_sha256";
inline constexpr std::string_view SCENE_COUNT = "scene_count";
inline constexpr std::string_view SCENE_DURATION_SECS = "scene_duration_secs";
inline constexpr std::string_view SCENE_IMAGE_PATHS = "scene_image_paths";
inline constexpr std::string_view SCENES = "scenes";
inline constexpr std::string_view SCENES_JSON = "scenes_json";
inline constexpr std::string_view SCRIPT_TEXT = "script_text";
inline constexpr std::string_view SOURCE = "source";
inline constexpr std::string_view STATUS = "status";
inline constexpr std::string_view SUBMITTED_VIA = "submitted_via";
inline constexpr std::string_view TEMPLATE_ID = "template_id";
inline constexpr std::string_view TEMPLATE_VERSION = "template_version";
inline constexpr std::string_view TIMEOUT_SECS = "timeout_secs";
inline constexpr std::string_view TOTAL_DURATION_SECS = "total_duration_secs";
inline constexpr std::string_view UPDATED_AT = "updated_at";
inline constexpr std::string_view VERSION = "version";
inline constexpr std::string_view VIDEO_METADATA = "video_metadata";
inline constexpr std::string_view VIDEO_MODE = "video_mode";
inline constexpr std::string_view VIDEO_NAME = "video_name";
inline constexpr std::string_view VOICEOVER_COUNT = "voiceover_count";
inline constexpr std::string_view VOICEOVER_PATHS = "voiceover_paths";

// render_manifest_v1.schema.json
inline constexpr std::string_view RENDER_MANIFEST_ASSETS = "assets";
inline constexpr std::string_view RENDER_MANIFEST_ASSETS_DURATION_MS = "duration_ms";
inline constexpr std::string_view RENDER_MANIFEST_ASSETS_FORMAT = "format";
inline constexpr std::string_view RENDER_MANIFEST_ASSETS_ID = "id";
inline constexpr std::string_view RENDER_MANIFEST_ASSETS_KIND = "kind";
inline constexpr std::string_view RENDER_MANIFEST_ASSETS_SHA256 = "sha256";
inline constexpr std::string_view RENDER_MANIFEST_ASSETS_SIZE_BYTES = "size_bytes";
inline constexpr std::string_view RENDER_MANIFEST_ASSETS_URI = "uri";
inline constexpr std::string_view RENDER_MANIFEST_CANVAS = "canvas";
inline constexpr std::string_view RENDER_MANIFEST_CANVAS_FPS_DEN = "fps_den";
inline constexpr std::string_view RENDER_MANIFEST_CANVAS_FPS_NUM = "fps_num";
inline constexpr std::string_view RENDER_MANIFEST_CANVAS_HEIGHT = "height";
inline constexpr std::string_view RENDER_MANIFEST_CANVAS_PIXEL_FORMAT = "pixel_format";
inline constexpr std::string_view RENDER_MANIFEST_CANVAS_WIDTH = "width";
inline constexpr std::string_view RENDER_MANIFEST_LAYERS = "layers";
inline constexpr std::string_view RENDER_MANIFEST_LAYERS_ANIMATION = "animation";
inline constexpr std::string_view RENDER_MANIFEST_LAYERS_ASSET = "asset";
inline constexpr std::string_view RENDER_MANIFEST_LAYERS_DURATION_SECONDS = "duration_seconds";
inline constexpr std::string_view RENDER_MANIFEST_LAYERS_FONT = "font";
inline constexpr std::string_view RENDER_MANIFEST_LAYERS_FONT_SIZE = "font_size";
inline constexpr std::string_view RENDER_MANIFEST_LAYERS_ID = "id";
inline constexpr std::string_view RENDER_MANIFEST_LAYERS_POSITION = "position";
inline constexpr std::string_view RENDER_MANIFEST_LAYERS_PRESET = "preset";
inline constexpr std::string_view RENDER_MANIFEST_LAYERS_ROLE = "role";
inline constexpr std::string_view RENDER_MANIFEST_LAYERS_SOURCE = "source";
inline constexpr std::string_view RENDER_MANIFEST_LAYERS_START_SECONDS = "start_seconds";
inline constexpr std::string_view RENDER_MANIFEST_LAYERS_TEXT = "text";
inline constexpr std::string_view RENDER_MANIFEST_LAYERS_TYPE = "type";
inline constexpr std::string_view RENDER_MANIFEST_OUTPUT = "output";
inline constexpr std::string_view RENDER_MANIFEST_OUTPUT_AUDIO_CHANNELS = "audio_channels";
inline constexpr std::string_view RENDER_MANIFEST_OUTPUT_AUDIO_CODEC = "audio_codec";
inline constexpr std::string_view RENDER_MANIFEST_OUTPUT_AUDIO_SAMPLE_RATE = "audio_sample_rate";
inline constexpr std::string_view RENDER_MANIFEST_OUTPUT_CONTAINER = "container";
inline constexpr std::string_view RENDER_MANIFEST_OUTPUT_VIDEO_CODEC = "video_codec";
inline constexpr std::string_view RENDER_MANIFEST_SCHEMA = "schema";
inline constexpr std::string_view RENDER_MANIFEST_TRACKS = "tracks";
inline constexpr std::string_view RENDER_MANIFEST_TRACKS_ASSET_ID = "asset_id";
inline constexpr std::string_view RENDER_MANIFEST_TRACKS_BURN_IN = "burn_in";
inline constexpr std::string_view RENDER_MANIFEST_TRACKS_EVENTS = "events";
inline constexpr std::string_view RENDER_MANIFEST_TRACKS_EVENTS_ASSET_ID = "asset_id";
inline constexpr std::string_view RENDER_MANIFEST_TRACKS_EVENTS_DUCK_UNDER_VOICEOVER = "duck_under_voiceover";
inline constexpr std::string_view RENDER_MANIFEST_TRACKS_EVENTS_DURATION_MS = "duration_ms";
inline constexpr std::string_view RENDER_MANIFEST_TRACKS_EVENTS_FADE_IN_MS = "fade_in_ms";
inline constexpr std::string_view RENDER_MANIFEST_TRACKS_EVENTS_FADE_OUT_MS = "fade_out_ms";
inline constexpr std::string_view RENDER_MANIFEST_TRACKS_EVENTS_GAIN_DB = "gain_db";
inline constexpr std::string_view RENDER_MANIFEST_TRACKS_EVENTS_SOURCE_START_MS = "source_start_ms";
inline constexpr std::string_view RENDER_MANIFEST_TRACKS_EVENTS_TIMELINE_START_MS = "timeline_start_ms";
inline constexpr std::string_view RENDER_MANIFEST_TRACKS_ID = "id";
inline constexpr std::string_view RENDER_MANIFEST_TRACKS_KIND = "kind";

// delivery_plan_v1.schema.json
inline constexpr std::string_view DELIVERY_PLAN_DESTINATION_ID = "destination_id";
inline constexpr std::string_view DELIVERY_PLAN_ENABLED = "enabled";
inline constexpr std::string_view DELIVERY_PLAN_EXTERNAL_DESTINATION_ID = "external_destination_id";
inline constexpr std::string_view DELIVERY_PLAN_METADATA = "metadata";
inline constexpr std::string_view DELIVERY_PLAN_PLATFORM = "platform";
inline constexpr std::string_view DELIVERY_PLAN_PRIORITY = "priority";
inline constexpr std::string_view DELIVERY_PLAN_RETRY_BUDGET = "retry_budget";

}  // namespace velox::contract::fields
