#!/usr/bin/env python3
# =============================================================================
# tests/worker-cert/build_real_payload.py — Real-asset SubmitJobRequest builder.
# =============================================================================
# Builds the JSON payload accepted by Velox Master's POST /api/v1/jobs
# (operationId `submitJob`, schema `SubmitJobRequest` in
# `DataServer/api/openapi.yaml`) using ONLY canonical `velox-asset://<asset_id>`
# references — never the path-like `velox-asset://voiceovers/<file>.mp3` shape
# that has caused application-level failures in past smokes
# (see docs/operations/04-velox-final-smoke-checklist.md §1).
#
# Asset IDs come from `tests/worker-cert/fixtures/assets.json` (canonical,
# hand-curated from job_submit_e2e_happy_path_test.go, enqueue_normalization_
# test.go, creator_push_e2e_test.go, render_manifest_resolver_test.go).
#
# Outputs the JSON to stdout (default) or to a file via --output. Stdlib
# only (argparse + json + pathlib + re + sys) so it can run in any minimal
# CI / e2e / local shell without pip dependencies.
#
# Exit codes:
#   0  success — payload written/printed.
#   2  usage / env error (missing arg, invalid flag, fixtures unreadable).
#   3  fixtures file present but malformed (jq-parseable JSON expected).
#   4  forbidden pattern detected by --strict self-validation
#      (defensive; this script never emits those by construction).
# =============================================================================

import argparse
import json
import re
import sys
import time
from pathlib import Path

# --- Forbidden patterns (intentional anti-pattern from earlier failures) ----
# Legacy body keys are checked separately by assert_canonical_shape below.
# Matches any velox-asset://<scheme>/<file>.<ext> shape — i.e. references that
# try to back into a server-local file path. The canonical codec only accepts
# `velox-asset://<asset_id>` regardless of kind (voiceover/clip/subtitle/
# image) — see DataServer/internal/handlers/server/pipeline/intake_validation.go
# §manifestRefURLRegexp. These patterns are EXCLUDED from any payload this
# script produces; --strict runs the same regex against the OUTPUT to assert
# safety on every invocation.
FORBIDDEN_PATTERNS = [
    re.compile(r"velox-asset://voiceovers/[^/]+\.[a-zA-Z0-9]+"),
    re.compile(r"velox-asset://clips/[^/]+\.[a-zA-Z0-9]+"),
    re.compile(r"velox-asset://subtitles/[^/]+\.[a-zA-Z0-9]+"),
    re.compile(r"velox-asset://images/[^/]+\.[a-zA-Z0-9]+"),
    re.compile(r"file://"),
    re.compile(r"\bC:\\\\|\b/home/|\b/Users/|\b/var/|\b/tmp/"),
]

# Canonical kind taxonomy (kind → assets[].asset_id selector), matches
# fixtures/assets.json schema documented inline.
KINDS = ("voiceover", "clips", "subtitles", "images")


def load_fixtures(path: Path) -> dict:
    """Load fixtures JSON; abort with code 3 on parse error, code 2 on missing."""
    if not path.exists():
        print(f"fixtures not found: {path}", file=sys.stderr)
        sys.exit(2)
    try:
        with path.open("r", encoding="utf-8") as fh:
            data = json.load(fh)
    except json.JSONDecodeError as exc:
        print(f"fixtures malformed JSON: {path}: {exc}", file=sys.stderr)
        sys.exit(3)
    for kind in KINDS:
        if not isinstance(data.get(kind), list) or not data[kind]:
            print(
                f"fixtures missing/empty required kind: {kind!r} (need asset_id list)",
                file=sys.stderr,
            )
            sys.exit(3)
        for entry in data[kind]:
            if not isinstance(entry, dict) or "asset_id" not in entry:
                print(
                    f"fixtures malformed entry under {kind!r}: {entry!r} (need dict with asset_id)",
                    file=sys.stderr,
                )
                sys.exit(3)
    return data


def pick_asset_id(fixtures: dict, kind: str, index: int = 0) -> str:
    """Pick the asset_id at `index` from the `kind` list; fails on out-of-range."""
    entries = fixtures[kind]
    if index < 0 or index >= len(entries):
        print(f"asset index {index} out of range for kind {kind!r}", file=sys.stderr)
        sys.exit(2)
    return entries[index]["asset_id"]


def build_payload(
    worker_id: str,
    destination_id: str,
    target_executor_id: str,
    fixtures: dict,
    idempotency_key_suffix: int,
    now_epoch: int | None = None,
    scenes_count: int = 2,
    duration_per_scene: int = 3,
    no_placement_pin: bool = False,
) -> dict:
    """Compose a SubmitJobRequest-shaped payload from canonical real assets.

    The idempotency_key is `smoke-one-<worker_id>-<epoch>` to mirror the
    canonical jobs_smoke.sh pattern; second-resolution precision is enough
    for operator pre-flight smokes because the master refuses duplicates only
    inside the typical idempotency_window (here we deliberately avoid
    second-resolution reuse by including worker_id).

    `scenes_count` controls how many scenes are generated by modulo-cycling
    through fixtures["clips"] and fixtures["voiceover"]; default 2 matches
    the canonical smoke_one.sh shape, larger values (>=10) exercise the
    scene-concat engine path on multi_scene_concat smokes. `duration_per_scene`
    defaults to 3 (the canonical smoke_one value); the multi_scene_concat
    smoke overrides this to keep total run-time under the operator's poll
    budget while still exercising per-scene stitching.
    """
    if now_epoch is None:
        now_epoch = int(time.time())
    if scenes_count < 1:
        print(f"scenes_count must be >= 1; got {scenes_count}", file=sys.stderr)
        sys.exit(2)
    n_clips = len(fixtures["clips"])
    n_vo = len(fixtures["voiceover"])
    # Modulo-cycle: scene i uses clips[i % n_clips] and voiceover[i % n_vo].
    # Every asset is attached to its scene so the request has no positional
    # top-level arrays and remains valid when scenes are reordered.
    scenes = []
    for i in range(scenes_count):
        clip_id = pick_asset_id(fixtures, "clips", i % n_clips)
        vo_id = pick_asset_id(fixtures, "voiceover", i % n_vo)
        clip_url = f"velox-asset://{clip_id}"
        voiceover_url = f"velox-asset://{vo_id}"
        scenes.append({
            "scene_id": f"scene-{i}",
            "index": i,
            "kind": "clip",
            "text": f"Scene {i} — multi-scene concat {worker_id} (clip={i % n_clips} vo={i % n_vo})",
            "duration_seconds": duration_per_scene,
            "clip": {
                "asset_id": clip_id,
                "url": clip_url,
                "duration_ms": duration_per_scene * 1000,
            },
            "voiceover": {
                "asset_id": vo_id,
                "url": voiceover_url,
                "duration_ms": duration_per_scene * 1000,
            },
        })
    idem_suffix = f"-{idempotency_key_suffix}" if idempotency_key_suffix else ""
    payload = {
        "idempotency_key": f"smoke-one-{worker_id}-{now_epoch}{idem_suffix}",
        "job_type": "clip.stock.v1",
        "template_id": "worker-cert.smoke",
        "template_version": 1,
        "video_name": f"Real-asset smoke for {worker_id}@{now_epoch} (scenes={scenes_count})",
        "script_text": f"Real-asset worker certification for {worker_id}.",
        "output": {"width": 1280, "height": 720, "fps": 30, "format": "mp4"},
        "scenes": scenes,
        "delivery_plan": [
            {
                "destination_id": destination_id,
                "priority": 100,
                "retry_budget": 1,
            }
        ],
    }
    if not no_placement_pin:
        payload["placement_pin_worker_id"] = worker_id
    return payload


def assert_canonical_shape(payload: dict) -> list[str]:
    """Return paths for legacy body keys that must never reach POST /api/v1/jobs."""
    hits: list[str] = []
    forbidden_top = ("voiceover_paths", "subtitle_tracks", "clip_link", "image_link", "project_id", "target_executor_id", "_audit")
    if any(key in payload for key in forbidden_top):
        hits.extend(f"$.{key}" for key in payload if key in forbidden_top)
    required = ("idempotency_key", "job_type", "template_id", "template_version", "video_name", "scenes", "output", "delivery_plan")
    hits.extend(f"$.{key} (missing)" for key in required if key not in payload)
    if not isinstance(payload.get("job_type"), str) or not payload["job_type"].strip():
        hits.append("$.job_type (empty)")
    if not isinstance(payload.get("template_id"), str) or not payload["template_id"].strip():
        hits.append("$.template_id (empty)")
    if not isinstance(payload.get("template_version"), int) or payload["template_version"] < 1:
        hits.append("$.template_version (not positive integer)")
    if not isinstance(payload.get("video_name"), str) or not payload["video_name"].strip():
        hits.append("$.video_name (empty)")
    for i, scene in enumerate(payload.get("scenes", [])):
        if not isinstance(scene, dict):
            hits.append(f"$.scenes[{i}]")
            continue
        for key in ("clip_link", "clip_links", "image_link", "image_links", "voiceover_path", "local_path", "bindings", "stock_clip_sources", "drive_links"):
            if key in scene:
                hits.append(f"$.scenes[{i}].{key}")
        for key in ("clip", "voiceover"):
            asset = scene.get(key)
            if not isinstance(asset, dict) or not asset.get("url"):
                hits.append(f"$.scenes[{i}].{key}.url")
        if "subtitles" in scene and (not isinstance(scene["subtitles"], dict) or not scene["subtitles"].get("url")):
            hits.append(f"$.scenes[{i}].subtitles.url")
    output = payload.get("output")
    if not isinstance(output, dict):
        hits.append("$.output (not object)")
    elif not all(isinstance(output.get(key), int) and output[key] > 0 for key in ("width", "height", "fps")):
        hits.append("$.output (invalid dimensions/fps)")
    if not isinstance(payload.get("delivery_plan"), list) or not payload.get("delivery_plan"):
        hits.append("$.delivery_plan (empty or not array)")
    else:
        for i, entry in enumerate(payload["delivery_plan"]):
            if not isinstance(entry, dict) or not isinstance(entry.get("destination_id"), str) or not entry["destination_id"].strip():
                hits.append(f"$.delivery_plan[{i}].destination_id (empty)")
    return hits


def assert_no_forbidden(payload: dict, *, path: str = "$") -> list[str]:
    """Walk payload looking for any FORBIDDEN_PATTERNS hit; return hit paths."""
    hits: list[str] = []
    if isinstance(payload, dict):
        for k, v in payload.items():
            hits.extend(assert_no_forbidden(v, path=f"{path}.{k}"))
    elif isinstance(payload, list):
        for i, v in enumerate(payload):
            hits.extend(assert_no_forbidden(v, path=f"{path}[{i}]"))
    elif isinstance(payload, str):
        for pat in FORBIDDEN_PATTERNS:
            if pat.search(payload):
                hits.append(f"{path}={payload!r} (matched {pat.pattern})")
    return hits


def cmd_build(args: argparse.Namespace) -> int:
    if not isinstance(args.destination, str) or not args.destination.strip():
        print("error: --destination must be a non-empty explicit destination_id", file=sys.stderr)
        return 2
    args.destination = args.destination.strip()
    fixtures_path = Path(args.fixtures)
    fixtures = load_fixtures(fixtures_path)
    payload = build_payload(
        worker_id=args.worker_id,
        destination_id=args.destination,
        target_executor_id=args.target_executor_id,
        fixtures=fixtures,
        idempotency_key_suffix=args.idempotency_suffix,
        scenes_count=args.scenes_count,
        duration_per_scene=args.duration_per_scene,
        no_placement_pin=args.no_placement_pin,
    )
    if args.strict:
        hits = assert_canonical_shape(payload) + assert_no_forbidden(payload)
        if hits:
            print(
                f"ERROR: {len(hits)} forbidden pattern(s) detected (script regressed?):",
                file=sys.stderr,
            )
            for h in hits:
                print(f"  - {h}", file=sys.stderr)
            return 4

    text = json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False)
    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        # Atomic write: tmp + mv.
        tmp = out.with_suffix(out.suffix + ".tmp")
        tmp.write_text(text, encoding="utf-8")
        tmp.replace(out)
        print(f"wrote {out}", file=sys.stderr)
    else:
        sys.stdout.write(text + "\n")
    return 0


def cmd_selftest(args: argparse.Namespace) -> int:
    """Dry-run without I/O: build a payload, run strict validation, exit."""
    if not isinstance(args.destination, str) or not args.destination.strip():
        print("error: --destination must be a non-empty explicit destination_id", file=sys.stderr)
        return 2
    args.destination = args.destination.strip()
    fixtures_path = Path(args.fixtures)
    fixtures = load_fixtures(fixtures_path)
    payload = build_payload(
        worker_id=args.worker_id or "selftest-worker",
        destination_id=args.destination,
        target_executor_id=args.target_executor_id,
        fixtures=fixtures,
        idempotency_key_suffix=0,
        scenes_count=args.scenes_count,
        duration_per_scene=args.duration_per_scene,
        no_placement_pin=args.no_placement_pin,
    )
    hits = assert_canonical_shape(payload) + assert_no_forbidden(payload)
    print(f"selftest: built payload with {len(payload.get('scenes'))} scene(s)", file=sys.stderr)
    pin = payload.get("placement_pin_worker_id", "<unpinned>")
    print(f"selftest: placement_pin_worker_id={pin}", file=sys.stderr)
    print(
        f"selftest: scene assets={[{'clip': s['clip']['asset_id'], 'voiceover': s['voiceover']['asset_id']} for s in payload['scenes']]}",
        file=sys.stderr,
    )
    if hits:
        print(f"selftest: FAIL ({len(hits)} forbidden hit(s))", file=sys.stderr)
        return 4
    print("selftest: OK", file=sys.stderr)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="build_real_payload.py",
        description=(
            "Build a Velox /api/v1/jobs SubmitJobRequest payload from canonical "
            "velox-asset://<asset_id> references. Forbids the path-like "
            "velox-asset://voiceovers/<file>.mp3 shape that has caused application "
            "failures; relies on tests/worker-cert/fixtures/assets.json for "
            "canonical asset IDs (hand-curated from e2e tests)."
        ),
        epilog=(
            "Examples:\n"
            "  # Print payload for a worker and an explicitly selected destination:\n"
            "  python3 tests/worker-cert/build_real_payload.py \\\n"
            "    --worker-id host_57_131_20_173 \\\n"
            "    --destination drive-production\n\n"
            "  # Write to a file for shell piping via --payload-file:\n"
            "  python3 tests/worker-cert/build_real_payload.py \\\n"
            "    --worker-id host_57_131_20_173 \\\n"
            "    --output /tmp/payload.json \\\n"
            "    --strict\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--fixtures",
        default="tests/worker-cert/fixtures/assets.json",
        help="path to assets.json with the canonical asset_id set "
        "(default: tests/worker-cert/fixtures/assets.json)",
    )
    parser.add_argument(
        "--worker-id",
        help="worker_id label stamped into the payload's idempotency_key + "
        "scene text (required for build; ignored by selftest unless provided)",
    )
    parser.add_argument(
        "--destination",
        required=True,
        help="explicit delivery destination_id; implicit destinations are forbidden",
    )
    parser.add_argument(
        "--target-executor-id",
        default="scene.composite.v1@1",
        help="explicit target_executor_id (default: scene.composite.v1@1, "
        "the canonical executor; avoids relying on the placement matcher "
        "default derivation)",
    )
    parser.add_argument(
        "--idempotency-suffix",
        type=int,
        default=0,
        help="optional integer appended to idempotency_key to disambiguate "
        "back-to-back smokes (default: 0; epoch seconds in the body already "
        "distinguish by the second)",
    )
    parser.add_argument(
        "--scenes-count",
        type=int,
        default=2,
        help="number of scenes to generate by modulo-cycling through "
        "fixtures['clips'] and fixtures['voiceover'] (default: 2, the "
        "canonical smoke_one.sh shape; >=10 exercises the scene-concat "
        "engine path used by multi_scene_concat smokes)",
    )
    parser.add_argument(
        "--duration-per-scene",
        type=int,
        default=3,
        help="duration_seconds stamped on every generated scene (default: 3, "
        "matches smoke_one.sh; multi_scene_concat smokes use 2 to keep total "
        "render time under the operator poll budget while still exercising "
        "per-scene stitching)",
    )
    parser.add_argument(
        "--output", help="write payload to this file path instead of stdout"
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="run output against the forbidden-pattern validator (defensive — "
        "this script never emits those by construction, but a regression in "
        "the scene/voiceover composers would surface here)",
    )
    parser.add_argument(
        "--no-placement-pin",
        action="store_true",
        help="omit placement_pin_worker_id from the payload so the master "
        "schedules the job on any eligible worker (default: pin to --worker-id). "
        "Use for fleet-distribution tests where jobs must fan out across workers.",
    )

    sub = parser.add_subparsers(dest="cmd")
    sub.required = False  # default = build
    sub.add_parser("selftest", help="dry-run without I/O; asserts no forbidden "
                    "pattern on a built payload; honors --scenes-count so "
                    "the multi_scene_concat regression shield also runs")

    args = parser.parse_args(argv)

    if args.cmd == "selftest":
        return cmd_selftest(args)
    if not args.worker_id:
        print("error: --worker-id is required for build", file=sys.stderr)
        return 2
    return cmd_build(args)


if __name__ == "__main__":
    sys.exit(main())
