run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - govet
    - goimports
    - ineffassign
    - unused
    - funlen
issues:
  exclude-rules:
    - path: .*\.generated\.go
      linters:
        - all
    - linters:
        - errcheck
      text: Error return value of .* is not checked
linters-settings:
  funlen:
    lines: 600
    statements: -1
    complexity: -1
