version: "2"

linters:
  default: none
  enable:
    - funlen
    - govet
    - ineffassign
    - unused
  settings:
    funlen:
      lines: 600
      statements: -1
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: .*\.generated\.go
        linters:
          - all
      - linters:
          - errcheck
        text: Error return value of .* is not checked
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
