// Code generated by shared/telemetry/cmd/cataloggen; DO NOT EDIT.
// Source: shared/telemetry/schema/catalog.json
#pragma once

#include <array>
#include <string_view>

namespace velox::telemetry::catalog {

inline constexpr int kSchemaVersion = 1;

inline constexpr std::string_view kOriginMaster = "master";
inline constexpr std::string_view kOriginWorker = "worker";
inline constexpr std::string_view kOriginEngine = "engine";
inline constexpr std::string_view kOriginFFmpeg = "ffmpeg";
inline constexpr std::string_view kOriginUpload = "upload";
inline constexpr std::string_view kOriginValidation = "validation";
inline constexpr std::string_view kScopeJob = "job";
inline constexpr std::string_view kScopeTask = "task";
inline constexpr std::string_view kScopeAttempt = "attempt";
inline constexpr std::string_view kScopeSegment = "segment";
inline constexpr std::string_view kScopeAudioTrack = "audio_track";
inline constexpr std::string_view kScopeSubtitleTrack = "subtitle_track";
inline constexpr std::string_view kScopeArtifact = "artifact";
inline constexpr std::string_view kStatusOk = "ok";
inline constexpr std::string_view kStatusFailed = "failed";
inline constexpr std::string_view kEventTypeCompleted = "completed";
inline constexpr std::string_view kEventTypeFailed = "failed";
inline constexpr std::string_view kEventTypeStarted = "started";
inline constexpr std::string_view kEventTypeProgress = "progress";
struct EventDescriptor {
    std::string_view key;
    std::string_view component;
    std::string_view action;
    std::string_view origin;
    std::string_view scope;
    std::string_view phase;
    std::string_view event_type;
    std::string_view kind;
    std::string_view unit;
    std::string_view timing_mode;
    std::string_view aggregation;
    std::string_view cardinality;
    std::string_view owner;
};

inline constexpr std::array<EventDescriptor, 159> kEvents = {{
    { "attempt.failure", "attempt", "failure", "worker", "attempt", "finalize", "", "counter", "count", "none", "sum", "per_attempt", "worker" },
    { "attempt.retry", "attempt", "retry", "worker", "attempt", "finalize", "", "counter", "count", "none", "sum", "per_attempt", "worker" },
    { "audio.summary", "audio", "summary", "validation", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "validation" },
    { "control.grpc.offer_rtt", "control.grpc", "offer_rtt", "master", "task", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_task", "master" },
    { "control.grpc.reconnect", "control.grpc", "reconnect", "master", "attempt", "queue", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "master" },
    { "control.grpc.result_ack_wait", "control.grpc", "result_ack_wait", "master", "task", "finalize", "", "duration", "milliseconds", "span_child", "sum", "per_task", "master" },
    { "control.grpc.result_send", "control.grpc", "result_send", "master", "task", "upload", "", "duration", "milliseconds", "span_child", "sum", "per_task", "master" },
    { "control.grpc.send_queue_wait", "control.grpc", "send_queue_wait", "master", "task", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_task", "master" },
    { "control.heartbeat_rtt", "control", "heartbeat_rtt", "master", "attempt", "queue", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "master" },
    { "control.lease_renewal_rtt", "control", "lease_renewal_rtt", "master", "attempt", "queue", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "master" },
    { "db.artifact_commit_tx", "db", "artifact_commit_tx", "master", "artifact", "finalize", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "master" },
    { "db.claim_tx", "db", "claim_tx", "master", "attempt", "queue", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "master" },
    { "db.enqueue_tx", "db", "enqueue_tx", "master", "attempt", "queue", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "master" },
    { "db.lock_wait", "db", "lock_wait", "master", "attempt", "queue", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "master" },
    { "db.query", "db", "query", "master", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "master" },
    { "db.result_ingest_tx", "db", "result_ingest_tx", "master", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "master" },
    { "db.wal_checkpoint", "db", "wal_checkpoint", "master", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "master" },
    { "engine.audio.channel_convert", "engine.audio", "channel_convert", "engine", "audio_track", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_track", "media_engine" },
    { "engine.audio.ducking", "engine.audio", "ducking", "engine", "audio_track", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_track", "media_engine" },
    { "engine.audio.encode", "engine.audio", "encode", "engine", "audio_track", "encode", "", "duration", "milliseconds", "span_child", "sum", "per_track", "encoder" },
    { "engine.audio.limit", "engine.audio", "limit", "engine", "audio_track", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_track", "media_engine" },
    { "engine.audio.loudness_scan", "engine.audio", "loudness_scan", "engine", "audio_track", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_track", "media_engine" },
    { "engine.audio.mix", "engine.audio", "mix", "engine", "audio_track", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_track", "media_engine" },
    { "engine.audio.music_decode", "engine.audio", "music_decode", "engine", "audio_track", "decode", "", "duration", "milliseconds", "span_child", "sum", "per_track", "decoder" },
    { "engine.audio.resample", "engine.audio", "resample", "engine", "audio_track", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_track", "media_engine" },
    { "engine.audio.sfx_decode", "engine.audio", "sfx_decode", "engine", "audio_track", "decode", "", "duration", "milliseconds", "span_child", "sum", "per_track", "decoder" },
    { "engine.audio.timeline_align", "engine.audio", "timeline_align", "engine", "audio_track", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_track", "media_engine" },
    { "engine.audio.voiceover_decode", "engine.audio", "voiceover_decode", "engine", "audio_track", "decode", "", "duration", "milliseconds", "span_child", "sum", "per_track", "decoder" },
    { "engine.color_convert_in", "engine", "color_convert_in", "engine", "segment", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "media_engine" },
    { "engine.color_convert_out", "engine", "color_convert_out", "engine", "segment", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "media_engine" },
    { "engine.composite", "engine", "composite", "engine", "segment", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "media_engine" },
    { "engine.concat", "engine", "concat", "engine", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "media_engine" },
    { "engine.crop", "engine", "crop", "engine", "segment", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "media_engine" },
    { "engine.encode.flush", "engine.encode", "flush", "engine", "segment", "encode", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "encoder" },
    { "engine.encode.frame_submit", "engine.encode", "frame_submit", "engine", "segment", "encode", "", "counter", "count", "none", "sum", "per_segment", "encoder" },
    { "engine.encode.setup", "engine.encode", "setup", "engine", "segment", "encode", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "encoder" },
    { "engine.frame_pipeline.encode_segment", "engine.frame_pipeline", "encode_segment", "engine", "segment", "encode", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "media_engine" },
    { "engine.input.demux_probe", "engine.input", "demux_probe", "engine", "segment", "decode", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "media_engine" },
    { "engine.input.duration_probe", "engine.input", "duration_probe", "engine", "segment", "decode", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "media_engine" },
    { "engine.input.keyframe_scan", "engine.input", "keyframe_scan", "engine", "segment", "decode", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "media_engine" },
    { "engine.input.open", "engine.input", "open", "engine", "segment", "decode", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "media_engine" },
    { "engine.input.seek", "engine.input", "seek", "engine", "segment", "decode", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "media_engine" },
    { "engine.input.stream_discovery", "engine.input", "stream_discovery", "engine", "segment", "decode", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "media_engine" },
    { "engine.mask", "engine", "mask", "engine", "segment", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "media_engine" },
    { "engine.mixed_packet_mux", "engine", "mixed_packet_mux", "engine", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "media_engine" },
    { "engine.mux.audio", "engine.mux", "audio", "engine", "audio_track", "encode", "", "duration", "milliseconds", "span_child", "sum", "per_track", "muxer" },
    { "engine.mux.header", "engine.mux", "header", "engine", "artifact", "encode", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "muxer" },
    { "engine.mux.packet_write", "engine.mux", "packet_write", "engine", "artifact", "encode", "", "counter", "count", "none", "sum", "per_artifact", "muxer" },
    { "engine.mux.trailer", "engine.mux", "trailer", "engine", "artifact", "encode", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "muxer" },
    { "engine.opacity", "engine", "opacity", "engine", "segment", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "media_engine" },
    { "engine.output.fsync", "engine.output", "fsync", "engine", "artifact", "finalize", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "muxer" },
    { "engine.packet_mux", "engine", "packet_mux", "engine", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "media_engine" },
    { "engine.render", "engine", "render", "engine", "attempt", "render", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "media_engine" },
    { "engine.scale", "engine", "scale", "engine", "segment", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "media_engine" },
    { "engine.simulate", "engine", "simulate", "engine", "segment", "simulate", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "media_engine" },
    { "engine.transform", "engine", "transform", "engine", "segment", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "media_engine" },
    { "engine.video.decode", "engine.video", "decode", "engine", "segment", "decode", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "decoder" },
    { "engine.video.frame_reorder", "engine.video", "frame_reorder", "engine", "segment", "decode", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "decoder" },
    { "engine.video.hw_download", "engine.video", "hw_download", "engine", "segment", "decode", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "decoder" },
    { "engine.video.timestamp_normalize", "engine.video", "timestamp_normalize", "engine", "segment", "decode", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "decoder" },
    { "ffmpeg.encode_segment", "ffmpeg", "encode_segment", "ffmpeg", "segment", "encode", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "process_runner" },
    { "ffmpeg.progress", "ffmpeg", "progress", "ffmpeg", "segment", "encode", "", "counter", "count", "none", "sum", "per_segment", "process_runner" },
    { "io.summary", "io", "summary", "validation", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "validation" },
    { "master.artifact.sha_mismatch", "master.artifact", "sha_mismatch", "master", "attempt", "finalize", "", "counter", "count", "none", "sum", "per_attempt", "master" },
    { "master.commit.transaction", "master.commit", "transaction", "master", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "master" },
    { "master.commit_ack.send", "master.commit_ack", "send", "master", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "master" },
    { "master.enqueue.transaction", "master.enqueue", "transaction", "master", "task", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_task", "master" },
    { "master.http.auth", "master.http", "auth", "master", "job", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_job", "master" },
    { "master.http.decode", "master.http", "decode", "master", "job", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_job", "master" },
    { "master.intake.validate", "master.intake", "validate", "master", "task", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_task", "master" },
    { "master.lease.issue", "master.lease", "issue", "master", "task", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_task", "master" },
    { "master.manifest.fetch", "master.manifest", "fetch", "master", "task", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_task", "asset_manifest" },
    { "master.manifest.hash_verify", "master.manifest", "hash_verify", "master", "task", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_task", "asset_manifest" },
    { "master.manifest.parse", "master.manifest", "parse", "master", "task", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_task", "asset_manifest" },
    { "master.offer.accept_to_start", "master.offer", "accept_to_start", "master", "task", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_task", "master" },
    { "master.offer.offer_to_accept", "master.offer", "offer_to_accept", "master", "task", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_task", "master" },
    { "master.offer.send", "master.offer", "send", "master", "task", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_task", "master" },
    { "master.payload.normalize", "master.payload", "normalize", "master", "task", "compile", "", "duration", "milliseconds", "span_child", "sum", "per_task", "master" },
    { "master.placement.candidate_scan", "master.placement", "candidate_scan", "master", "task", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_task", "master" },
    { "master.placement.match", "master.placement", "match", "master", "task", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_task", "master" },
    { "master.placement.rejection", "master.placement", "rejection", "master", "task", "queue", "", "counter", "count", "none", "sum", "per_task", "master" },
    { "master.placement.snapshot_load", "master.placement", "snapshot_load", "master", "task", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_task", "master" },
    { "master.plan.compile", "master.plan", "compile", "master", "task", "compile", "", "duration", "milliseconds", "span_child", "sum", "per_task", "render_plan" },
    { "master.queue.ready_wait", "master.queue", "ready_wait", "master", "task", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_task", "master" },
    { "master.upload.verify", "master.upload", "verify", "upload", "artifact", "finalize", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "publisher" },
    { "master.upload_plan.create", "master.upload_plan", "create", "upload", "artifact", "upload", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "uploader" },
    { "quality.audio_sync", "quality", "audio_sync", "validation", "artifact", "finalize", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "validation" },
    { "quality.black_frame_scan", "quality", "black_frame_scan", "validation", "artifact", "finalize", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "validation" },
    { "quality.duration_check", "quality", "duration_check", "validation", "artifact", "finalize", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "validation" },
    { "quality.ffprobe", "quality", "ffprobe", "validation", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "validation" },
    { "quality.sha256", "quality", "sha256", "validation", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "validation" },
    { "quality.silence_scan", "quality", "silence_scan", "validation", "artifact", "finalize", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "validation" },
    { "quality.stream_check", "quality", "stream_check", "validation", "artifact", "finalize", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "validation" },
    { "quality.subtitle_timeline", "quality", "subtitle_timeline", "validation", "subtitle_track", "finalize", "", "duration", "milliseconds", "span_child", "sum", "per_track", "validation" },
    { "quality.summary", "quality", "summary", "validation", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "validation" },
    { "retry.summary", "retry", "summary", "validation", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "validation" },
    { "runner.cache_lookup", "runner", "cache_lookup", "worker", "attempt", "cache_lookup", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "cache_resolver" },
    { "runner.execute", "runner", "execute", "worker", "attempt", "render", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "task_runner" },
    { "runner.prefetch", "runner", "prefetch", "worker", "attempt", "asset_wait", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "worker" },
    { "runner.report", "runner", "report", "worker", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "task_runner" },
    { "runner.run", "runner", "run", "worker", "attempt", "finalize", "failed", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "task_runner" },
    { "runner.upload", "runner", "upload", "worker", "attempt", "upload", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "uploader" },
    { "subtitle.ass_compile", "subtitle", "ass_compile", "validation", "subtitle_track", "compile", "", "duration", "milliseconds", "span_child", "sum", "per_track", "validation" },
    { "subtitle.audio_extract", "subtitle", "audio_extract", "validation", "subtitle_track", "compile", "", "duration", "milliseconds", "span_child", "sum", "per_track", "validation" },
    { "subtitle.burn_in", "subtitle", "burn_in", "engine", "subtitle_track", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_track", "media_engine" },
    { "subtitle.font_fallback", "subtitle", "font_fallback", "engine", "subtitle_track", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_track", "media_engine" },
    { "subtitle.font_load", "subtitle", "font_load", "engine", "subtitle_track", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_track", "media_engine" },
    { "subtitle.glyph_raster", "subtitle", "glyph_raster", "engine", "subtitle_track", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_track", "media_engine" },
    { "subtitle.layout", "subtitle", "layout", "engine", "subtitle_track", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_track", "media_engine" },
    { "subtitle.parse", "subtitle", "parse", "engine", "subtitle_track", "composite", "", "duration", "milliseconds", "span_child", "sum", "per_track", "media_engine" },
    { "subtitle.segment", "subtitle", "segment", "validation", "subtitle_track", "compile", "", "duration", "milliseconds", "span_child", "sum", "per_track", "validation" },
    { "subtitle.summary", "subtitle", "summary", "validation", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "validation" },
    { "subtitle.transcribe", "subtitle", "transcribe", "validation", "subtitle_track", "compile", "", "duration", "milliseconds", "span_child", "sum", "per_track", "validation" },
    { "subtitle.word_alignment", "subtitle", "word_alignment", "validation", "subtitle_track", "compile", "", "duration", "milliseconds", "span_child", "sum", "per_track", "validation" },
    { "waste.summary", "waste", "summary", "validation", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "validation" },
    { "worker.asset.bind", "worker.asset", "bind", "worker", "task", "asset_wait", "", "duration", "milliseconds", "span_child", "sum", "per_task", "downloader" },
    { "worker.asset.connect", "worker.asset", "connect", "worker", "task", "download", "", "duration", "milliseconds", "span_child", "sum", "per_task", "downloader" },
    { "worker.asset.disk_write", "worker.asset", "disk_write", "worker", "artifact", "download", "", "duration", "milliseconds", "span_child", "sum", "per_asset", "downloader" },
    { "worker.asset.dns", "worker.asset", "dns", "worker", "task", "download", "", "duration", "milliseconds", "span_child", "sum", "per_task", "downloader" },
    { "worker.asset.final_hash", "worker.asset", "final_hash", "worker", "artifact", "download", "", "duration", "milliseconds", "span_child", "sum", "per_asset", "downloader" },
    { "worker.asset.fsync", "worker.asset", "fsync", "worker", "artifact", "download", "", "duration", "milliseconds", "span_child", "sum", "per_asset", "downloader" },
    { "worker.asset.progress_checkpoint", "worker.asset", "progress_checkpoint", "worker", "task", "download", "", "counter", "count", "none", "sum", "per_task", "downloader" },
    { "worker.asset.resolve", "worker.asset", "resolve", "worker", "task", "asset_wait", "", "duration", "milliseconds", "span_child", "sum", "per_task", "downloader" },
    { "worker.asset.transfer", "worker.asset", "transfer", "worker", "task", "download", "", "duration", "milliseconds", "span_child", "sum", "per_task", "downloader" },
    { "worker.asset.ttfb", "worker.asset", "ttfb", "worker", "task", "download", "", "duration", "milliseconds", "span_child", "sum", "per_task", "downloader" },
    { "worker.cache.eviction", "worker.cache", "eviction", "worker", "task", "cache_lookup", "", "counter", "count", "none", "sum", "per_task", "cache_resolver" },
    { "worker.cache.hash_verify", "worker.cache", "hash_verify", "worker", "task", "cache_lookup", "", "duration", "milliseconds", "span_child", "sum", "per_task", "cache_resolver" },
    { "worker.cache.hit_read", "worker.cache", "hit_read", "worker", "task", "cache_lookup", "", "counter", "count", "none", "sum", "per_task", "cache_resolver" },
    { "worker.cache.lookup", "worker.cache", "lookup", "worker", "task", "cache_lookup", "", "duration", "milliseconds", "span_child", "sum", "per_task", "cache_resolver" },
    { "worker.cache.metadata_read", "worker.cache", "metadata_read", "worker", "task", "cache_lookup", "", "duration", "milliseconds", "span_child", "sum", "per_task", "cache_resolver" },
    { "worker.cache.miss", "worker.cache", "miss", "worker", "task", "cache_lookup", "", "counter", "count", "none", "sum", "per_task", "cache_resolver" },
    { "worker.commit_ack_wait", "worker", "commit_ack_wait", "upload", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "uploader" },
    { "worker.disk.wait", "worker.disk", "wait", "worker", "attempt", "render", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "attempt_telemetry" },
    { "worker.engine.binary_resolve", "worker.engine", "binary_resolve", "worker", "attempt", "render", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "process_runner" },
    { "worker.engine.first_progress", "worker.engine", "first_progress", "worker", "attempt", "render", "", "counter", "count", "none", "sum", "per_attempt", "process_runner" },
    { "worker.engine.output_stat", "worker.engine", "output_stat", "worker", "artifact", "finalize", "", "gauge", "count", "none", "last", "per_artifact", "publisher" },
    { "worker.engine.sidecar_read", "worker.engine", "sidecar_read", "worker", "artifact", "finalize", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "process_runner" },
    { "worker.engine.spawn", "worker.engine", "spawn", "worker", "attempt", "render", "", "counter", "count", "none", "sum", "per_attempt", "process_runner" },
    { "worker.engine.tempdir_create", "worker.engine", "tempdir_create", "worker", "attempt", "render", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "process_runner" },
    { "worker.engine.usage", "worker.engine", "usage", "worker", "attempt", "render", "", "counter", "count", "none", "sum", "per_attempt", "process_runner" },
    { "worker.engine.wait", "worker.engine", "wait", "worker", "attempt", "render", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "process_runner" },
    { "worker.output.cleanup", "worker.output", "cleanup", "worker", "artifact", "finalize", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "worker" },
    { "worker.output.declare", "worker.output", "declare", "upload", "artifact", "upload", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "uploader" },
    { "worker.output.hash", "worker.output", "hash", "upload", "artifact", "upload", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "publisher" },
    { "worker.parallel.queue_wait", "worker.parallel", "queue_wait", "worker", "segment", "queue", "", "duration", "milliseconds", "span_child", "sum", "per_segment", "worker" },
    { "worker.parallel.segment_finish", "worker.parallel", "segment_finish", "worker", "segment", "finalize", "", "counter", "count", "none", "sum", "per_segment", "worker" },
    { "worker.parallel.segment_start", "worker.parallel", "segment_start", "worker", "segment", "render", "", "counter", "count", "none", "sum", "per_segment", "worker" },
    { "worker.plan.compile", "worker.plan", "compile", "worker", "task", "compile", "", "duration", "milliseconds", "span_child", "sum", "per_task", "render_plan" },
    { "worker.plan.deserialize", "worker.plan", "deserialize", "worker", "task", "compile", "", "duration", "milliseconds", "span_child", "sum", "per_task", "render_plan" },
    { "worker.plan.resolve_assets", "worker.plan", "resolve_assets", "worker", "task", "compile", "", "duration", "milliseconds", "span_child", "sum", "per_task", "asset_manifest" },
    { "worker.plan.serialize", "worker.plan", "serialize", "worker", "task", "compile", "", "duration", "milliseconds", "span_child", "sum", "per_task", "render_plan" },
    { "worker.plan.validate", "worker.plan", "validate", "worker", "task", "compile", "", "duration", "milliseconds", "span_child", "sum", "per_task", "render_plan" },
    { "worker.plan.write", "worker.plan", "write", "worker", "artifact", "compile", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "render_plan" },
    { "worker.temp.create", "worker.temp", "create", "worker", "attempt", "render", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "attempt_telemetry" },
    { "worker.temp.delete", "worker.temp", "delete", "worker", "attempt", "finalize", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "attempt_telemetry" },
    { "worker.temp.read", "worker.temp", "read", "worker", "attempt", "render", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "attempt_telemetry" },
    { "worker.temp.write", "worker.temp", "write", "worker", "attempt", "render", "", "duration", "milliseconds", "exclusive", "sum", "per_attempt", "attempt_telemetry" },
    { "worker.upload.connect", "worker.upload", "connect", "upload", "artifact", "upload", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "uploader" },
    { "worker.upload.transfer", "worker.upload", "transfer", "upload", "artifact", "upload", "", "duration", "milliseconds", "span_child", "sum", "per_artifact", "uploader" },
}};

struct FactOwner {
    std::string_view name;
    std::string_view owner;
};

inline constexpr std::array<FactOwner, 14> kFacts = {{
    { "artifact_sha", "publisher" },
    { "asset_sha", "asset_manifest" },
    { "cache_hit_miss", "cache_resolver" },
    { "clip_count", "render_plan" },
    { "cpu_ram_disk", "attempt_telemetry" },
    { "downloaded_bytes", "downloader" },
    { "expected_duration", "render_plan" },
    { "frames_decoded", "decoder" },
    { "frames_encoded", "encoder" },
    { "mux_bytes", "muxer" },
    { "packets_read", "media_engine" },
    { "process_spawn", "process_runner" },
    { "task_status", "task_runner" },
    { "worker_status", "worker_state" },
}};

struct PhaseTaxon {
    std::string_view name;
    std::string_view role;
    std::string_view parent;
};

inline constexpr std::array<PhaseTaxon, 12> kPhases = {{
    { "asset_wait", "exclusive", "" },
    { "cache_lookup", "exclusive", "" },
    { "compile", "exclusive", "" },
    { "composite", "span_parent", "render" },
    { "decode", "span_parent", "render" },
    { "download", "exclusive", "" },
    { "encode", "span_parent", "render" },
    { "finalize", "exclusive", "" },
    { "queue", "exclusive", "" },
    { "render", "exclusive", "" },
    { "simulate", "exclusive", "" },
    { "upload", "exclusive", "" },
}};

constexpr bool IsAccountedTopLevelPhase(std::string_view phase) {
    for (const auto& taxon : kPhases) {
        if (taxon.name == phase) return taxon.role == "exclusive";
    }
    return false;
}

constexpr bool IsCanonicalOrigin(std::string_view value) {
    return value == kOriginMaster || value == kOriginWorker || value == kOriginEngine ||
           value == kOriginFFmpeg || value == kOriginUpload || value == kOriginValidation;
}

constexpr bool IsCanonicalScope(std::string_view value) {
    return value == kScopeJob || value == kScopeTask || value == kScopeAttempt ||
           value == kScopeSegment || value == kScopeAudioTrack ||
           value == kScopeSubtitleTrack || value == kScopeArtifact;
}

constexpr bool IsCanonicalStatus(std::string_view value) {
    return value == kStatusOk || value == kStatusFailed;
}

constexpr bool IsCanonicalEventType(std::string_view value) {
    return value == kEventTypeCompleted || value == kEventTypeFailed ||
           value == kEventTypeStarted || value == kEventTypeProgress;
}

constexpr const EventDescriptor* FindEvent(std::string_view component, std::string_view action) {
    for (const auto& event : kEvents) {
        if (event.component == component && event.action == action) return &event;
    }
    return nullptr;
}

constexpr bool IsCatalogEvent(std::string_view component, std::string_view action) {
    return FindEvent(component, action) != nullptr;
}

} // namespace velox::telemetry::catalog
