// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: velox/control/master_to_worker.proto

// Proto definition for Velox Worker-Control bidirectional stream.
// Both master (DataServer) and worker (worker-agent-go) use this contract
// for typed, versioned control-plane communication.
//
// Phase 2 (typed protobuf): message types are strongly typed with oneof
// instead of the legacy TransportMessage { string type; Struct payload; }.
// google.protobuf.Struct is retained only for genuinely dynamic fields
// (extra, job_payload, params, configuration) — TaskResult.metrics is now
// fully typed (TaskExecutionMetrics) per the scorecard-of-efficiency
// design (taskattempts.report.go + observability.service.go).
//
// ProtocolVersion bumped to "v3" — old v2 workers (TaskResult.metrics as
// google.protobuf.Struct) are no longer accepted at the gRPC handshake.
// The PR-5 cutover is forward-only: drain the fleet before deploy.
//
// Phase E cutover (May 2026): the MasterToWorkerEnvelope oneof no longer
// emits a forward-only JobAvailable notification. Wire-level field
// number 21 is reserved-but-unused to preserve field-number compatibility
// with previously-deployed workers/masters.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------------------------------------------------------
// Master -> Worker
// ---------------------------------------------------------
type MasterToWorkerEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	WorkerId        string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SequenceNumber  int64                  `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	SentAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*MasterToWorkerEnvelope_HelloAck
	//	*MasterToWorkerEnvelope_TaskOffer
	//	*MasterToWorkerEnvelope_TaskLeaseGranted
	//	*MasterToWorkerEnvelope_Command
	//	*MasterToWorkerEnvelope_CancelJob
	//	*MasterToWorkerEnvelope_Drain
	//	*MasterToWorkerEnvelope_ConfigurationUpdate
	//	*MasterToWorkerEnvelope_LeaseRevoked
	//	*MasterToWorkerEnvelope_Ping
	//	*MasterToWorkerEnvelope_ArtifactEarlyUploadPlan
	//	*MasterToWorkerEnvelope_ArtifactUploadPlan
	//	*MasterToWorkerEnvelope_TaskCommitAck
	//	*MasterToWorkerEnvelope_TaskResultAck
	//	*MasterToWorkerEnvelope_FutureAssetPlan
	//	*MasterToWorkerEnvelope_CancelPrefetch
	Msg           isMasterToWorkerEnvelope_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterToWorkerEnvelope) Reset() {
	*x = MasterToWorkerEnvelope{}
	mi := &file_velox_control_master_to_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterToWorkerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterToWorkerEnvelope) ProtoMessage() {}

func (x *MasterToWorkerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_master_to_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterToWorkerEnvelope.ProtoReflect.Descriptor instead.
func (*MasterToWorkerEnvelope) Descriptor() ([]byte, []int) {
	return file_velox_control_master_to_worker_proto_rawDescGZIP(), []int{0}
}

func (x *MasterToWorkerEnvelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MasterToWorkerEnvelope) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *MasterToWorkerEnvelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MasterToWorkerEnvelope) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *MasterToWorkerEnvelope) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *MasterToWorkerEnvelope) GetMsg() isMasterToWorkerEnvelope_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetTaskOffer() *TaskOffer {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_TaskOffer); ok {
			return x.TaskOffer
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetTaskLeaseGranted() *TaskLeaseGranted {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_TaskLeaseGranted); ok {
			return x.TaskLeaseGranted
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetCancelJob() *CancelJob {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_CancelJob); ok {
			return x.CancelJob
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetDrain() *Drain {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetConfigurationUpdate() *ConfigurationUpdate {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_ConfigurationUpdate); ok {
			return x.ConfigurationUpdate
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetLeaseRevoked() *LeaseRevoked {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_LeaseRevoked); ok {
			return x.LeaseRevoked
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetArtifactEarlyUploadPlan() *ArtifactEarlyUploadPlan {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_ArtifactEarlyUploadPlan); ok {
			return x.ArtifactEarlyUploadPlan
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetArtifactUploadPlan() *ArtifactUploadPlan {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_ArtifactUploadPlan); ok {
			return x.ArtifactUploadPlan
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetTaskCommitAck() *TaskCommitAck {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_TaskCommitAck); ok {
			return x.TaskCommitAck
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetTaskResultAck() *TaskResultAck {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_TaskResultAck); ok {
			return x.TaskResultAck
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetFutureAssetPlan() *FutureAssetPlan {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_FutureAssetPlan); ok {
			return x.FutureAssetPlan
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetCancelPrefetch() *CancelPrefetch {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_CancelPrefetch); ok {
			return x.CancelPrefetch
		}
	}
	return nil
}

type isMasterToWorkerEnvelope_Msg interface {
	isMasterToWorkerEnvelope_Msg()
}

type MasterToWorkerEnvelope_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,20,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type MasterToWorkerEnvelope_TaskOffer struct {
	// 22 (JobOffer) — superseded by TaskOffer (30). Reserved.
	TaskOffer *TaskOffer `protobuf:"bytes,30,opt,name=task_offer,json=taskOffer,proto3,oneof"`
}

type MasterToWorkerEnvelope_TaskLeaseGranted struct {
	// 23 (JobLeaseGranted) — superseded by TaskLeaseGranted (31). Reserved.
	TaskLeaseGranted *TaskLeaseGranted `protobuf:"bytes,31,opt,name=task_lease_granted,json=taskLeaseGranted,proto3,oneof"`
}

type MasterToWorkerEnvelope_Command struct {
	Command *Command `protobuf:"bytes,24,opt,name=command,proto3,oneof"`
}

type MasterToWorkerEnvelope_CancelJob struct {
	CancelJob *CancelJob `protobuf:"bytes,25,opt,name=cancel_job,json=cancelJob,proto3,oneof"`
}

type MasterToWorkerEnvelope_Drain struct {
	Drain *Drain `protobuf:"bytes,26,opt,name=drain,proto3,oneof"`
}

type MasterToWorkerEnvelope_ConfigurationUpdate struct {
	ConfigurationUpdate *ConfigurationUpdate `protobuf:"bytes,27,opt,name=configuration_update,json=configurationUpdate,proto3,oneof"`
}

type MasterToWorkerEnvelope_LeaseRevoked struct {
	LeaseRevoked *LeaseRevoked `protobuf:"bytes,28,opt,name=lease_revoked,json=leaseRevoked,proto3,oneof"`
}

type MasterToWorkerEnvelope_Ping struct {
	Ping *Ping `protobuf:"bytes,29,opt,name=ping,proto3,oneof"`
}

type MasterToWorkerEnvelope_ArtifactEarlyUploadPlan struct {
	// Progressive artifact upload intent/plan. These messages are additive;
	// legacy TaskOutputDeclared/ArtifactUploadPlan remain unchanged.
	ArtifactEarlyUploadPlan *ArtifactEarlyUploadPlan `protobuf:"bytes,39,opt,name=artifact_early_upload_plan,json=artifactEarlyUploadPlan,proto3,oneof"`
}

type MasterToWorkerEnvelope_ArtifactUploadPlan struct {
	// Phase 3.4 / 3.6 (Artifact Commit Protocol) — typed
	// upload-plan-and-commit-ack pipeline. The UploadPlan
	// (Fase 3.4) carries the per-manifest upload targets plus the
	// master's canonical commit_id; TaskCommitAck (Fase 3.6) is
	// the master's terminal signal that the attempt is durable
	// and the worker can clean up the local spool row.
	ArtifactUploadPlan *ArtifactUploadPlan `protobuf:"bytes,32,opt,name=artifact_upload_plan,json=artifactUploadPlan,proto3,oneof"`
}

type MasterToWorkerEnvelope_TaskCommitAck struct {
	TaskCommitAck *TaskCommitAck `protobuf:"bytes,33,opt,name=task_commit_ack,json=taskCommitAck,proto3,oneof"`
}

type MasterToWorkerEnvelope_TaskResultAck struct {
	// Acknowledgement sent by the master after processing a TaskResult.
	// Carries the attempt_id and an optional error (e.g. "report_conflict").
	TaskResultAck *TaskResultAck `protobuf:"bytes,35,opt,name=task_result_ack,json=taskResultAck,proto3,oneof"`
}

type MasterToWorkerEnvelope_FutureAssetPlan struct {
	// Versioned full snapshot of the worker-scoped future asset plan.
	// The worker reconciles this snapshot; it is not a second download
	// protocol. Physical transfers remain owned by the canonical cache
	// resolver / AssetDownloadManager.
	FutureAssetPlan *FutureAssetPlan `protobuf:"bytes,36,opt,name=future_asset_plan,json=futureAssetPlan,proto3,oneof"`
}

type MasterToWorkerEnvelope_CancelPrefetch struct {
	// Low-latency cancellation hint. The next FutureAssetPlan remains the
	// reconciliation source of truth when this message is lost.
	CancelPrefetch *CancelPrefetch `protobuf:"bytes,37,opt,name=cancel_prefetch,json=cancelPrefetch,proto3,oneof"`
}

func (*MasterToWorkerEnvelope_HelloAck) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_TaskOffer) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_TaskLeaseGranted) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_Command) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_CancelJob) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_Drain) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_ConfigurationUpdate) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_LeaseRevoked) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_Ping) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_ArtifactEarlyUploadPlan) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_ArtifactUploadPlan) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_TaskCommitAck) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_TaskResultAck) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_FutureAssetPlan) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_CancelPrefetch) isMasterToWorkerEnvelope_Msg() {}

type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_velox_control_master_to_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_master_to_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_velox_control_master_to_worker_proto_rawDescGZIP(), []int{1}
}

type TaskOffer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId           string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AttemptId       string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	ExecutorId      string                 `protobuf:"bytes,4,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	ExecutorVersion int32                  `protobuf:"varint,5,opt,name=executor_version,json=executorVersion,proto3" json:"executor_version,omitempty"`
	TaskSpec        *structpb.Struct       `protobuf:"bytes,6,opt,name=task_spec,json=taskSpec,proto3" json:"task_spec,omitempty"`
	LeaseId         string                 `protobuf:"bytes,7,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseDeadline   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=lease_deadline,json=leaseDeadline,proto3" json:"lease_deadline,omitempty"`
	Requirements    *structpb.Struct       `protobuf:"bytes,9,opt,name=requirements,proto3" json:"requirements,omitempty"`
	OutputContract  *structpb.Struct       `protobuf:"bytes,10,opt,name=output_contract,json=outputContract,proto3" json:"output_contract,omitempty"`
	AttemptNumber   int32                  `protobuf:"varint,11,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	Revision        int32                  `protobuf:"varint,12,opt,name=revision,proto3" json:"revision,omitempty"`
	JobRevision     int32                  `protobuf:"varint,13,opt,name=job_revision,json=jobRevision,proto3" json:"job_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskOffer) Reset() {
	*x = TaskOffer{}
	mi := &file_velox_control_master_to_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOffer) ProtoMessage() {}

func (x *TaskOffer) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_master_to_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOffer.ProtoReflect.Descriptor instead.
func (*TaskOffer) Descriptor() ([]byte, []int) {
	return file_velox_control_master_to_worker_proto_rawDescGZIP(), []int{2}
}

func (x *TaskOffer) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskOffer) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskOffer) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskOffer) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *TaskOffer) GetExecutorVersion() int32 {
	if x != nil {
		return x.ExecutorVersion
	}
	return 0
}

func (x *TaskOffer) GetTaskSpec() *structpb.Struct {
	if x != nil {
		return x.TaskSpec
	}
	return nil
}

func (x *TaskOffer) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *TaskOffer) GetLeaseDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseDeadline
	}
	return nil
}

func (x *TaskOffer) GetRequirements() *structpb.Struct {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *TaskOffer) GetOutputContract() *structpb.Struct {
	if x != nil {
		return x.OutputContract
	}
	return nil
}

func (x *TaskOffer) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *TaskOffer) GetRevision() int32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *TaskOffer) GetJobRevision() int32 {
	if x != nil {
		return x.JobRevision
	}
	return 0
}

type TaskLeaseGranted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	JobId         string                 `protobuf:"bytes,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AttemptNumber int32                  `protobuf:"varint,5,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	Revision      int32                  `protobuf:"varint,6,opt,name=revision,proto3" json:"revision,omitempty"`
	JobRevision   int32                  `protobuf:"varint,7,opt,name=job_revision,json=jobRevision,proto3" json:"job_revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLeaseGranted) Reset() {
	*x = TaskLeaseGranted{}
	mi := &file_velox_control_master_to_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLeaseGranted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLeaseGranted) ProtoMessage() {}

func (x *TaskLeaseGranted) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_master_to_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLeaseGranted.ProtoReflect.Descriptor instead.
func (*TaskLeaseGranted) Descriptor() ([]byte, []int) {
	return file_velox_control_master_to_worker_proto_rawDescGZIP(), []int{3}
}

func (x *TaskLeaseGranted) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskLeaseGranted) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *TaskLeaseGranted) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskLeaseGranted) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskLeaseGranted) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *TaskLeaseGranted) GetRevision() int32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *TaskLeaseGranted) GetJobRevision() int32 {
	if x != nil {
		return x.JobRevision
	}
	return 0
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_velox_control_master_to_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_master_to_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_velox_control_master_to_worker_proto_rawDescGZIP(), []int{4}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Command) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Command) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

type CancelJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJob) Reset() {
	*x = CancelJob{}
	mi := &file_velox_control_master_to_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJob) ProtoMessage() {}

func (x *CancelJob) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_master_to_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJob.ProtoReflect.Descriptor instead.
func (*CancelJob) Descriptor() ([]byte, []int) {
	return file_velox_control_master_to_worker_proto_rawDescGZIP(), []int{5}
}

func (x *CancelJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type Drain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drain) Reset() {
	*x = Drain{}
	mi := &file_velox_control_master_to_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drain) ProtoMessage() {}

func (x *Drain) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_master_to_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drain.ProtoReflect.Descriptor instead.
func (*Drain) Descriptor() ([]byte, []int) {
	return file_velox_control_master_to_worker_proto_rawDescGZIP(), []int{6}
}

func (x *Drain) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ConfigurationUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configuration *structpb.Struct       `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationUpdate) Reset() {
	*x = ConfigurationUpdate{}
	mi := &file_velox_control_master_to_worker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationUpdate) ProtoMessage() {}

func (x *ConfigurationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_master_to_worker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationUpdate.ProtoReflect.Descriptor instead.
func (*ConfigurationUpdate) Descriptor() ([]byte, []int) {
	return file_velox_control_master_to_worker_proto_rawDescGZIP(), []int{7}
}

func (x *ConfigurationUpdate) GetConfiguration() *structpb.Struct {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type LeaseRevoked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRevoked) Reset() {
	*x = LeaseRevoked{}
	mi := &file_velox_control_master_to_worker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRevoked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRevoked) ProtoMessage() {}

func (x *LeaseRevoked) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_master_to_worker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRevoked.ProtoReflect.Descriptor instead.
func (*LeaseRevoked) Descriptor() ([]byte, []int) {
	return file_velox_control_master_to_worker_proto_rawDescGZIP(), []int{8}
}

func (x *LeaseRevoked) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *LeaseRevoked) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_velox_control_master_to_worker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_master_to_worker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_velox_control_master_to_worker_proto_rawDescGZIP(), []int{9}
}

// FutureAssetPlan is a complete, versioned worker-scoped snapshot. The
// planner keeps prefetch eligibility (distance <= 3) separate from cache
// retention protection (lookahead <= 10). No TaskState is changed by this
// message.
type FutureAssetPlan struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	Version             uint64                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	PlanId              string                  `protobuf:"bytes,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	WorkerId            string                  `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	GeneratedAt         *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	ExpiresAt           *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CurrentJobId        string                  `protobuf:"bytes,6,opt,name=current_job_id,json=currentJobId,proto3" json:"current_job_id,omitempty"`
	PrefetchJobs        []*PrefetchJob          `protobuf:"bytes,7,rep,name=prefetch_jobs,json=prefetchJobs,proto3" json:"prefetch_jobs,omitempty"`
	ProtectAssets       []*ProtectedFutureAsset `protobuf:"bytes,8,rep,name=protect_assets,json=protectAssets,proto3" json:"protect_assets,omitempty"`
	PrefetchHorizon     int32                   `protobuf:"varint,9,opt,name=prefetch_horizon,json=prefetchHorizon,proto3" json:"prefetch_horizon,omitempty"`
	ProtectionLookahead int32                   `protobuf:"varint,10,opt,name=protection_lookahead,json=protectionLookahead,proto3" json:"protection_lookahead,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FutureAssetPlan) Reset() {
	*x = FutureAssetPlan{}
	mi := &file_velox_control_master_to_worker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FutureAssetPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FutureAssetPlan) ProtoMessage() {}

func (x *FutureAssetPlan) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_master_to_worker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FutureAssetPlan.ProtoReflect.Descriptor instead.
func (*FutureAssetPlan) Descriptor() ([]byte, []int) {
	return file_velox_control_master_to_worker_proto_rawDescGZIP(), []int{10}
}

func (x *FutureAssetPlan) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FutureAssetPlan) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *FutureAssetPlan) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *FutureAssetPlan) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *FutureAssetPlan) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *FutureAssetPlan) GetCurrentJobId() string {
	if x != nil {
		return x.CurrentJobId
	}
	return ""
}

func (x *FutureAssetPlan) GetPrefetchJobs() []*PrefetchJob {
	if x != nil {
		return x.PrefetchJobs
	}
	return nil
}

func (x *FutureAssetPlan) GetProtectAssets() []*ProtectedFutureAsset {
	if x != nil {
		return x.ProtectAssets
	}
	return nil
}

func (x *FutureAssetPlan) GetPrefetchHorizon() int32 {
	if x != nil {
		return x.PrefetchHorizon
	}
	return 0
}

func (x *FutureAssetPlan) GetProtectionLookahead() int32 {
	if x != nil {
		return x.ProtectionLookahead
	}
	return 0
}

type PrefetchJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ReservationId string                 `protobuf:"bytes,3,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	TaskRevision  int32                  `protobuf:"varint,4,opt,name=task_revision,json=taskRevision,proto3" json:"task_revision,omitempty"`
	Distance      int32                  `protobuf:"varint,5,opt,name=distance,proto3" json:"distance,omitempty"`
	Assets        []*PrefetchAsset       `protobuf:"bytes,6,rep,name=assets,proto3" json:"assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefetchJob) Reset() {
	*x = PrefetchJob{}
	mi := &file_velox_control_master_to_worker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefetchJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefetchJob) ProtoMessage() {}

func (x *PrefetchJob) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_master_to_worker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefetchJob.ProtoReflect.Descriptor instead.
func (*PrefetchJob) Descriptor() ([]byte, []int) {
	return file_velox_control_master_to_worker_proto_rawDescGZIP(), []int{11}
}

func (x *PrefetchJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PrefetchJob) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PrefetchJob) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *PrefetchJob) GetTaskRevision() int32 {
	if x != nil {
		return x.TaskRevision
	}
	return 0
}

func (x *PrefetchJob) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *PrefetchJob) GetAssets() []*PrefetchAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type PrefetchAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetKey      string                 `protobuf:"bytes,1,opt,name=asset_key,json=assetKey,proto3" json:"asset_key,omitempty"`
	AssetId       string                 `protobuf:"bytes,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	MimeType      string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrefetchAsset) Reset() {
	*x = PrefetchAsset{}
	mi := &file_velox_control_master_to_worker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefetchAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefetchAsset) ProtoMessage() {}

func (x *PrefetchAsset) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_master_to_worker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefetchAsset.ProtoReflect.Descriptor instead.
func (*PrefetchAsset) Descriptor() ([]byte, []int) {
	return file_velox_control_master_to_worker_proto_rawDescGZIP(), []int{12}
}

func (x *PrefetchAsset) GetAssetKey() string {
	if x != nil {
		return x.AssetKey
	}
	return ""
}

func (x *PrefetchAsset) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *PrefetchAsset) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *PrefetchAsset) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *PrefetchAsset) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *PrefetchAsset) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type ProtectedFutureAsset struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AssetKey        string                 `protobuf:"bytes,1,opt,name=asset_key,json=assetKey,proto3" json:"asset_key,omitempty"`
	FutureRefCount  int32                  `protobuf:"varint,2,opt,name=future_ref_count,json=futureRefCount,proto3" json:"future_ref_count,omitempty"`
	NextUseDistance int32                  `protobuf:"varint,3,opt,name=next_use_distance,json=nextUseDistance,proto3" json:"next_use_distance,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProtectedFutureAsset) Reset() {
	*x = ProtectedFutureAsset{}
	mi := &file_velox_control_master_to_worker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtectedFutureAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtectedFutureAsset) ProtoMessage() {}

func (x *ProtectedFutureAsset) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_master_to_worker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtectedFutureAsset.ProtoReflect.Descriptor instead.
func (*ProtectedFutureAsset) Descriptor() ([]byte, []int) {
	return file_velox_control_master_to_worker_proto_rawDescGZIP(), []int{13}
}

func (x *ProtectedFutureAsset) GetAssetKey() string {
	if x != nil {
		return x.AssetKey
	}
	return ""
}

func (x *ProtectedFutureAsset) GetFutureRefCount() int32 {
	if x != nil {
		return x.FutureRefCount
	}
	return 0
}

func (x *ProtectedFutureAsset) GetNextUseDistance() int32 {
	if x != nil {
		return x.NextUseDistance
	}
	return 0
}

type CancelPrefetch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ReservationId string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	PlanVersion   uint64                 `protobuf:"varint,3,opt,name=plan_version,json=planVersion,proto3" json:"plan_version,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelPrefetch) Reset() {
	*x = CancelPrefetch{}
	mi := &file_velox_control_master_to_worker_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelPrefetch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPrefetch) ProtoMessage() {}

func (x *CancelPrefetch) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_master_to_worker_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPrefetch.ProtoReflect.Descriptor instead.
func (*CancelPrefetch) Descriptor() ([]byte, []int) {
	return file_velox_control_master_to_worker_proto_rawDescGZIP(), []int{14}
}

func (x *CancelPrefetch) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelPrefetch) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CancelPrefetch) GetPlanVersion() uint64 {
	if x != nil {
		return x.PlanVersion
	}
	return 0
}

func (x *CancelPrefetch) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_velox_control_master_to_worker_proto protoreflect.FileDescriptor

const file_velox_control_master_to_worker_proto_rawDesc = "" +
	"\n" +
	"$velox/control/master_to_worker.proto\x12\rvelox.control\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\"velox/control/control_common.proto\"\xaa\n" +
	"\n" +
	"\x16MasterToWorkerEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x03R\x0esequenceNumber\x123\n" +
	"\asent_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12)\n" +
	"\x10protocol_version\x18\x06 \x01(\tR\x0fprotocolVersion\x126\n" +
	"\thello_ack\x18\x14 \x01(\v2\x17.velox.control.HelloAckH\x00R\bhelloAck\x129\n" +
	"\n" +
	"task_offer\x18\x1e \x01(\v2\x18.velox.control.TaskOfferH\x00R\ttaskOffer\x12O\n" +
	"\x12task_lease_granted\x18\x1f \x01(\v2\x1f.velox.control.TaskLeaseGrantedH\x00R\x10taskLeaseGranted\x122\n" +
	"\acommand\x18\x18 \x01(\v2\x16.velox.control.CommandH\x00R\acommand\x129\n" +
	"\n" +
	"cancel_job\x18\x19 \x01(\v2\x18.velox.control.CancelJobH\x00R\tcancelJob\x12,\n" +
	"\x05drain\x18\x1a \x01(\v2\x14.velox.control.DrainH\x00R\x05drain\x12W\n" +
	"\x14configuration_update\x18\x1b \x01(\v2\".velox.control.ConfigurationUpdateH\x00R\x13configurationUpdate\x12B\n" +
	"\rlease_revoked\x18\x1c \x01(\v2\x1b.velox.control.LeaseRevokedH\x00R\fleaseRevoked\x12)\n" +
	"\x04ping\x18\x1d \x01(\v2\x13.velox.control.PingH\x00R\x04ping\x12e\n" +
	"\x1aartifact_early_upload_plan\x18' \x01(\v2&.velox.control.ArtifactEarlyUploadPlanH\x00R\x17artifactEarlyUploadPlan\x12U\n" +
	"\x14artifact_upload_plan\x18  \x01(\v2!.velox.control.ArtifactUploadPlanH\x00R\x12artifactUploadPlan\x12F\n" +
	"\x0ftask_commit_ack\x18! \x01(\v2\x1c.velox.control.TaskCommitAckH\x00R\rtaskCommitAck\x12F\n" +
	"\x0ftask_result_ack\x18# \x01(\v2\x1c.velox.control.TaskResultAckH\x00R\rtaskResultAck\x12L\n" +
	"\x11future_asset_plan\x18$ \x01(\v2\x1e.velox.control.FutureAssetPlanH\x00R\x0ffutureAssetPlan\x12H\n" +
	"\x0fcancel_prefetch\x18% \x01(\v2\x1d.velox.control.CancelPrefetchH\x00R\x0ecancelPrefetchB\x05\n" +
	"\x03msgJ\x04\b\x15\x10\x16J\x04\b\x16\x10\x17J\x04\b\x17\x10\x18J\x04\b\"\x10#\"\n" +
	"\n" +
	"\bHelloAck\"\x9f\x04\n" +
	"\tTaskOffer\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12\x1f\n" +
	"\vexecutor_id\x18\x04 \x01(\tR\n" +
	"executorId\x12)\n" +
	"\x10executor_version\x18\x05 \x01(\x05R\x0fexecutorVersion\x124\n" +
	"\ttask_spec\x18\x06 \x01(\v2\x17.google.protobuf.StructR\btaskSpec\x12\x19\n" +
	"\blease_id\x18\a \x01(\tR\aleaseId\x12A\n" +
	"\x0elease_deadline\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\rleaseDeadline\x12;\n" +
	"\frequirements\x18\t \x01(\v2\x17.google.protobuf.StructR\frequirements\x12@\n" +
	"\x0foutput_contract\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\x0eoutputContract\x12%\n" +
	"\x0eattempt_number\x18\v \x01(\x05R\rattemptNumber\x12\x1a\n" +
	"\brevision\x18\f \x01(\x05R\brevision\x12!\n" +
	"\fjob_revision\x18\r \x01(\x05R\vjobRevision\"\xe2\x01\n" +
	"\x10TaskLeaseGranted\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12\x15\n" +
	"\x06job_id\x18\x04 \x01(\tR\x05jobId\x12%\n" +
	"\x0eattempt_number\x18\x05 \x01(\x05R\rattemptNumber\x12\x1a\n" +
	"\brevision\x18\x06 \x01(\x05R\brevision\x12!\n" +
	"\fjob_revision\x18\a \x01(\x05R\vjobRevision\"\xad\x01\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12/\n" +
	"\x06params\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06params\"\"\n" +
	"\tCancelJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x1f\n" +
	"\x05Drain\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"T\n" +
	"\x13ConfigurationUpdate\x12=\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x17.google.protobuf.StructR\rconfiguration\"=\n" +
	"\fLeaseRevoked\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x06\n" +
	"\x04Ping\"\xec\x03\n" +
	"\x0fFutureAssetPlan\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\tR\x06planId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12=\n" +
	"\fgenerated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12$\n" +
	"\x0ecurrent_job_id\x18\x06 \x01(\tR\fcurrentJobId\x12?\n" +
	"\rprefetch_jobs\x18\a \x03(\v2\x1a.velox.control.PrefetchJobR\fprefetchJobs\x12J\n" +
	"\x0eprotect_assets\x18\b \x03(\v2#.velox.control.ProtectedFutureAssetR\rprotectAssets\x12)\n" +
	"\x10prefetch_horizon\x18\t \x01(\x05R\x0fprefetchHorizon\x121\n" +
	"\x14protection_lookahead\x18\n" +
	" \x01(\x05R\x13protectionLookahead\"\xdb\x01\n" +
	"\vPrefetchJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12%\n" +
	"\x0ereservation_id\x18\x03 \x01(\tR\rreservationId\x12#\n" +
	"\rtask_revision\x18\x04 \x01(\x05R\ftaskRevision\x12\x1a\n" +
	"\bdistance\x18\x05 \x01(\x05R\bdistance\x124\n" +
	"\x06assets\x18\x06 \x03(\v2\x1c.velox.control.PrefetchAssetR\x06assets\"\xaf\x01\n" +
	"\rPrefetchAsset\x12\x1b\n" +
	"\tasset_key\x18\x01 \x01(\tR\bassetKey\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\tR\aassetId\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\"\x89\x01\n" +
	"\x14ProtectedFutureAsset\x12\x1b\n" +
	"\tasset_key\x18\x01 \x01(\tR\bassetKey\x12(\n" +
	"\x10future_ref_count\x18\x02 \x01(\x05R\x0efutureRefCount\x12*\n" +
	"\x11next_use_distance\x18\x03 \x01(\x05R\x0fnextUseDistance\"\x89\x01\n" +
	"\x0eCancelPrefetch\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12!\n" +
	"\fplan_version\x18\x03 \x01(\x04R\vplanVersion\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reasonB\"Z velox-shared/controltransport/pbb\x06proto3"

var (
	file_velox_control_master_to_worker_proto_rawDescOnce sync.Once
	file_velox_control_master_to_worker_proto_rawDescData []byte
)

func file_velox_control_master_to_worker_proto_rawDescGZIP() []byte {
	file_velox_control_master_to_worker_proto_rawDescOnce.Do(func() {
		file_velox_control_master_to_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_velox_control_master_to_worker_proto_rawDesc), len(file_velox_control_master_to_worker_proto_rawDesc)))
	})
	return file_velox_control_master_to_worker_proto_rawDescData
}

var file_velox_control_master_to_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_velox_control_master_to_worker_proto_goTypes = []any{
	(*MasterToWorkerEnvelope)(nil),  // 0: velox.control.MasterToWorkerEnvelope
	(*HelloAck)(nil),                // 1: velox.control.HelloAck
	(*TaskOffer)(nil),               // 2: velox.control.TaskOffer
	(*TaskLeaseGranted)(nil),        // 3: velox.control.TaskLeaseGranted
	(*Command)(nil),                 // 4: velox.control.Command
	(*CancelJob)(nil),               // 5: velox.control.CancelJob
	(*Drain)(nil),                   // 6: velox.control.Drain
	(*ConfigurationUpdate)(nil),     // 7: velox.control.ConfigurationUpdate
	(*LeaseRevoked)(nil),            // 8: velox.control.LeaseRevoked
	(*Ping)(nil),                    // 9: velox.control.Ping
	(*FutureAssetPlan)(nil),         // 10: velox.control.FutureAssetPlan
	(*PrefetchJob)(nil),             // 11: velox.control.PrefetchJob
	(*PrefetchAsset)(nil),           // 12: velox.control.PrefetchAsset
	(*ProtectedFutureAsset)(nil),    // 13: velox.control.ProtectedFutureAsset
	(*CancelPrefetch)(nil),          // 14: velox.control.CancelPrefetch
	(*timestamppb.Timestamp)(nil),   // 15: google.protobuf.Timestamp
	(*ArtifactEarlyUploadPlan)(nil), // 16: velox.control.ArtifactEarlyUploadPlan
	(*ArtifactUploadPlan)(nil),      // 17: velox.control.ArtifactUploadPlan
	(*TaskCommitAck)(nil),           // 18: velox.control.TaskCommitAck
	(*TaskResultAck)(nil),           // 19: velox.control.TaskResultAck
	(*structpb.Struct)(nil),         // 20: google.protobuf.Struct
}
var file_velox_control_master_to_worker_proto_depIdxs = []int32{
	15, // 0: velox.control.MasterToWorkerEnvelope.sent_at:type_name -> google.protobuf.Timestamp
	1,  // 1: velox.control.MasterToWorkerEnvelope.hello_ack:type_name -> velox.control.HelloAck
	2,  // 2: velox.control.MasterToWorkerEnvelope.task_offer:type_name -> velox.control.TaskOffer
	3,  // 3: velox.control.MasterToWorkerEnvelope.task_lease_granted:type_name -> velox.control.TaskLeaseGranted
	4,  // 4: velox.control.MasterToWorkerEnvelope.command:type_name -> velox.control.Command
	5,  // 5: velox.control.MasterToWorkerEnvelope.cancel_job:type_name -> velox.control.CancelJob
	6,  // 6: velox.control.MasterToWorkerEnvelope.drain:type_name -> velox.control.Drain
	7,  // 7: velox.control.MasterToWorkerEnvelope.configuration_update:type_name -> velox.control.ConfigurationUpdate
	8,  // 8: velox.control.MasterToWorkerEnvelope.lease_revoked:type_name -> velox.control.LeaseRevoked
	9,  // 9: velox.control.MasterToWorkerEnvelope.ping:type_name -> velox.control.Ping
	16, // 10: velox.control.MasterToWorkerEnvelope.artifact_early_upload_plan:type_name -> velox.control.ArtifactEarlyUploadPlan
	17, // 11: velox.control.MasterToWorkerEnvelope.artifact_upload_plan:type_name -> velox.control.ArtifactUploadPlan
	18, // 12: velox.control.MasterToWorkerEnvelope.task_commit_ack:type_name -> velox.control.TaskCommitAck
	19, // 13: velox.control.MasterToWorkerEnvelope.task_result_ack:type_name -> velox.control.TaskResultAck
	10, // 14: velox.control.MasterToWorkerEnvelope.future_asset_plan:type_name -> velox.control.FutureAssetPlan
	14, // 15: velox.control.MasterToWorkerEnvelope.cancel_prefetch:type_name -> velox.control.CancelPrefetch
	20, // 16: velox.control.TaskOffer.task_spec:type_name -> google.protobuf.Struct
	15, // 17: velox.control.TaskOffer.lease_deadline:type_name -> google.protobuf.Timestamp
	20, // 18: velox.control.TaskOffer.requirements:type_name -> google.protobuf.Struct
	20, // 19: velox.control.TaskOffer.output_contract:type_name -> google.protobuf.Struct
	15, // 20: velox.control.Command.timestamp:type_name -> google.protobuf.Timestamp
	20, // 21: velox.control.Command.params:type_name -> google.protobuf.Struct
	20, // 22: velox.control.ConfigurationUpdate.configuration:type_name -> google.protobuf.Struct
	15, // 23: velox.control.FutureAssetPlan.generated_at:type_name -> google.protobuf.Timestamp
	15, // 24: velox.control.FutureAssetPlan.expires_at:type_name -> google.protobuf.Timestamp
	11, // 25: velox.control.FutureAssetPlan.prefetch_jobs:type_name -> velox.control.PrefetchJob
	13, // 26: velox.control.FutureAssetPlan.protect_assets:type_name -> velox.control.ProtectedFutureAsset
	12, // 27: velox.control.PrefetchJob.assets:type_name -> velox.control.PrefetchAsset
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_velox_control_master_to_worker_proto_init() }
func file_velox_control_master_to_worker_proto_init() {
	if File_velox_control_master_to_worker_proto != nil {
		return
	}
	file_velox_control_control_common_proto_init()
	file_velox_control_master_to_worker_proto_msgTypes[0].OneofWrappers = []any{
		(*MasterToWorkerEnvelope_HelloAck)(nil),
		(*MasterToWorkerEnvelope_TaskOffer)(nil),
		(*MasterToWorkerEnvelope_TaskLeaseGranted)(nil),
		(*MasterToWorkerEnvelope_Command)(nil),
		(*MasterToWorkerEnvelope_CancelJob)(nil),
		(*MasterToWorkerEnvelope_Drain)(nil),
		(*MasterToWorkerEnvelope_ConfigurationUpdate)(nil),
		(*MasterToWorkerEnvelope_LeaseRevoked)(nil),
		(*MasterToWorkerEnvelope_Ping)(nil),
		(*MasterToWorkerEnvelope_ArtifactEarlyUploadPlan)(nil),
		(*MasterToWorkerEnvelope_ArtifactUploadPlan)(nil),
		(*MasterToWorkerEnvelope_TaskCommitAck)(nil),
		(*MasterToWorkerEnvelope_TaskResultAck)(nil),
		(*MasterToWorkerEnvelope_FutureAssetPlan)(nil),
		(*MasterToWorkerEnvelope_CancelPrefetch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_velox_control_master_to_worker_proto_rawDesc), len(file_velox_control_master_to_worker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_velox_control_master_to_worker_proto_goTypes,
		DependencyIndexes: file_velox_control_master_to_worker_proto_depIdxs,
		MessageInfos:      file_velox_control_master_to_worker_proto_msgTypes,
	}.Build()
	File_velox_control_master_to_worker_proto = out.File
	file_velox_control_master_to_worker_proto_goTypes = nil
	file_velox_control_master_to_worker_proto_depIdxs = nil
}
