// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: velox/control/worker_to_master.proto

// Proto definition for Velox Worker-Control bidirectional stream.
// Both master (DataServer) and worker (worker-agent-go) use this contract
// for typed, versioned control-plane communication.
//
// Phase 2 (typed protobuf): message types are strongly typed with oneof
// instead of the legacy TransportMessage { string type; Struct payload; }.
// google.protobuf.Struct is retained only for genuinely dynamic fields
// (extra, job_payload, params, configuration) — TaskResult.metrics is now
// fully typed (TaskExecutionMetrics) per the scorecard-of-efficiency
// design (taskattempts.report.go + observability.service.go).
//
// ProtocolVersion bumped to "v3" — old v2 workers (TaskResult.metrics as
// google.protobuf.Struct) are no longer accepted at the gRPC handshake.
// The PR-5 cutover is forward-only: drain the fleet before deploy.
//
// Phase E cutover (May 2026): the MasterToWorkerEnvelope oneof no longer
// emits a forward-only JobAvailable notification. Wire-level field
// number 21 is reserved-but-unused to preserve field-number compatibility
// with previously-deployed workers/masters.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------------------------------------------------------
// Worker -> Master
// ---------------------------------------------------------
type WorkerToMasterEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	WorkerId        string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SequenceNumber  int64                  `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	SentAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WorkerToMasterEnvelope_Hello
	//	*WorkerToMasterEnvelope_Heartbeat
	//	*WorkerToMasterEnvelope_TaskAccepted
	//	*WorkerToMasterEnvelope_TaskRejected
	//	*WorkerToMasterEnvelope_TaskResult
	//	*WorkerToMasterEnvelope_TaskLeaseRenewal
	//	*WorkerToMasterEnvelope_CommandAck
	//	*WorkerToMasterEnvelope_ArtifactUploaded
	//	*WorkerToMasterEnvelope_Goodbye
	//	*WorkerToMasterEnvelope_TaskOutputDeclared
	//	*WorkerToMasterEnvelope_ArtifactUploadCompleted
	//	*WorkerToMasterEnvelope_AssetDownloadProgress
	//	*WorkerToMasterEnvelope_ArtifactUploadIntent
	//	*WorkerToMasterEnvelope_PrefetchLifecycleEvent
	Msg           isWorkerToMasterEnvelope_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerToMasterEnvelope) Reset() {
	*x = WorkerToMasterEnvelope{}
	mi := &file_velox_control_worker_to_master_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerToMasterEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerToMasterEnvelope) ProtoMessage() {}

func (x *WorkerToMasterEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_to_master_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerToMasterEnvelope.ProtoReflect.Descriptor instead.
func (*WorkerToMasterEnvelope) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_to_master_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerToMasterEnvelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *WorkerToMasterEnvelope) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerToMasterEnvelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WorkerToMasterEnvelope) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *WorkerToMasterEnvelope) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *WorkerToMasterEnvelope) GetMsg() isWorkerToMasterEnvelope_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetTaskAccepted() *TaskAccepted {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_TaskAccepted); ok {
			return x.TaskAccepted
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetTaskRejected() *TaskRejected {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_TaskRejected); ok {
			return x.TaskRejected
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetTaskLeaseRenewal() *TaskLeaseRenewal {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_TaskLeaseRenewal); ok {
			return x.TaskLeaseRenewal
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetCommandAck() *CommandAck {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_CommandAck); ok {
			return x.CommandAck
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetArtifactUploaded() *ArtifactUploaded {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_ArtifactUploaded); ok {
			return x.ArtifactUploaded
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetGoodbye() *Goodbye {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_Goodbye); ok {
			return x.Goodbye
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetTaskOutputDeclared() *TaskOutputDeclared {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_TaskOutputDeclared); ok {
			return x.TaskOutputDeclared
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetArtifactUploadCompleted() *ArtifactUploadCompleted {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_ArtifactUploadCompleted); ok {
			return x.ArtifactUploadCompleted
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetAssetDownloadProgress() *AssetDownloadProgress {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_AssetDownloadProgress); ok {
			return x.AssetDownloadProgress
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetArtifactUploadIntent() *ArtifactUploadIntent {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_ArtifactUploadIntent); ok {
			return x.ArtifactUploadIntent
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetPrefetchLifecycleEvent() *PrefetchLifecycleEvent {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_PrefetchLifecycleEvent); ok {
			return x.PrefetchLifecycleEvent
		}
	}
	return nil
}

type isWorkerToMasterEnvelope_Msg interface {
	isWorkerToMasterEnvelope_Msg()
}

type WorkerToMasterEnvelope_Hello struct {
	Hello *Hello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type WorkerToMasterEnvelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type WorkerToMasterEnvelope_TaskAccepted struct {
	// 12 (LeaseRenewal) — superseded by TaskLeaseRenewal (23). Reserved.
	// 13 (JobAccepted)  — superseded by TaskAccepted (20). Reserved.
	// 14 (JobRejected)  — superseded by TaskRejected (21). Reserved.
	// 15 (JobProgress)  — informational only; new workers use heartbeat extra.
	TaskAccepted *TaskAccepted `protobuf:"bytes,20,opt,name=task_accepted,json=taskAccepted,proto3,oneof"`
}

type WorkerToMasterEnvelope_TaskRejected struct {
	TaskRejected *TaskRejected `protobuf:"bytes,21,opt,name=task_rejected,json=taskRejected,proto3,oneof"`
}

type WorkerToMasterEnvelope_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,22,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type WorkerToMasterEnvelope_TaskLeaseRenewal struct {
	TaskLeaseRenewal *TaskLeaseRenewal `protobuf:"bytes,23,opt,name=task_lease_renewal,json=taskLeaseRenewal,proto3,oneof"`
}

type WorkerToMasterEnvelope_CommandAck struct {
	CommandAck *CommandAck `protobuf:"bytes,16,opt,name=command_ack,json=commandAck,proto3,oneof"`
}

type WorkerToMasterEnvelope_ArtifactUploaded struct {
	// 17 (JobResult) — job-keyed execution report; superseded by TaskResult.
	ArtifactUploaded *ArtifactUploaded `protobuf:"bytes,18,opt,name=artifact_uploaded,json=artifactUploaded,proto3,oneof"`
}

type WorkerToMasterEnvelope_Goodbye struct {
	Goodbye *Goodbye `protobuf:"bytes,19,opt,name=goodbye,proto3,oneof"`
}

type WorkerToMasterEnvelope_TaskOutputDeclared struct {
	// Phase 3.3 / 3.5 (Artifact Commit Protocol) — typed
	// declared-and-completed pipeline. The legacy ArtifactUploaded
	// message (18) remains in place for backward compatibility with
	// pre-v1-capability workers; the new TaskOutputDeclared /
	// ArtifactUploadCompleted pair is the typed, fencing-aware
	// successor and is the one referenced by CapabilityArtifactCommitV1.
	TaskOutputDeclared *TaskOutputDeclared `protobuf:"bytes,32,opt,name=task_output_declared,json=taskOutputDeclared,proto3,oneof"`
}

type WorkerToMasterEnvelope_ArtifactUploadCompleted struct {
	ArtifactUploadCompleted *ArtifactUploadCompleted `protobuf:"bytes,33,opt,name=artifact_upload_completed,json=artifactUploadCompleted,proto3,oneof"`
}

type WorkerToMasterEnvelope_AssetDownloadProgress struct {
	// Worker-side canonical asset download read-model checkpoint.
	// The physical transfer is shared across jobs; job_ids carries the
	// current per-job references so the master can project one transfer
	// into multiple job_asset_refs rows without duplicating the download.
	AssetDownloadProgress *AssetDownloadProgress `protobuf:"bytes,36,opt,name=asset_download_progress,json=assetDownloadProgress,proto3,oneof"`
}

type WorkerToMasterEnvelope_ArtifactUploadIntent struct {
	// Worker declaration that lets the master issue an early upload plan.
	ArtifactUploadIntent *ArtifactUploadIntent `protobuf:"bytes,37,opt,name=artifact_upload_intent,json=artifactUploadIntent,proto3,oneof"`
}

type WorkerToMasterEnvelope_PrefetchLifecycleEvent struct {
	// Worker-side prefetch lifecycle event. Emitted for future_plan_received,
	// future_plan_applied, and prefetch_prepared so the Master can persist
	// them into the job_events journal for fleetctl job inspect.
	PrefetchLifecycleEvent *PrefetchLifecycleEvent `protobuf:"bytes,38,opt,name=prefetch_lifecycle_event,json=prefetchLifecycleEvent,proto3,oneof"`
}

func (*WorkerToMasterEnvelope_Hello) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_Heartbeat) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_TaskAccepted) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_TaskRejected) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_TaskResult) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_TaskLeaseRenewal) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_CommandAck) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_ArtifactUploaded) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_Goodbye) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_TaskOutputDeclared) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_ArtifactUploadCompleted) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_AssetDownloadProgress) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_ArtifactUploadIntent) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_PrefetchLifecycleEvent) isWorkerToMasterEnvelope_Msg() {}

type Hello struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerName     string                 `protobuf:"bytes,1,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	Hostname       string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	BundleVersion  string                 `protobuf:"bytes,4,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`
	BundleHash     string                 `protobuf:"bytes,5,opt,name=bundle_hash,json=bundleHash,proto3" json:"bundle_hash,omitempty"`
	EngineVersion  string                 `protobuf:"bytes,6,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	CredentialHash string                 `protobuf:"bytes,7,opt,name=credential_hash,json=credentialHash,proto3" json:"credential_hash,omitempty"`
	// Capability string literals (constants, not enum, so old workers
	// can advertise older caps without rebuilding the proto).
	//
	//	"artifact.commit.v1"
	//	"task.output.declared.v1"
	//	"artifact.upload.plan.v1"
	//	"artifact.upload.completed.v1"
	//	"task.commit.ack.v1"
	//
	// The Struct field is intentionally opaque (json-shaped map) so
	// new capability strings ride in the wire without a regen. The
	// canonical Go-side constants live in
	// shared/controltransport/capabilities.go and are the wire surface
	// — see the design note in that file for the proto-vs-impl
	// divergence rationale.
	Capabilities  *structpb.Struct `protobuf:"bytes,8,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	WorkerClass   string           `protobuf:"bytes,9,opt,name=worker_class,json=workerClass,proto3" json:"worker_class,omitempty"`
	RolloutGroup  string           `protobuf:"bytes,10,opt,name=rollout_group,json=rolloutGroup,proto3" json:"rollout_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_velox_control_worker_to_master_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_to_master_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_to_master_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Hello) GetBundleVersion() string {
	if x != nil {
		return x.BundleVersion
	}
	return ""
}

func (x *Hello) GetBundleHash() string {
	if x != nil {
		return x.BundleHash
	}
	return ""
}

func (x *Hello) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *Hello) GetCredentialHash() string {
	if x != nil {
		return x.CredentialHash
	}
	return ""
}

func (x *Hello) GetCapabilities() *structpb.Struct {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Hello) GetWorkerClass() string {
	if x != nil {
		return x.WorkerClass
	}
	return ""
}

func (x *Hello) GetRolloutGroup() string {
	if x != nil {
		return x.RolloutGroup
	}
	return ""
}

// Heartbeat carries typed resource counters plus the typed FFmpeg
// counters and per-attempt metrics that the master aggregates for the
// Project Performance Scorecard. `extra` is retained ONLY for free-form
// worker logs; canonical metrics live on the typed sub-messages.
type Heartbeat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerName      string                 `protobuf:"bytes,1,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	WorkerStatus    string                 `protobuf:"bytes,2,opt,name=worker_status,json=workerStatus,proto3" json:"worker_status,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentJob      string                 `protobuf:"bytes,4,opt,name=current_job,json=currentJob,proto3" json:"current_job,omitempty"`
	CodeVersion     string                 `protobuf:"bytes,5,opt,name=code_version,json=codeVersion,proto3" json:"code_version,omitempty"`
	BundleVersion   string                 `protobuf:"bytes,6,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`
	BundleHash      string                 `protobuf:"bytes,7,opt,name=bundle_hash,json=bundleHash,proto3" json:"bundle_hash,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,8,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	EngineVersion   string                 `protobuf:"bytes,9,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	JobsCompleted   int64                  `protobuf:"varint,10,opt,name=jobs_completed,json=jobsCompleted,proto3" json:"jobs_completed,omitempty"`
	JobsFailed      int64                  `protobuf:"varint,11,opt,name=jobs_failed,json=jobsFailed,proto3" json:"jobs_failed,omitempty"`
	ActiveJobsCount int32                  `protobuf:"varint,12,opt,name=active_jobs_count,json=activeJobsCount,proto3" json:"active_jobs_count,omitempty"`
	Extra           *structpb.Struct       `protobuf:"bytes,13,opt,name=extra,proto3" json:"extra,omitempty"`
	// resources: typed counters (Linux /proc reads; sampled every 5s and
	// averaged over the heartbeat period). Empty on builds that don't ship
	// the resource sampler (macOS dev / unit tests); missing = "unknown"
	// on the master side, not a falsy zero.
	Resources     *WorkerResourceCounters `protobuf:"bytes,14,opt,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_velox_control_worker_to_master_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_to_master_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_to_master_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *Heartbeat) GetWorkerStatus() string {
	if x != nil {
		return x.WorkerStatus
	}
	return ""
}

func (x *Heartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Heartbeat) GetCurrentJob() string {
	if x != nil {
		return x.CurrentJob
	}
	return ""
}

func (x *Heartbeat) GetCodeVersion() string {
	if x != nil {
		return x.CodeVersion
	}
	return ""
}

func (x *Heartbeat) GetBundleVersion() string {
	if x != nil {
		return x.BundleVersion
	}
	return ""
}

func (x *Heartbeat) GetBundleHash() string {
	if x != nil {
		return x.BundleHash
	}
	return ""
}

func (x *Heartbeat) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Heartbeat) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *Heartbeat) GetJobsCompleted() int64 {
	if x != nil {
		return x.JobsCompleted
	}
	return 0
}

func (x *Heartbeat) GetJobsFailed() int64 {
	if x != nil {
		return x.JobsFailed
	}
	return 0
}

func (x *Heartbeat) GetActiveJobsCount() int32 {
	if x != nil {
		return x.ActiveJobsCount
	}
	return 0
}

func (x *Heartbeat) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *Heartbeat) GetResources() *WorkerResourceCounters {
	if x != nil {
		return x.Resources
	}
	return nil
}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_velox_control_worker_to_master_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_to_master_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_to_master_proto_rawDescGZIP(), []int{3}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// TaskResult is the task-native execution report.
//
// PR-5 (typed metrics, scorecard v1): metrics is now the typed
// TaskExecutionMetrics message. Legacy v2 clients sent a
// google.protobuf.Struct here; v3 master rejects v2 TaskResults at the
// typed-field check inside handler_jobs.go (an unmarshal of the
// structpb-shaped wire payload into TaskExecutionMetrics will produce
// a zero-value metrics — the master surfaces a WARN log and falls back
// to scalar counters only). See migration 054 for the canonical schema
// on `task_attempt_metrics`.
type SegmentTiming struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SegmentIndex     int32                  `protobuf:"varint,1,opt,name=segment_index,json=segmentIndex,proto3" json:"segment_index,omitempty"`
	SceneWorkerIndex int32                  `protobuf:"varint,2,opt,name=scene_worker_index,json=sceneWorkerIndex,proto3" json:"scene_worker_index,omitempty"`
	SourceType       string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	DurationMs       float64                `protobuf:"fixed64,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	AssetDownloadMs  float64                `protobuf:"fixed64,5,opt,name=asset_download_ms,json=assetDownloadMs,proto3" json:"asset_download_ms,omitempty"`
	FfmpegEncodeMs   float64                `protobuf:"fixed64,6,opt,name=ffmpeg_encode_ms,json=ffmpegEncodeMs,proto3" json:"ffmpeg_encode_ms,omitempty"`
	SourceBytes      int64                  `protobuf:"varint,7,opt,name=source_bytes,json=sourceBytes,proto3" json:"source_bytes,omitempty"`
	OutputBytes      int64                  `protobuf:"varint,8,opt,name=output_bytes,json=outputBytes,proto3" json:"output_bytes,omitempty"`
	FramesEncoded    int64                  `protobuf:"varint,9,opt,name=frames_encoded,json=framesEncoded,proto3" json:"frames_encoded,omitempty"`
	Codec            string                 `protobuf:"bytes,10,opt,name=codec,proto3" json:"codec,omitempty"`
	Preset           string                 `protobuf:"bytes,11,opt,name=preset,proto3" json:"preset,omitempty"`
	FfmpegThreads    int32                  `protobuf:"varint,12,opt,name=ffmpeg_threads,json=ffmpegThreads,proto3" json:"ffmpeg_threads,omitempty"`
	Status           string                 `protobuf:"bytes,13,opt,name=status,proto3" json:"status,omitempty"`
	ErrorCode        string                 `protobuf:"bytes,14,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,15,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SourceUrlHash    string                 `protobuf:"bytes,16,opt,name=source_url_hash,json=sourceUrlHash,proto3" json:"source_url_hash,omitempty"`
	CacheKey         string                 `protobuf:"bytes,17,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`
	MetadataJson     string                 `protobuf:"bytes,18,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	InputDurationMs  float64                `protobuf:"fixed64,19,opt,name=input_duration_ms,json=inputDurationMs,proto3" json:"input_duration_ms,omitempty"`
	OutputDurationMs float64                `protobuf:"fixed64,20,opt,name=output_duration_ms,json=outputDurationMs,proto3" json:"output_duration_ms,omitempty"`
	// Parallelism telemetry (migration 098).
	StartedOffsetMs  float64 `protobuf:"fixed64,21,opt,name=started_offset_ms,json=startedOffsetMs,proto3" json:"started_offset_ms,omitempty"`    // monotonic offset from attempt start to segment start
	FinishedOffsetMs float64 `protobuf:"fixed64,22,opt,name=finished_offset_ms,json=finishedOffsetMs,proto3" json:"finished_offset_ms,omitempty"` // monotonic offset from attempt start to segment end
	WorkerSlot       int32   `protobuf:"varint,23,opt,name=worker_slot,json=workerSlot,proto3" json:"worker_slot,omitempty"`                      // concurrency slot that executed this segment
	CpuThreads       int32   `protobuf:"varint,24,opt,name=cpu_threads,json=cpuThreads,proto3" json:"cpu_threads,omitempty"`                      // FFmpeg threads allocated to this segment
	ParallelGroup    string  `protobuf:"bytes,25,opt,name=parallel_group,json=parallelGroup,proto3" json:"parallel_group,omitempty"`              // logical grouping (e.g. "scene_0", "concat")
	SceneId          string  `protobuf:"bytes,26,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	FramesDecoded    int64   `protobuf:"varint,27,opt,name=frames_decoded,json=framesDecoded,proto3" json:"frames_decoded,omitempty"`
	FramesComposited int64   `protobuf:"varint,28,opt,name=frames_composited,json=framesComposited,proto3" json:"frames_composited,omitempty"`
	FfmpegSpeedX     float64 `protobuf:"fixed64,29,opt,name=ffmpeg_speed_x,json=ffmpegSpeedX,proto3" json:"ffmpeg_speed_x,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SegmentTiming) Reset() {
	*x = SegmentTiming{}
	mi := &file_velox_control_worker_to_master_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SegmentTiming) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegmentTiming) ProtoMessage() {}

func (x *SegmentTiming) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_to_master_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegmentTiming.ProtoReflect.Descriptor instead.
func (*SegmentTiming) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_to_master_proto_rawDescGZIP(), []int{4}
}

func (x *SegmentTiming) GetSegmentIndex() int32 {
	if x != nil {
		return x.SegmentIndex
	}
	return 0
}

func (x *SegmentTiming) GetSceneWorkerIndex() int32 {
	if x != nil {
		return x.SceneWorkerIndex
	}
	return 0
}

func (x *SegmentTiming) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *SegmentTiming) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *SegmentTiming) GetAssetDownloadMs() float64 {
	if x != nil {
		return x.AssetDownloadMs
	}
	return 0
}

func (x *SegmentTiming) GetFfmpegEncodeMs() float64 {
	if x != nil {
		return x.FfmpegEncodeMs
	}
	return 0
}

func (x *SegmentTiming) GetSourceBytes() int64 {
	if x != nil {
		return x.SourceBytes
	}
	return 0
}

func (x *SegmentTiming) GetOutputBytes() int64 {
	if x != nil {
		return x.OutputBytes
	}
	return 0
}

func (x *SegmentTiming) GetFramesEncoded() int64 {
	if x != nil {
		return x.FramesEncoded
	}
	return 0
}

func (x *SegmentTiming) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

func (x *SegmentTiming) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *SegmentTiming) GetFfmpegThreads() int32 {
	if x != nil {
		return x.FfmpegThreads
	}
	return 0
}

func (x *SegmentTiming) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SegmentTiming) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *SegmentTiming) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SegmentTiming) GetSourceUrlHash() string {
	if x != nil {
		return x.SourceUrlHash
	}
	return ""
}

func (x *SegmentTiming) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *SegmentTiming) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *SegmentTiming) GetInputDurationMs() float64 {
	if x != nil {
		return x.InputDurationMs
	}
	return 0
}

func (x *SegmentTiming) GetOutputDurationMs() float64 {
	if x != nil {
		return x.OutputDurationMs
	}
	return 0
}

func (x *SegmentTiming) GetStartedOffsetMs() float64 {
	if x != nil {
		return x.StartedOffsetMs
	}
	return 0
}

func (x *SegmentTiming) GetFinishedOffsetMs() float64 {
	if x != nil {
		return x.FinishedOffsetMs
	}
	return 0
}

func (x *SegmentTiming) GetWorkerSlot() int32 {
	if x != nil {
		return x.WorkerSlot
	}
	return 0
}

func (x *SegmentTiming) GetCpuThreads() int32 {
	if x != nil {
		return x.CpuThreads
	}
	return 0
}

func (x *SegmentTiming) GetParallelGroup() string {
	if x != nil {
		return x.ParallelGroup
	}
	return ""
}

func (x *SegmentTiming) GetSceneId() string {
	if x != nil {
		return x.SceneId
	}
	return ""
}

func (x *SegmentTiming) GetFramesDecoded() int64 {
	if x != nil {
		return x.FramesDecoded
	}
	return 0
}

func (x *SegmentTiming) GetFramesComposited() int64 {
	if x != nil {
		return x.FramesComposited
	}
	return 0
}

func (x *SegmentTiming) GetFfmpegSpeedX() float64 {
	if x != nil {
		return x.FfmpegSpeedX
	}
	return 0
}

type TaskResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId            string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AttemptId        string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "succeeded" or "failed"
	ErrorCode        string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorDetail      string                 `protobuf:"bytes,6,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	ExecutionMetrics *TaskExecutionMetrics  `protobuf:"bytes,7,opt,name=execution_metrics,json=executionMetrics,proto3" json:"execution_metrics,omitempty"`
	PhaseMarkers     []*PhaseMarker         `protobuf:"bytes,8,rep,name=phase_markers,json=phaseMarkers,proto3" json:"phase_markers,omitempty"`
	ExecutorId       string                 `protobuf:"bytes,9,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	ExecutorKey      string                 `protobuf:"bytes,10,opt,name=executor_key,json=executorKey,proto3" json:"executor_key,omitempty"`
	OutputArtifacts  []*structpb.Struct     `protobuf:"bytes,11,rep,name=output_artifacts,json=outputArtifacts,proto3" json:"output_artifacts,omitempty"`
	LeaseId          string                 `protobuf:"bytes,12,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	AttemptNumber    int32                  `protobuf:"varint,13,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	Revision         int32                  `protobuf:"varint,14,opt,name=revision,proto3" json:"revision,omitempty"`
	SegmentTimings   []*SegmentTiming       `protobuf:"bytes,15,rep,name=segment_timings,json=segmentTimings,proto3" json:"segment_timings,omitempty"`
	// PerformanceReport metadata: the worker emits exactly one report per
	// attempt and stamps it with schema/version and a SHA-256 hash over the
	// canonical raw report JSON. The master uses these fields for idempotency
	// and conflict detection in task_attempt_reports.
	ReportSchemaVersion int32  `protobuf:"varint,16,opt,name=report_schema_version,json=reportSchemaVersion,proto3" json:"report_schema_version,omitempty"`
	ReportVersion       int32  `protobuf:"varint,17,opt,name=report_version,json=reportVersion,proto3" json:"report_version,omitempty"`
	ReportHash          string `protobuf:"bytes,18,opt,name=report_hash,json=reportHash,proto3" json:"report_hash,omitempty"`
	// Partial phase metrics captured when an attempt fails before all phases
	// complete. Stored in task_phase_timings with status='PARTIAL' or
	// 'FAILED' so the master can diagnose which phase/component caused the
	// failure without losing the timings of the work already done.
	//
	// Observability chain / block 1: this field is LEGACY. New workers
	// populate `phase_timings` (20) with the FULL phase list on every
	// report (success AND failure) and mirror the failure subset here so
	// older masters that predate field 20 keep receiving partial-phase
	// data for failed attempts.
	PartialPhaseMetrics []*PhaseTimingDetailed `protobuf:"bytes,19,rep,name=partial_phase_metrics,json=partialPhaseMetrics,proto3" json:"partial_phase_metrics,omitempty"`
	// Observability chain / block 1: the FULL ordered phase list for the
	// attempt. The worker compiles this on every report (success and
	// failure) via the telemetry phase recorder. The master persists the
	// rows into task_phase_timings AND projects the event-carrying
	// entries into the append-only task_execution_events table. The
	// identity tuple (job/task/worker/session/snapshot/lease/executor)
	// on each entry is stamped by the MASTER from the canonical identity
	// tuple at ingest; worker-supplied identity fields are informational.
	PhaseTimings []*PhaseTimingDetailed `protobuf:"bytes,20,rep,name=phase_timings,json=phaseTimings,proto3" json:"phase_timings,omitempty"`
	// Version of the shared TelemetryEventCatalog used to produce the
	// detailed phase stream. Zero means a legacy worker that predates this
	// field; the master accepts it through the compatibility path.
	TelemetrySchemaVersion int32 `protobuf:"varint,21,opt,name=telemetry_schema_version,json=telemetrySchemaVersion,proto3" json:"telemetry_schema_version,omitempty"`
	// Non-overlapping worker lifecycle waterfall. Unlike phase_timings, these
	// segments are a partition of the worker-side attempt interval and are
	// intended for gap attribution rather than aggregate diagnostics.
	Waterfall []*AttemptWaterfallStage `protobuf:"bytes,22,rep,name=waterfall,proto3" json:"waterfall,omitempty"`
	// Monotonic milestone timeline (elapsed_ms from attempt start). Each
	// millisecond belongs to at most one waterfall bucket; this timeline is
	// the source for the bucket builder and the unaccounted gap calculation.
	Milestones []*AttemptMilestone `protobuf:"bytes,23,rep,name=milestones,proto3" json:"milestones,omitempty"`
	// STEP D drill-down INSIDE the asset_preparation waterfall bucket: the
	// per-attempt asset accounting plus sub-phase wall/work sums as measured
	// by the worker runtime. Sub-phases may overlap (parallel downloads), so
	// they are never re-combined into a coverage number master-side; an absent
	// message means the worker predates this field — no fabricated zeros.
	AssetPreparation *AssetPreparationBreakdown `protobuf:"bytes,24,opt,name=asset_preparation,json=assetPreparation,proto3" json:"asset_preparation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_velox_control_worker_to_master_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_to_master_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_to_master_proto_rawDescGZIP(), []int{5}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskResult) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TaskResult) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

func (x *TaskResult) GetExecutionMetrics() *TaskExecutionMetrics {
	if x != nil {
		return x.ExecutionMetrics
	}
	return nil
}

func (x *TaskResult) GetPhaseMarkers() []*PhaseMarker {
	if x != nil {
		return x.PhaseMarkers
	}
	return nil
}

func (x *TaskResult) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *TaskResult) GetExecutorKey() string {
	if x != nil {
		return x.ExecutorKey
	}
	return ""
}

func (x *TaskResult) GetOutputArtifacts() []*structpb.Struct {
	if x != nil {
		return x.OutputArtifacts
	}
	return nil
}

func (x *TaskResult) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *TaskResult) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *TaskResult) GetRevision() int32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *TaskResult) GetSegmentTimings() []*SegmentTiming {
	if x != nil {
		return x.SegmentTimings
	}
	return nil
}

func (x *TaskResult) GetReportSchemaVersion() int32 {
	if x != nil {
		return x.ReportSchemaVersion
	}
	return 0
}

func (x *TaskResult) GetReportVersion() int32 {
	if x != nil {
		return x.ReportVersion
	}
	return 0
}

func (x *TaskResult) GetReportHash() string {
	if x != nil {
		return x.ReportHash
	}
	return ""
}

func (x *TaskResult) GetPartialPhaseMetrics() []*PhaseTimingDetailed {
	if x != nil {
		return x.PartialPhaseMetrics
	}
	return nil
}

func (x *TaskResult) GetPhaseTimings() []*PhaseTimingDetailed {
	if x != nil {
		return x.PhaseTimings
	}
	return nil
}

func (x *TaskResult) GetTelemetrySchemaVersion() int32 {
	if x != nil {
		return x.TelemetrySchemaVersion
	}
	return 0
}

func (x *TaskResult) GetWaterfall() []*AttemptWaterfallStage {
	if x != nil {
		return x.Waterfall
	}
	return nil
}

func (x *TaskResult) GetMilestones() []*AttemptMilestone {
	if x != nil {
		return x.Milestones
	}
	return nil
}

func (x *TaskResult) GetAssetPreparation() *AssetPreparationBreakdown {
	if x != nil {
		return x.AssetPreparation
	}
	return nil
}

type AssetPreparationBreakdown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per-attempt asset accounting.
	AssetsRequired int64 `protobuf:"varint,1,opt,name=assets_required,json=assetsRequired,proto3" json:"assets_required,omitempty"`
	AssetsUnique   int64 `protobuf:"varint,2,opt,name=assets_unique,json=assetsUnique,proto3" json:"assets_unique,omitempty"`
	CacheHits      int64 `protobuf:"varint,3,opt,name=cache_hits,json=cacheHits,proto3" json:"cache_hits,omitempty"`
	CacheMisses    int64 `protobuf:"varint,4,opt,name=cache_misses,json=cacheMisses,proto3" json:"cache_misses,omitempty"`
	// Served from a verified local file without moving bytes / bytes moved now.
	ReadyBeforeAttempt      int64 `protobuf:"varint,5,opt,name=ready_before_attempt,json=readyBeforeAttempt,proto3" json:"ready_before_attempt,omitempty"`
	DownloadedDuringAttempt int64 `protobuf:"varint,6,opt,name=downloaded_during_attempt,json=downloadedDuringAttempt,proto3" json:"downloaded_during_attempt,omitempty"`
	// Sub-phase durations, summed across per-asset resolutions. Wall vs work:
	// download_wall_ms is Σ per-transfer windows, download_work_ms is Σ
	// byte-moving time; with parallel downloads work_sum < wall_sum is normal.
	CacheLookupMs      int64 `protobuf:"varint,7,opt,name=cache_lookup_ms,json=cacheLookupMs,proto3" json:"cache_lookup_ms,omitempty"`
	RemoteWaitMs       int64 `protobuf:"varint,8,opt,name=remote_wait_ms,json=remoteWaitMs,proto3" json:"remote_wait_ms,omitempty"`
	RemoteWaitCount    int64 `protobuf:"varint,9,opt,name=remote_wait_count,json=remoteWaitCount,proto3" json:"remote_wait_count,omitempty"`
	DownloadWallMs     int64 `protobuf:"varint,10,opt,name=download_wall_ms,json=downloadWallMs,proto3" json:"download_wall_ms,omitempty"`
	DownloadWorkMs     int64 `protobuf:"varint,11,opt,name=download_work_ms,json=downloadWorkMs,proto3" json:"download_work_ms,omitempty"`
	HashVerifyMs       int64 `protobuf:"varint,12,opt,name=hash_verify_ms,json=hashVerifyMs,proto3" json:"hash_verify_ms,omitempty"`
	MetadataProbeMs    int64 `protobuf:"varint,13,opt,name=metadata_probe_ms,json=metadataProbeMs,proto3" json:"metadata_probe_ms,omitempty"`
	MaterializeLocalMs int64 `protobuf:"varint,14,opt,name=materialize_local_ms,json=materializeLocalMs,proto3" json:"materialize_local_ms,omitempty"`
	// Byte-level attribution: derived from the single cacheResolutionSink.
	// cache_hit_bytes counts bytes served from verified local cache;
	// cache_miss_bytes counts bytes downloaded from remote; prefetch_hit_bytes
	// is the subset of cache_hit_bytes where origin == prefetch.
	CacheHitBytes    int64 `protobuf:"varint,15,opt,name=cache_hit_bytes,json=cacheHitBytes,proto3" json:"cache_hit_bytes,omitempty"`
	CacheMissBytes   int64 `protobuf:"varint,16,opt,name=cache_miss_bytes,json=cacheMissBytes,proto3" json:"cache_miss_bytes,omitempty"`
	PrefetchHitBytes int64 `protobuf:"varint,17,opt,name=prefetch_hit_bytes,json=prefetchHitBytes,proto3" json:"prefetch_hit_bytes,omitempty"`
	// Origin counters: exactly one of {prefetch_hits, warm_cache_hits,
	// runtime_downloads} is incremented per resolution.
	PrefetchHits     int64 `protobuf:"varint,18,opt,name=prefetch_hits,json=prefetchHits,proto3" json:"prefetch_hits,omitempty"`
	WarmCacheHits    int64 `protobuf:"varint,19,opt,name=warm_cache_hits,json=warmCacheHits,proto3" json:"warm_cache_hits,omitempty"`
	RuntimeDownloads int64 `protobuf:"varint,20,opt,name=runtime_downloads,json=runtimeDownloads,proto3" json:"runtime_downloads,omitempty"`
	// Byte-level origin attribution.
	WarmCacheBytes       int64 `protobuf:"varint,21,opt,name=warm_cache_bytes,json=warmCacheBytes,proto3" json:"warm_cache_bytes,omitempty"`
	RuntimeDownloadBytes int64 `protobuf:"varint,22,opt,name=runtime_download_bytes,json=runtimeDownloadBytes,proto3" json:"runtime_download_bytes,omitempty"`
	// Total SizeBytes across all required asset resolutions.
	RequiredAssetBytes int64 `protobuf:"varint,23,opt,name=required_asset_bytes,json=requiredAssetBytes,proto3" json:"required_asset_bytes,omitempty"`
	// Epoch ms of the most recent prefetch preparation.
	LatestPreparedAtMs int64 `protobuf:"varint,24,opt,name=latest_prepared_at_ms,json=latestPreparedAtMs,proto3" json:"latest_prepared_at_ms,omitempty"`
	// Epoch ms when the attempt started.
	AttemptStartedAtMs int64 `protobuf:"varint,25,opt,name=attempt_started_at_ms,json=attemptStartedAtMs,proto3" json:"attempt_started_at_ms,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AssetPreparationBreakdown) Reset() {
	*x = AssetPreparationBreakdown{}
	mi := &file_velox_control_worker_to_master_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetPreparationBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetPreparationBreakdown) ProtoMessage() {}

func (x *AssetPreparationBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_to_master_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetPreparationBreakdown.ProtoReflect.Descriptor instead.
func (*AssetPreparationBreakdown) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_to_master_proto_rawDescGZIP(), []int{6}
}

func (x *AssetPreparationBreakdown) GetAssetsRequired() int64 {
	if x != nil {
		return x.AssetsRequired
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetAssetsUnique() int64 {
	if x != nil {
		return x.AssetsUnique
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetCacheHits() int64 {
	if x != nil {
		return x.CacheHits
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetCacheMisses() int64 {
	if x != nil {
		return x.CacheMisses
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetReadyBeforeAttempt() int64 {
	if x != nil {
		return x.ReadyBeforeAttempt
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetDownloadedDuringAttempt() int64 {
	if x != nil {
		return x.DownloadedDuringAttempt
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetCacheLookupMs() int64 {
	if x != nil {
		return x.CacheLookupMs
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetRemoteWaitMs() int64 {
	if x != nil {
		return x.RemoteWaitMs
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetRemoteWaitCount() int64 {
	if x != nil {
		return x.RemoteWaitCount
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetDownloadWallMs() int64 {
	if x != nil {
		return x.DownloadWallMs
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetDownloadWorkMs() int64 {
	if x != nil {
		return x.DownloadWorkMs
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetHashVerifyMs() int64 {
	if x != nil {
		return x.HashVerifyMs
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetMetadataProbeMs() int64 {
	if x != nil {
		return x.MetadataProbeMs
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetMaterializeLocalMs() int64 {
	if x != nil {
		return x.MaterializeLocalMs
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetCacheHitBytes() int64 {
	if x != nil {
		return x.CacheHitBytes
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetCacheMissBytes() int64 {
	if x != nil {
		return x.CacheMissBytes
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetPrefetchHitBytes() int64 {
	if x != nil {
		return x.PrefetchHitBytes
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetPrefetchHits() int64 {
	if x != nil {
		return x.PrefetchHits
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetWarmCacheHits() int64 {
	if x != nil {
		return x.WarmCacheHits
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetRuntimeDownloads() int64 {
	if x != nil {
		return x.RuntimeDownloads
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetWarmCacheBytes() int64 {
	if x != nil {
		return x.WarmCacheBytes
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetRuntimeDownloadBytes() int64 {
	if x != nil {
		return x.RuntimeDownloadBytes
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetRequiredAssetBytes() int64 {
	if x != nil {
		return x.RequiredAssetBytes
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetLatestPreparedAtMs() int64 {
	if x != nil {
		return x.LatestPreparedAtMs
	}
	return 0
}

func (x *AssetPreparationBreakdown) GetAttemptStartedAtMs() int64 {
	if x != nil {
		return x.AttemptStartedAtMs
	}
	return 0
}

type AttemptWaterfallStage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttemptWaterfallStage) Reset() {
	*x = AttemptWaterfallStage{}
	mi := &file_velox_control_worker_to_master_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttemptWaterfallStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttemptWaterfallStage) ProtoMessage() {}

func (x *AttemptWaterfallStage) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_to_master_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttemptWaterfallStage.ProtoReflect.Descriptor instead.
func (*AttemptWaterfallStage) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_to_master_proto_rawDescGZIP(), []int{7}
}

func (x *AttemptWaterfallStage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttemptWaterfallStage) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *AttemptWaterfallStage) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *AttemptWaterfallStage) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *AttemptWaterfallStage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AttemptMilestone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	ElapsedMs     int64                  `protobuf:"varint,3,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	OccurredAt    string                 `protobuf:"bytes,4,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttemptMilestone) Reset() {
	*x = AttemptMilestone{}
	mi := &file_velox_control_worker_to_master_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttemptMilestone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttemptMilestone) ProtoMessage() {}

func (x *AttemptMilestone) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_to_master_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttemptMilestone.ProtoReflect.Descriptor instead.
func (*AttemptMilestone) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_to_master_proto_rawDescGZIP(), []int{8}
}

func (x *AttemptMilestone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttemptMilestone) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AttemptMilestone) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *AttemptMilestone) GetOccurredAt() string {
	if x != nil {
		return x.OccurredAt
	}
	return ""
}

type TaskLeaseRenewal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AttemptId       string                 `protobuf:"bytes,2,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	LeaseId         string                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	RequestedExpiry *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=requested_expiry,json=requestedExpiry,proto3" json:"requested_expiry,omitempty"`
	JobId           string                 `protobuf:"bytes,5,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AttemptNumber   int32                  `protobuf:"varint,6,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	Revision        int32                  `protobuf:"varint,7,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskLeaseRenewal) Reset() {
	*x = TaskLeaseRenewal{}
	mi := &file_velox_control_worker_to_master_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLeaseRenewal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLeaseRenewal) ProtoMessage() {}

func (x *TaskLeaseRenewal) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_to_master_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLeaseRenewal.ProtoReflect.Descriptor instead.
func (*TaskLeaseRenewal) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_to_master_proto_rawDescGZIP(), []int{9}
}

func (x *TaskLeaseRenewal) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskLeaseRenewal) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskLeaseRenewal) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *TaskLeaseRenewal) GetRequestedExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedExpiry
	}
	return nil
}

func (x *TaskLeaseRenewal) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskLeaseRenewal) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *TaskLeaseRenewal) GetRevision() int32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

// PhaseMarker records one canonical phase timing.
//
// Canonical names (load-bearing for observability.aggregate scoring):
//
//	queue, asset_wait, cache_lookup, download, decode, compile,
//	simulate, render, composite, encode, upload, finalize.
//
// Workers MUST emit only these names; free-form identifiers are
// rejected by the master's IsCanonicalPhase() guard rail at ingest.
type PhaseMarker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseMarker) Reset() {
	*x = PhaseMarker{}
	mi := &file_velox_control_worker_to_master_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseMarker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseMarker) ProtoMessage() {}

func (x *PhaseMarker) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_to_master_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseMarker.ProtoReflect.Descriptor instead.
func (*PhaseMarker) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_to_master_proto_rawDescGZIP(), []int{10}
}

func (x *PhaseMarker) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PhaseMarker) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *PhaseMarker) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *PhaseMarker) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PhaseMarker) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

// PhaseTimingDetailed is the rich, per-phase record emitted when an
// attempt terminates before all phases complete. It carries enough
// context (component, action, byte/frame counters, error code) to
// diagnose failures while reusing the same task_phase_timings storage
// as successful attempts.
//
// Observability chain / block 1: PhaseTimingDetailed is ALSO the unit
// of the append-only task_execution_events timeline. Fields 14-24 add
// the event taxonomy (origin, scope, event_type, event_name,
// event_index) plus an echo of the executor/lease/worker identity.
// Fields 25-34 carry repeated-event context, resource timing and an
// optional artifact identity. The master stamps canonical identity
// values at ingest; worker-supplied identity echoes are informational
// and overridden from the canonical attempt tuple.
type PhaseTimingDetailed struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PhaseOrder   int32                  `protobuf:"varint,1,opt,name=phase_order,json=phaseOrder,proto3" json:"phase_order,omitempty"`
	Component    string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	Action       string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	StartedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	DurationMs   int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Status       string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ErrorCode    string                 `protobuf:"bytes,8,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	BytesIn      int64                  `protobuf:"varint,10,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut     int64                  `protobuf:"varint,11,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	Frames       int64                  `protobuf:"varint,12,opt,name=frames,proto3" json:"frames,omitempty"`
	MetadataJson string                 `protobuf:"bytes,13,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	// ── Observability chain / block 1: event taxonomy ────────────────
	// Closed enums (constants, not enum types, so older workers can send
	// unknown origins/scopes without a wire break):
	//
	//	origin: master | worker | engine | ffmpeg | upload | validation
	//	scope:  job | task | attempt | segment | audio_track |
	//	        subtitle_track | artifact
	Origin string `protobuf:"bytes,14,opt,name=origin,proto3" json:"origin,omitempty"`
	Scope  string `protobuf:"bytes,15,opt,name=scope,proto3" json:"scope,omitempty"`
	// event_type: "started" | "completed" | "failed" | "progress" | ...
	// event_name: free-form short label (e.g. "encode_segment_4").
	EventType string `protobuf:"bytes,16,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventName string `protobuf:"bytes,17,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	// Monotonic per-(attempt, origin) sequence number. Combined with the
	// master's UNIQUE(attempt_id, origin, event_index) index it makes
	// report replays idempotent.
	EventIndex int64 `protobuf:"varint,18,opt,name=event_index,json=eventIndex,proto3" json:"event_index,omitempty"`
	// Canonical phase name (queue, asset_wait, cache_lookup, download,
	// decode, compile, simulate, render, composite, encode, upload,
	// finalize) when this event belongs to one.
	Phase string `protobuf:"bytes,19,opt,name=phase,proto3" json:"phase,omitempty"`
	// ── Identity echo (informational; master overrides at ingest) ────
	ExecutorId       string `protobuf:"bytes,20,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	ExecutorVersion  int32  `protobuf:"varint,21,opt,name=executor_version,json=executorVersion,proto3" json:"executor_version,omitempty"`
	LeaseId          string `protobuf:"bytes,22,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	WorkerSnapshotId string `protobuf:"bytes,23,opt,name=worker_snapshot_id,json=workerSnapshotId,proto3" json:"worker_snapshot_id,omitempty"`
	WorkerSessionId  string `protobuf:"bytes,24,opt,name=worker_session_id,json=workerSessionId,proto3" json:"worker_session_id,omitempty"`
	// Repeated-event context and resource timing. These fields are appended
	// so fields 1-24 remain wire-compatible with existing workers/masters.
	SegmentIndex     int32   `protobuf:"varint,25,opt,name=segment_index,json=segmentIndex,proto3" json:"segment_index,omitempty"`
	TrackKind        string  `protobuf:"bytes,26,opt,name=track_kind,json=trackKind,proto3" json:"track_kind,omitempty"`
	TrackIndex       int32   `protobuf:"varint,27,opt,name=track_index,json=trackIndex,proto3" json:"track_index,omitempty"`
	StartedOffsetMs  float64 `protobuf:"fixed64,28,opt,name=started_offset_ms,json=startedOffsetMs,proto3" json:"started_offset_ms,omitempty"`
	FinishedOffsetMs float64 `protobuf:"fixed64,29,opt,name=finished_offset_ms,json=finishedOffsetMs,proto3" json:"finished_offset_ms,omitempty"`
	CpuMs            float64 `protobuf:"fixed64,30,opt,name=cpu_ms,json=cpuMs,proto3" json:"cpu_ms,omitempty"`
	QueueWaitMs      float64 `protobuf:"fixed64,31,opt,name=queue_wait_ms,json=queueWaitMs,proto3" json:"queue_wait_ms,omitempty"`
	FramesIn         int64   `protobuf:"varint,32,opt,name=frames_in,json=framesIn,proto3" json:"frames_in,omitempty"`
	FramesOut        int64   `protobuf:"varint,33,opt,name=frames_out,json=framesOut,proto3" json:"frames_out,omitempty"`
	// Optional artifact identity for artifact-scoped events. The master
	// still overrides identity fields from canonical database rows.
	ArtifactId string `protobuf:"bytes,34,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	// Version of the shared TelemetryEventCatalog for this event.
	TelemetrySchemaVersion int32 `protobuf:"varint,35,opt,name=telemetry_schema_version,json=telemetrySchemaVersion,proto3" json:"telemetry_schema_version,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PhaseTimingDetailed) Reset() {
	*x = PhaseTimingDetailed{}
	mi := &file_velox_control_worker_to_master_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseTimingDetailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseTimingDetailed) ProtoMessage() {}

func (x *PhaseTimingDetailed) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_to_master_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseTimingDetailed.ProtoReflect.Descriptor instead.
func (*PhaseTimingDetailed) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_to_master_proto_rawDescGZIP(), []int{11}
}

func (x *PhaseTimingDetailed) GetPhaseOrder() int32 {
	if x != nil {
		return x.PhaseOrder
	}
	return 0
}

func (x *PhaseTimingDetailed) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *PhaseTimingDetailed) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PhaseTimingDetailed) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *PhaseTimingDetailed) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *PhaseTimingDetailed) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *PhaseTimingDetailed) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PhaseTimingDetailed) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *PhaseTimingDetailed) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PhaseTimingDetailed) GetBytesIn() int64 {
	if x != nil {
		return x.BytesIn
	}
	return 0
}

func (x *PhaseTimingDetailed) GetBytesOut() int64 {
	if x != nil {
		return x.BytesOut
	}
	return 0
}

func (x *PhaseTimingDetailed) GetFrames() int64 {
	if x != nil {
		return x.Frames
	}
	return 0
}

func (x *PhaseTimingDetailed) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *PhaseTimingDetailed) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *PhaseTimingDetailed) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *PhaseTimingDetailed) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PhaseTimingDetailed) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *PhaseTimingDetailed) GetEventIndex() int64 {
	if x != nil {
		return x.EventIndex
	}
	return 0
}

func (x *PhaseTimingDetailed) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PhaseTimingDetailed) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *PhaseTimingDetailed) GetExecutorVersion() int32 {
	if x != nil {
		return x.ExecutorVersion
	}
	return 0
}

func (x *PhaseTimingDetailed) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *PhaseTimingDetailed) GetWorkerSnapshotId() string {
	if x != nil {
		return x.WorkerSnapshotId
	}
	return ""
}

func (x *PhaseTimingDetailed) GetWorkerSessionId() string {
	if x != nil {
		return x.WorkerSessionId
	}
	return ""
}

func (x *PhaseTimingDetailed) GetSegmentIndex() int32 {
	if x != nil {
		return x.SegmentIndex
	}
	return 0
}

func (x *PhaseTimingDetailed) GetTrackKind() string {
	if x != nil {
		return x.TrackKind
	}
	return ""
}

func (x *PhaseTimingDetailed) GetTrackIndex() int32 {
	if x != nil {
		return x.TrackIndex
	}
	return 0
}

func (x *PhaseTimingDetailed) GetStartedOffsetMs() float64 {
	if x != nil {
		return x.StartedOffsetMs
	}
	return 0
}

func (x *PhaseTimingDetailed) GetFinishedOffsetMs() float64 {
	if x != nil {
		return x.FinishedOffsetMs
	}
	return 0
}

func (x *PhaseTimingDetailed) GetCpuMs() float64 {
	if x != nil {
		return x.CpuMs
	}
	return 0
}

func (x *PhaseTimingDetailed) GetQueueWaitMs() float64 {
	if x != nil {
		return x.QueueWaitMs
	}
	return 0
}

func (x *PhaseTimingDetailed) GetFramesIn() int64 {
	if x != nil {
		return x.FramesIn
	}
	return 0
}

func (x *PhaseTimingDetailed) GetFramesOut() int64 {
	if x != nil {
		return x.FramesOut
	}
	return 0
}

func (x *PhaseTimingDetailed) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *PhaseTimingDetailed) GetTelemetrySchemaVersion() int32 {
	if x != nil {
		return x.TelemetrySchemaVersion
	}
	return 0
}

var File_velox_control_worker_to_master_proto protoreflect.FileDescriptor

const file_velox_control_worker_to_master_proto_rawDesc = "" +
	"\n" +
	"$velox/control/worker_to_master.proto\x12\rvelox.control\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\"velox/control/control_common.proto\x1a!velox/control/worker_events.proto\"\xcb\n" +
	"\n" +
	"\x16WorkerToMasterEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x03R\x0esequenceNumber\x123\n" +
	"\asent_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12)\n" +
	"\x10protocol_version\x18\x06 \x01(\tR\x0fprotocolVersion\x12,\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x14.velox.control.HelloH\x00R\x05hello\x128\n" +
	"\theartbeat\x18\v \x01(\v2\x18.velox.control.HeartbeatH\x00R\theartbeat\x12B\n" +
	"\rtask_accepted\x18\x14 \x01(\v2\x1b.velox.control.TaskAcceptedH\x00R\ftaskAccepted\x12B\n" +
	"\rtask_rejected\x18\x15 \x01(\v2\x1b.velox.control.TaskRejectedH\x00R\ftaskRejected\x12<\n" +
	"\vtask_result\x18\x16 \x01(\v2\x19.velox.control.TaskResultH\x00R\n" +
	"taskResult\x12O\n" +
	"\x12task_lease_renewal\x18\x17 \x01(\v2\x1f.velox.control.TaskLeaseRenewalH\x00R\x10taskLeaseRenewal\x12<\n" +
	"\vcommand_ack\x18\x10 \x01(\v2\x19.velox.control.CommandAckH\x00R\n" +
	"commandAck\x12N\n" +
	"\x11artifact_uploaded\x18\x12 \x01(\v2\x1f.velox.control.ArtifactUploadedH\x00R\x10artifactUploaded\x122\n" +
	"\agoodbye\x18\x13 \x01(\v2\x16.velox.control.GoodbyeH\x00R\agoodbye\x12U\n" +
	"\x14task_output_declared\x18  \x01(\v2!.velox.control.TaskOutputDeclaredH\x00R\x12taskOutputDeclared\x12d\n" +
	"\x19artifact_upload_completed\x18! \x01(\v2&.velox.control.ArtifactUploadCompletedH\x00R\x17artifactUploadCompleted\x12^\n" +
	"\x17asset_download_progress\x18$ \x01(\v2$.velox.control.AssetDownloadProgressH\x00R\x15assetDownloadProgress\x12[\n" +
	"\x16artifact_upload_intent\x18% \x01(\v2#.velox.control.ArtifactUploadIntentH\x00R\x14artifactUploadIntent\x12a\n" +
	"\x18prefetch_lifecycle_event\x18& \x01(\v2%.velox.control.PrefetchLifecycleEventH\x00R\x16prefetchLifecycleEventB\x05\n" +
	"\x03msgJ\x04\b\f\x10\rJ\x04\b\r\x10\x0eJ\x04\b\x0e\x10\x0fJ\x04\b\x0f\x10\x10J\x04\b\x11\x10\x12J\x04\b\"\x10#J\x04\b#\x10$\"\xfb\x02\n" +
	"\x05Hello\x12\x1f\n" +
	"\vworker_name\x18\x01 \x01(\tR\n" +
	"workerName\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0ebundle_version\x18\x04 \x01(\tR\rbundleVersion\x12\x1f\n" +
	"\vbundle_hash\x18\x05 \x01(\tR\n" +
	"bundleHash\x12%\n" +
	"\x0eengine_version\x18\x06 \x01(\tR\rengineVersion\x12'\n" +
	"\x0fcredential_hash\x18\a \x01(\tR\x0ecredentialHash\x12;\n" +
	"\fcapabilities\x18\b \x01(\v2\x17.google.protobuf.StructR\fcapabilities\x12!\n" +
	"\fworker_class\x18\t \x01(\tR\vworkerClass\x12#\n" +
	"\rrollout_group\x18\n" +
	" \x01(\tR\frolloutGroup\"\xaf\x04\n" +
	"\tHeartbeat\x12\x1f\n" +
	"\vworker_name\x18\x01 \x01(\tR\n" +
	"workerName\x12#\n" +
	"\rworker_status\x18\x02 \x01(\tR\fworkerStatus\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vcurrent_job\x18\x04 \x01(\tR\n" +
	"currentJob\x12!\n" +
	"\fcode_version\x18\x05 \x01(\tR\vcodeVersion\x12%\n" +
	"\x0ebundle_version\x18\x06 \x01(\tR\rbundleVersion\x12\x1f\n" +
	"\vbundle_hash\x18\a \x01(\tR\n" +
	"bundleHash\x12)\n" +
	"\x10protocol_version\x18\b \x01(\tR\x0fprotocolVersion\x12%\n" +
	"\x0eengine_version\x18\t \x01(\tR\rengineVersion\x12%\n" +
	"\x0ejobs_completed\x18\n" +
	" \x01(\x03R\rjobsCompleted\x12\x1f\n" +
	"\vjobs_failed\x18\v \x01(\x03R\n" +
	"jobsFailed\x12*\n" +
	"\x11active_jobs_count\x18\f \x01(\x05R\x0factiveJobsCount\x12-\n" +
	"\x05extra\x18\r \x01(\v2\x17.google.protobuf.StructR\x05extra\x12C\n" +
	"\tresources\x18\x0e \x01(\v2%.velox.control.WorkerResourceCountersR\tresources\"[\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xb4\b\n" +
	"\rSegmentTiming\x12#\n" +
	"\rsegment_index\x18\x01 \x01(\x05R\fsegmentIndex\x12,\n" +
	"\x12scene_worker_index\x18\x02 \x01(\x05R\x10sceneWorkerIndex\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x01R\n" +
	"durationMs\x12*\n" +
	"\x11asset_download_ms\x18\x05 \x01(\x01R\x0fassetDownloadMs\x12(\n" +
	"\x10ffmpeg_encode_ms\x18\x06 \x01(\x01R\x0effmpegEncodeMs\x12!\n" +
	"\fsource_bytes\x18\a \x01(\x03R\vsourceBytes\x12!\n" +
	"\foutput_bytes\x18\b \x01(\x03R\voutputBytes\x12%\n" +
	"\x0eframes_encoded\x18\t \x01(\x03R\rframesEncoded\x12\x14\n" +
	"\x05codec\x18\n" +
	" \x01(\tR\x05codec\x12\x16\n" +
	"\x06preset\x18\v \x01(\tR\x06preset\x12%\n" +
	"\x0effmpeg_threads\x18\f \x01(\x05R\rffmpegThreads\x12\x16\n" +
	"\x06status\x18\r \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x0e \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x0f \x01(\tR\ferrorMessage\x12&\n" +
	"\x0fsource_url_hash\x18\x10 \x01(\tR\rsourceUrlHash\x12\x1b\n" +
	"\tcache_key\x18\x11 \x01(\tR\bcacheKey\x12#\n" +
	"\rmetadata_json\x18\x12 \x01(\tR\fmetadataJson\x12*\n" +
	"\x11input_duration_ms\x18\x13 \x01(\x01R\x0finputDurationMs\x12,\n" +
	"\x12output_duration_ms\x18\x14 \x01(\x01R\x10outputDurationMs\x12*\n" +
	"\x11started_offset_ms\x18\x15 \x01(\x01R\x0fstartedOffsetMs\x12,\n" +
	"\x12finished_offset_ms\x18\x16 \x01(\x01R\x10finishedOffsetMs\x12\x1f\n" +
	"\vworker_slot\x18\x17 \x01(\x05R\n" +
	"workerSlot\x12\x1f\n" +
	"\vcpu_threads\x18\x18 \x01(\x05R\n" +
	"cpuThreads\x12%\n" +
	"\x0eparallel_group\x18\x19 \x01(\tR\rparallelGroup\x12\x19\n" +
	"\bscene_id\x18\x1a \x01(\tR\asceneId\x12%\n" +
	"\x0eframes_decoded\x18\x1b \x01(\x03R\rframesDecoded\x12+\n" +
	"\x11frames_composited\x18\x1c \x01(\x03R\x10framesComposited\x12$\n" +
	"\x0effmpeg_speed_x\x18\x1d \x01(\x01R\fffmpegSpeedX\"\xa8\t\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12!\n" +
	"\ferror_detail\x18\x06 \x01(\tR\verrorDetail\x12P\n" +
	"\x11execution_metrics\x18\a \x01(\v2#.velox.control.TaskExecutionMetricsR\x10executionMetrics\x12?\n" +
	"\rphase_markers\x18\b \x03(\v2\x1a.velox.control.PhaseMarkerR\fphaseMarkers\x12\x1f\n" +
	"\vexecutor_id\x18\t \x01(\tR\n" +
	"executorId\x12!\n" +
	"\fexecutor_key\x18\n" +
	" \x01(\tR\vexecutorKey\x12B\n" +
	"\x10output_artifacts\x18\v \x03(\v2\x17.google.protobuf.StructR\x0foutputArtifacts\x12\x19\n" +
	"\blease_id\x18\f \x01(\tR\aleaseId\x12%\n" +
	"\x0eattempt_number\x18\r \x01(\x05R\rattemptNumber\x12\x1a\n" +
	"\brevision\x18\x0e \x01(\x05R\brevision\x12E\n" +
	"\x0fsegment_timings\x18\x0f \x03(\v2\x1c.velox.control.SegmentTimingR\x0esegmentTimings\x122\n" +
	"\x15report_schema_version\x18\x10 \x01(\x05R\x13reportSchemaVersion\x12%\n" +
	"\x0ereport_version\x18\x11 \x01(\x05R\rreportVersion\x12\x1f\n" +
	"\vreport_hash\x18\x12 \x01(\tR\n" +
	"reportHash\x12V\n" +
	"\x15partial_phase_metrics\x18\x13 \x03(\v2\".velox.control.PhaseTimingDetailedR\x13partialPhaseMetrics\x12G\n" +
	"\rphase_timings\x18\x14 \x03(\v2\".velox.control.PhaseTimingDetailedR\fphaseTimings\x128\n" +
	"\x18telemetry_schema_version\x18\x15 \x01(\x05R\x16telemetrySchemaVersion\x12B\n" +
	"\twaterfall\x18\x16 \x03(\v2$.velox.control.AttemptWaterfallStageR\twaterfall\x12?\n" +
	"\n" +
	"milestones\x18\x17 \x03(\v2\x1f.velox.control.AttemptMilestoneR\n" +
	"milestones\x12U\n" +
	"\x11asset_preparation\x18\x18 \x01(\v2(.velox.control.AssetPreparationBreakdownR\x10assetPreparation\"\xdd\b\n" +
	"\x19AssetPreparationBreakdown\x12'\n" +
	"\x0fassets_required\x18\x01 \x01(\x03R\x0eassetsRequired\x12#\n" +
	"\rassets_unique\x18\x02 \x01(\x03R\fassetsUnique\x12\x1d\n" +
	"\n" +
	"cache_hits\x18\x03 \x01(\x03R\tcacheHits\x12!\n" +
	"\fcache_misses\x18\x04 \x01(\x03R\vcacheMisses\x120\n" +
	"\x14ready_before_attempt\x18\x05 \x01(\x03R\x12readyBeforeAttempt\x12:\n" +
	"\x19downloaded_during_attempt\x18\x06 \x01(\x03R\x17downloadedDuringAttempt\x12&\n" +
	"\x0fcache_lookup_ms\x18\a \x01(\x03R\rcacheLookupMs\x12$\n" +
	"\x0eremote_wait_ms\x18\b \x01(\x03R\fremoteWaitMs\x12*\n" +
	"\x11remote_wait_count\x18\t \x01(\x03R\x0fremoteWaitCount\x12(\n" +
	"\x10download_wall_ms\x18\n" +
	" \x01(\x03R\x0edownloadWallMs\x12(\n" +
	"\x10download_work_ms\x18\v \x01(\x03R\x0edownloadWorkMs\x12$\n" +
	"\x0ehash_verify_ms\x18\f \x01(\x03R\fhashVerifyMs\x12*\n" +
	"\x11metadata_probe_ms\x18\r \x01(\x03R\x0fmetadataProbeMs\x120\n" +
	"\x14materialize_local_ms\x18\x0e \x01(\x03R\x12materializeLocalMs\x12&\n" +
	"\x0fcache_hit_bytes\x18\x0f \x01(\x03R\rcacheHitBytes\x12(\n" +
	"\x10cache_miss_bytes\x18\x10 \x01(\x03R\x0ecacheMissBytes\x12,\n" +
	"\x12prefetch_hit_bytes\x18\x11 \x01(\x03R\x10prefetchHitBytes\x12#\n" +
	"\rprefetch_hits\x18\x12 \x01(\x03R\fprefetchHits\x12&\n" +
	"\x0fwarm_cache_hits\x18\x13 \x01(\x03R\rwarmCacheHits\x12+\n" +
	"\x11runtime_downloads\x18\x14 \x01(\x03R\x10runtimeDownloads\x12(\n" +
	"\x10warm_cache_bytes\x18\x15 \x01(\x03R\x0ewarmCacheBytes\x124\n" +
	"\x16runtime_download_bytes\x18\x16 \x01(\x03R\x14runtimeDownloadBytes\x120\n" +
	"\x14required_asset_bytes\x18\x17 \x01(\x03R\x12requiredAssetBytes\x121\n" +
	"\x15latest_prepared_at_ms\x18\x18 \x01(\x03R\x12latestPreparedAtMs\x121\n" +
	"\x15attempt_started_at_ms\x18\x19 \x01(\x03R\x12attemptStartedAtMs\"\xde\x01\n" +
	"\x15AttemptWaterfallStage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\x82\x01\n" +
	"\x10AttemptMilestone\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x03 \x01(\x03R\telapsedMs\x12\x1f\n" +
	"\voccurred_at\x18\x04 \x01(\tR\n" +
	"occurredAt\"\x86\x02\n" +
	"\x10TaskLeaseRenewal\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x02 \x01(\tR\tattemptId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\x12E\n" +
	"\x10requested_expiry\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0frequestedExpiry\x12\x15\n" +
	"\x06job_id\x18\x05 \x01(\tR\x05jobId\x12%\n" +
	"\x0eattempt_number\x18\x06 \x01(\x05R\rattemptNumber\x12\x1a\n" +
	"\brevision\x18\a \x01(\x05R\brevision\"\xc9\x01\n" +
	"\vPhaseMarker\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"\xcd\t\n" +
	"\x13PhaseTimingDetailed\x12\x1f\n" +
	"\vphase_order\x18\x01 \x01(\x05R\n" +
	"phaseOrder\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\b \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12\x19\n" +
	"\bbytes_in\x18\n" +
	" \x01(\x03R\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\v \x01(\x03R\bbytesOut\x12\x16\n" +
	"\x06frames\x18\f \x01(\x03R\x06frames\x12#\n" +
	"\rmetadata_json\x18\r \x01(\tR\fmetadataJson\x12\x16\n" +
	"\x06origin\x18\x0e \x01(\tR\x06origin\x12\x14\n" +
	"\x05scope\x18\x0f \x01(\tR\x05scope\x12\x1d\n" +
	"\n" +
	"event_type\x18\x10 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"event_name\x18\x11 \x01(\tR\teventName\x12\x1f\n" +
	"\vevent_index\x18\x12 \x01(\x03R\n" +
	"eventIndex\x12\x14\n" +
	"\x05phase\x18\x13 \x01(\tR\x05phase\x12\x1f\n" +
	"\vexecutor_id\x18\x14 \x01(\tR\n" +
	"executorId\x12)\n" +
	"\x10executor_version\x18\x15 \x01(\x05R\x0fexecutorVersion\x12\x19\n" +
	"\blease_id\x18\x16 \x01(\tR\aleaseId\x12,\n" +
	"\x12worker_snapshot_id\x18\x17 \x01(\tR\x10workerSnapshotId\x12*\n" +
	"\x11worker_session_id\x18\x18 \x01(\tR\x0fworkerSessionId\x12#\n" +
	"\rsegment_index\x18\x19 \x01(\x05R\fsegmentIndex\x12\x1d\n" +
	"\n" +
	"track_kind\x18\x1a \x01(\tR\ttrackKind\x12\x1f\n" +
	"\vtrack_index\x18\x1b \x01(\x05R\n" +
	"trackIndex\x12*\n" +
	"\x11started_offset_ms\x18\x1c \x01(\x01R\x0fstartedOffsetMs\x12,\n" +
	"\x12finished_offset_ms\x18\x1d \x01(\x01R\x10finishedOffsetMs\x12\x15\n" +
	"\x06cpu_ms\x18\x1e \x01(\x01R\x05cpuMs\x12\"\n" +
	"\rqueue_wait_ms\x18\x1f \x01(\x01R\vqueueWaitMs\x12\x1b\n" +
	"\tframes_in\x18  \x01(\x03R\bframesIn\x12\x1d\n" +
	"\n" +
	"frames_out\x18! \x01(\x03R\tframesOut\x12\x1f\n" +
	"\vartifact_id\x18\" \x01(\tR\n" +
	"artifactId\x128\n" +
	"\x18telemetry_schema_version\x18# \x01(\x05R\x16telemetrySchemaVersionB\"Z velox-shared/controltransport/pbb\x06proto3"

var (
	file_velox_control_worker_to_master_proto_rawDescOnce sync.Once
	file_velox_control_worker_to_master_proto_rawDescData []byte
)

func file_velox_control_worker_to_master_proto_rawDescGZIP() []byte {
	file_velox_control_worker_to_master_proto_rawDescOnce.Do(func() {
		file_velox_control_worker_to_master_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_velox_control_worker_to_master_proto_rawDesc), len(file_velox_control_worker_to_master_proto_rawDesc)))
	})
	return file_velox_control_worker_to_master_proto_rawDescData
}

var file_velox_control_worker_to_master_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_velox_control_worker_to_master_proto_goTypes = []any{
	(*WorkerToMasterEnvelope)(nil),    // 0: velox.control.WorkerToMasterEnvelope
	(*Hello)(nil),                     // 1: velox.control.Hello
	(*Heartbeat)(nil),                 // 2: velox.control.Heartbeat
	(*CommandAck)(nil),                // 3: velox.control.CommandAck
	(*SegmentTiming)(nil),             // 4: velox.control.SegmentTiming
	(*TaskResult)(nil),                // 5: velox.control.TaskResult
	(*AssetPreparationBreakdown)(nil), // 6: velox.control.AssetPreparationBreakdown
	(*AttemptWaterfallStage)(nil),     // 7: velox.control.AttemptWaterfallStage
	(*AttemptMilestone)(nil),          // 8: velox.control.AttemptMilestone
	(*TaskLeaseRenewal)(nil),          // 9: velox.control.TaskLeaseRenewal
	(*PhaseMarker)(nil),               // 10: velox.control.PhaseMarker
	(*PhaseTimingDetailed)(nil),       // 11: velox.control.PhaseTimingDetailed
	(*timestamppb.Timestamp)(nil),     // 12: google.protobuf.Timestamp
	(*TaskAccepted)(nil),              // 13: velox.control.TaskAccepted
	(*TaskRejected)(nil),              // 14: velox.control.TaskRejected
	(*ArtifactUploaded)(nil),          // 15: velox.control.ArtifactUploaded
	(*Goodbye)(nil),                   // 16: velox.control.Goodbye
	(*TaskOutputDeclared)(nil),        // 17: velox.control.TaskOutputDeclared
	(*ArtifactUploadCompleted)(nil),   // 18: velox.control.ArtifactUploadCompleted
	(*AssetDownloadProgress)(nil),     // 19: velox.control.AssetDownloadProgress
	(*ArtifactUploadIntent)(nil),      // 20: velox.control.ArtifactUploadIntent
	(*PrefetchLifecycleEvent)(nil),    // 21: velox.control.PrefetchLifecycleEvent
	(*structpb.Struct)(nil),           // 22: google.protobuf.Struct
	(*WorkerResourceCounters)(nil),    // 23: velox.control.WorkerResourceCounters
	(*TaskExecutionMetrics)(nil),      // 24: velox.control.TaskExecutionMetrics
}
var file_velox_control_worker_to_master_proto_depIdxs = []int32{
	12, // 0: velox.control.WorkerToMasterEnvelope.sent_at:type_name -> google.protobuf.Timestamp
	1,  // 1: velox.control.WorkerToMasterEnvelope.hello:type_name -> velox.control.Hello
	2,  // 2: velox.control.WorkerToMasterEnvelope.heartbeat:type_name -> velox.control.Heartbeat
	13, // 3: velox.control.WorkerToMasterEnvelope.task_accepted:type_name -> velox.control.TaskAccepted
	14, // 4: velox.control.WorkerToMasterEnvelope.task_rejected:type_name -> velox.control.TaskRejected
	5,  // 5: velox.control.WorkerToMasterEnvelope.task_result:type_name -> velox.control.TaskResult
	9,  // 6: velox.control.WorkerToMasterEnvelope.task_lease_renewal:type_name -> velox.control.TaskLeaseRenewal
	3,  // 7: velox.control.WorkerToMasterEnvelope.command_ack:type_name -> velox.control.CommandAck
	15, // 8: velox.control.WorkerToMasterEnvelope.artifact_uploaded:type_name -> velox.control.ArtifactUploaded
	16, // 9: velox.control.WorkerToMasterEnvelope.goodbye:type_name -> velox.control.Goodbye
	17, // 10: velox.control.WorkerToMasterEnvelope.task_output_declared:type_name -> velox.control.TaskOutputDeclared
	18, // 11: velox.control.WorkerToMasterEnvelope.artifact_upload_completed:type_name -> velox.control.ArtifactUploadCompleted
	19, // 12: velox.control.WorkerToMasterEnvelope.asset_download_progress:type_name -> velox.control.AssetDownloadProgress
	20, // 13: velox.control.WorkerToMasterEnvelope.artifact_upload_intent:type_name -> velox.control.ArtifactUploadIntent
	21, // 14: velox.control.WorkerToMasterEnvelope.prefetch_lifecycle_event:type_name -> velox.control.PrefetchLifecycleEvent
	22, // 15: velox.control.Hello.capabilities:type_name -> google.protobuf.Struct
	22, // 16: velox.control.Heartbeat.extra:type_name -> google.protobuf.Struct
	23, // 17: velox.control.Heartbeat.resources:type_name -> velox.control.WorkerResourceCounters
	24, // 18: velox.control.TaskResult.execution_metrics:type_name -> velox.control.TaskExecutionMetrics
	10, // 19: velox.control.TaskResult.phase_markers:type_name -> velox.control.PhaseMarker
	22, // 20: velox.control.TaskResult.output_artifacts:type_name -> google.protobuf.Struct
	4,  // 21: velox.control.TaskResult.segment_timings:type_name -> velox.control.SegmentTiming
	11, // 22: velox.control.TaskResult.partial_phase_metrics:type_name -> velox.control.PhaseTimingDetailed
	11, // 23: velox.control.TaskResult.phase_timings:type_name -> velox.control.PhaseTimingDetailed
	7,  // 24: velox.control.TaskResult.waterfall:type_name -> velox.control.AttemptWaterfallStage
	8,  // 25: velox.control.TaskResult.milestones:type_name -> velox.control.AttemptMilestone
	6,  // 26: velox.control.TaskResult.asset_preparation:type_name -> velox.control.AssetPreparationBreakdown
	12, // 27: velox.control.AttemptWaterfallStage.started_at:type_name -> google.protobuf.Timestamp
	12, // 28: velox.control.AttemptWaterfallStage.completed_at:type_name -> google.protobuf.Timestamp
	12, // 29: velox.control.TaskLeaseRenewal.requested_expiry:type_name -> google.protobuf.Timestamp
	12, // 30: velox.control.PhaseMarker.started_at:type_name -> google.protobuf.Timestamp
	12, // 31: velox.control.PhaseMarker.completed_at:type_name -> google.protobuf.Timestamp
	12, // 32: velox.control.PhaseTimingDetailed.started_at:type_name -> google.protobuf.Timestamp
	12, // 33: velox.control.PhaseTimingDetailed.completed_at:type_name -> google.protobuf.Timestamp
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_velox_control_worker_to_master_proto_init() }
func file_velox_control_worker_to_master_proto_init() {
	if File_velox_control_worker_to_master_proto != nil {
		return
	}
	file_velox_control_control_common_proto_init()
	file_velox_control_worker_events_proto_init()
	file_velox_control_worker_to_master_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerToMasterEnvelope_Hello)(nil),
		(*WorkerToMasterEnvelope_Heartbeat)(nil),
		(*WorkerToMasterEnvelope_TaskAccepted)(nil),
		(*WorkerToMasterEnvelope_TaskRejected)(nil),
		(*WorkerToMasterEnvelope_TaskResult)(nil),
		(*WorkerToMasterEnvelope_TaskLeaseRenewal)(nil),
		(*WorkerToMasterEnvelope_CommandAck)(nil),
		(*WorkerToMasterEnvelope_ArtifactUploaded)(nil),
		(*WorkerToMasterEnvelope_Goodbye)(nil),
		(*WorkerToMasterEnvelope_TaskOutputDeclared)(nil),
		(*WorkerToMasterEnvelope_ArtifactUploadCompleted)(nil),
		(*WorkerToMasterEnvelope_AssetDownloadProgress)(nil),
		(*WorkerToMasterEnvelope_ArtifactUploadIntent)(nil),
		(*WorkerToMasterEnvelope_PrefetchLifecycleEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_velox_control_worker_to_master_proto_rawDesc), len(file_velox_control_worker_to_master_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_velox_control_worker_to_master_proto_goTypes,
		DependencyIndexes: file_velox_control_worker_to_master_proto_depIdxs,
		MessageInfos:      file_velox_control_worker_to_master_proto_msgTypes,
	}.Build()
	File_velox_control_worker_to_master_proto = out.File
	file_velox_control_worker_to_master_proto_goTypes = nil
	file_velox_control_worker_to_master_proto_depIdxs = nil
}
