// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: velox/control/worker_control.proto

// Proto definition for Velox Worker-Control bidirectional stream.
// Both master (DataServer) and worker (worker-agent-go) use this contract
// for typed, versioned control-plane communication.
//
// Phase 2 (typed protobuf): message types are strongly typed with oneof
// instead of the legacy TransportMessage { string type; Struct payload; }.
// google.protobuf.Struct is retained only for genuinely dynamic fields
// (capabilities, extra, job_payload, params, configuration).
//
// Phase E cutover (May 2026): the MasterToWorkerEnvelope oneof no longer
// emits a forward-only JobAvailable notification. The wire-level field
// number 21 is reserved-but-unused to preserve field-number compatibility
// with previously-deployed workers/masters. New clients MUST NOT expect
// JobAvailable on this oneof; gRPC is the single delivery channel post
// cutover.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------------------------------------------------------
// Worker -> Master
// ---------------------------------------------------------
type WorkerToMasterEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	WorkerId        string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SequenceNumber  int64                  `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	SentAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*WorkerToMasterEnvelope_Hello
	//	*WorkerToMasterEnvelope_Heartbeat
	//	*WorkerToMasterEnvelope_LeaseRenewal
	//	*WorkerToMasterEnvelope_JobAccepted
	//	*WorkerToMasterEnvelope_JobRejected
	//	*WorkerToMasterEnvelope_TaskAccepted
	//	*WorkerToMasterEnvelope_TaskRejected
	//	*WorkerToMasterEnvelope_TaskResult
	//	*WorkerToMasterEnvelope_JobProgress
	//	*WorkerToMasterEnvelope_CommandAck
	//	*WorkerToMasterEnvelope_JobResult
	//	*WorkerToMasterEnvelope_ArtifactUploaded
	//	*WorkerToMasterEnvelope_Goodbye
	Msg           isWorkerToMasterEnvelope_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerToMasterEnvelope) Reset() {
	*x = WorkerToMasterEnvelope{}
	mi := &file_velox_control_worker_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerToMasterEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerToMasterEnvelope) ProtoMessage() {}

func (x *WorkerToMasterEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerToMasterEnvelope.ProtoReflect.Descriptor instead.
func (*WorkerToMasterEnvelope) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerToMasterEnvelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *WorkerToMasterEnvelope) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerToMasterEnvelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WorkerToMasterEnvelope) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *WorkerToMasterEnvelope) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *WorkerToMasterEnvelope) GetMsg() isWorkerToMasterEnvelope_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetLeaseRenewal() *LeaseRenewal {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_LeaseRenewal); ok {
			return x.LeaseRenewal
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetJobAccepted() *JobAccepted {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_JobAccepted); ok {
			return x.JobAccepted
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetJobRejected() *JobRejected {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_JobRejected); ok {
			return x.JobRejected
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetTaskAccepted() *TaskAccepted {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_TaskAccepted); ok {
			return x.TaskAccepted
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetTaskRejected() *TaskRejected {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_TaskRejected); ok {
			return x.TaskRejected
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetTaskResult() *TaskResult {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_TaskResult); ok {
			return x.TaskResult
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetJobProgress() *JobProgress {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_JobProgress); ok {
			return x.JobProgress
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetCommandAck() *CommandAck {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_CommandAck); ok {
			return x.CommandAck
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetJobResult() *JobResult {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_JobResult); ok {
			return x.JobResult
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetArtifactUploaded() *ArtifactUploaded {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_ArtifactUploaded); ok {
			return x.ArtifactUploaded
		}
	}
	return nil
}

func (x *WorkerToMasterEnvelope) GetGoodbye() *Goodbye {
	if x != nil {
		if x, ok := x.Msg.(*WorkerToMasterEnvelope_Goodbye); ok {
			return x.Goodbye
		}
	}
	return nil
}

type isWorkerToMasterEnvelope_Msg interface {
	isWorkerToMasterEnvelope_Msg()
}

type WorkerToMasterEnvelope_Hello struct {
	Hello *Hello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type WorkerToMasterEnvelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type WorkerToMasterEnvelope_LeaseRenewal struct {
	LeaseRenewal *LeaseRenewal `protobuf:"bytes,12,opt,name=lease_renewal,json=leaseRenewal,proto3,oneof"`
}

type WorkerToMasterEnvelope_JobAccepted struct {
	JobAccepted *JobAccepted `protobuf:"bytes,13,opt,name=job_accepted,json=jobAccepted,proto3,oneof"`
}

type WorkerToMasterEnvelope_JobRejected struct {
	JobRejected *JobRejected `protobuf:"bytes,14,opt,name=job_rejected,json=jobRejected,proto3,oneof"`
}

type WorkerToMasterEnvelope_TaskAccepted struct {
	TaskAccepted *TaskAccepted `protobuf:"bytes,20,opt,name=task_accepted,json=taskAccepted,proto3,oneof"`
}

type WorkerToMasterEnvelope_TaskRejected struct {
	TaskRejected *TaskRejected `protobuf:"bytes,21,opt,name=task_rejected,json=taskRejected,proto3,oneof"`
}

type WorkerToMasterEnvelope_TaskResult struct {
	TaskResult *TaskResult `protobuf:"bytes,22,opt,name=task_result,json=taskResult,proto3,oneof"`
}

type WorkerToMasterEnvelope_JobProgress struct {
	JobProgress *JobProgress `protobuf:"bytes,15,opt,name=job_progress,json=jobProgress,proto3,oneof"`
}

type WorkerToMasterEnvelope_CommandAck struct {
	CommandAck *CommandAck `protobuf:"bytes,16,opt,name=command_ack,json=commandAck,proto3,oneof"`
}

type WorkerToMasterEnvelope_JobResult struct {
	JobResult *JobResult `protobuf:"bytes,17,opt,name=job_result,json=jobResult,proto3,oneof"`
}

type WorkerToMasterEnvelope_ArtifactUploaded struct {
	ArtifactUploaded *ArtifactUploaded `protobuf:"bytes,18,opt,name=artifact_uploaded,json=artifactUploaded,proto3,oneof"`
}

type WorkerToMasterEnvelope_Goodbye struct {
	Goodbye *Goodbye `protobuf:"bytes,19,opt,name=goodbye,proto3,oneof"`
}

func (*WorkerToMasterEnvelope_Hello) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_Heartbeat) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_LeaseRenewal) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_JobAccepted) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_JobRejected) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_TaskAccepted) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_TaskRejected) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_TaskResult) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_JobProgress) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_CommandAck) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_JobResult) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_ArtifactUploaded) isWorkerToMasterEnvelope_Msg() {}

func (*WorkerToMasterEnvelope_Goodbye) isWorkerToMasterEnvelope_Msg() {}

type Hello struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerName     string                 `protobuf:"bytes,1,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	Hostname       string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Version        string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	BundleVersion  string                 `protobuf:"bytes,4,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`
	BundleHash     string                 `protobuf:"bytes,5,opt,name=bundle_hash,json=bundleHash,proto3" json:"bundle_hash,omitempty"`
	EngineVersion  string                 `protobuf:"bytes,6,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	CredentialHash string                 `protobuf:"bytes,7,opt,name=credential_hash,json=credentialHash,proto3" json:"credential_hash,omitempty"`
	Capabilities   *structpb.Struct       `protobuf:"bytes,8,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_velox_control_worker_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Hello) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Hello) GetBundleVersion() string {
	if x != nil {
		return x.BundleVersion
	}
	return ""
}

func (x *Hello) GetBundleHash() string {
	if x != nil {
		return x.BundleHash
	}
	return ""
}

func (x *Hello) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *Hello) GetCredentialHash() string {
	if x != nil {
		return x.CredentialHash
	}
	return ""
}

func (x *Hello) GetCapabilities() *structpb.Struct {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Heartbeat struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerName      string                 `protobuf:"bytes,1,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	WorkerStatus    string                 `protobuf:"bytes,2,opt,name=worker_status,json=workerStatus,proto3" json:"worker_status,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	CurrentJob      string                 `protobuf:"bytes,4,opt,name=current_job,json=currentJob,proto3" json:"current_job,omitempty"`
	CodeVersion     string                 `protobuf:"bytes,5,opt,name=code_version,json=codeVersion,proto3" json:"code_version,omitempty"`
	BundleVersion   string                 `protobuf:"bytes,6,opt,name=bundle_version,json=bundleVersion,proto3" json:"bundle_version,omitempty"`
	BundleHash      string                 `protobuf:"bytes,7,opt,name=bundle_hash,json=bundleHash,proto3" json:"bundle_hash,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,8,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	EngineVersion   string                 `protobuf:"bytes,9,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	JobsCompleted   int64                  `protobuf:"varint,10,opt,name=jobs_completed,json=jobsCompleted,proto3" json:"jobs_completed,omitempty"`
	JobsFailed      int64                  `protobuf:"varint,11,opt,name=jobs_failed,json=jobsFailed,proto3" json:"jobs_failed,omitempty"`
	ActiveJobsCount int32                  `protobuf:"varint,12,opt,name=active_jobs_count,json=activeJobsCount,proto3" json:"active_jobs_count,omitempty"`
	Extra           *structpb.Struct       `protobuf:"bytes,13,opt,name=extra,proto3" json:"extra,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_velox_control_worker_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *Heartbeat) GetWorkerStatus() string {
	if x != nil {
		return x.WorkerStatus
	}
	return ""
}

func (x *Heartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Heartbeat) GetCurrentJob() string {
	if x != nil {
		return x.CurrentJob
	}
	return ""
}

func (x *Heartbeat) GetCodeVersion() string {
	if x != nil {
		return x.CodeVersion
	}
	return ""
}

func (x *Heartbeat) GetBundleVersion() string {
	if x != nil {
		return x.BundleVersion
	}
	return ""
}

func (x *Heartbeat) GetBundleHash() string {
	if x != nil {
		return x.BundleHash
	}
	return ""
}

func (x *Heartbeat) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Heartbeat) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

func (x *Heartbeat) GetJobsCompleted() int64 {
	if x != nil {
		return x.JobsCompleted
	}
	return 0
}

func (x *Heartbeat) GetJobsFailed() int64 {
	if x != nil {
		return x.JobsFailed
	}
	return 0
}

func (x *Heartbeat) GetActiveJobsCount() int32 {
	if x != nil {
		return x.ActiveJobsCount
	}
	return 0
}

func (x *Heartbeat) GetExtra() *structpb.Struct {
	if x != nil {
		return x.Extra
	}
	return nil
}

type LeaseRenewal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	LeaseId        string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Attempt        int32                  `protobuf:"varint,3,opt,name=attempt,proto3" json:"attempt,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LeaseRenewal) Reset() {
	*x = LeaseRenewal{}
	mi := &file_velox_control_worker_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRenewal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRenewal) ProtoMessage() {}

func (x *LeaseRenewal) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRenewal.ProtoReflect.Descriptor instead.
func (*LeaseRenewal) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{3}
}

func (x *LeaseRenewal) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *LeaseRenewal) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *LeaseRenewal) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *LeaseRenewal) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

type JobAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobRunId      string                 `protobuf:"bytes,2,opt,name=job_run_id,json=jobRunId,proto3" json:"job_run_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,3,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobAccepted) Reset() {
	*x = JobAccepted{}
	mi := &file_velox_control_worker_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobAccepted) ProtoMessage() {}

func (x *JobAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobAccepted.ProtoReflect.Descriptor instead.
func (*JobAccepted) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{4}
}

func (x *JobAccepted) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobAccepted) GetJobRunId() string {
	if x != nil {
		return x.JobRunId
	}
	return ""
}

func (x *JobAccepted) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

type JobRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobRejected) Reset() {
	*x = JobRejected{}
	mi := &file_velox_control_worker_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRejected) ProtoMessage() {}

func (x *JobRejected) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRejected.ProtoReflect.Descriptor instead.
func (*JobRejected) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{5}
}

func (x *JobRejected) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobRejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type JobProgress struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Stage           string                 `protobuf:"bytes,2,opt,name=stage,proto3" json:"stage,omitempty"`
	ProgressPercent int32                  `protobuf:"varint,3,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	Scene           int32                  `protobuf:"varint,4,opt,name=scene,proto3" json:"scene,omitempty"`
	TotalScenes     int32                  `protobuf:"varint,5,opt,name=total_scenes,json=totalScenes,proto3" json:"total_scenes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobProgress) Reset() {
	*x = JobProgress{}
	mi := &file_velox_control_worker_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobProgress) ProtoMessage() {}

func (x *JobProgress) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobProgress.ProtoReflect.Descriptor instead.
func (*JobProgress) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{6}
}

func (x *JobProgress) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *JobProgress) GetProgressPercent() int32 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *JobProgress) GetScene() int32 {
	if x != nil {
		return x.Scene
	}
	return 0
}

func (x *JobProgress) GetTotalScenes() int32 {
	if x != nil {
		return x.TotalScenes
	}
	return 0
}

type CommandAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_velox_control_worker_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{7}
}

func (x *CommandAck) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandAck) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type JobResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobRunId      string                 `protobuf:"bytes,2,opt,name=job_run_id,json=jobRunId,proto3" json:"job_run_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	StartTime     string                 `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                 `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	LeaseId       string                 `protobuf:"bytes,7,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Attempt       int32                  `protobuf:"varint,8,opt,name=attempt,proto3" json:"attempt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResult) Reset() {
	*x = JobResult{}
	mi := &file_velox_control_worker_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResult) ProtoMessage() {}

func (x *JobResult) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResult.ProtoReflect.Descriptor instead.
func (*JobResult) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{8}
}

func (x *JobResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResult) GetJobRunId() string {
	if x != nil {
		return x.JobRunId
	}
	return ""
}

func (x *JobResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JobResult) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *JobResult) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *JobResult) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *JobResult) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

// TaskResult is the task-native execution report (PR #5).
// Sent by the worker after completing or failing a task.
//
// PR #5 (feat/task-result): output_artifacts carries the list of
// artifacts produced by this task execution; the master registers
// them via the artifact service. lease_id is the CAS token the
// worker received with the TaskOffer.
type TaskResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId           string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AttemptId       string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "succeeded" or "failed"
	ErrorCode       string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorDetail     string                 `protobuf:"bytes,6,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	Metrics         *structpb.Struct       `protobuf:"bytes,7,opt,name=metrics,proto3" json:"metrics,omitempty"`
	PhaseMarkers    []*PhaseMarker         `protobuf:"bytes,8,rep,name=phase_markers,json=phaseMarkers,proto3" json:"phase_markers,omitempty"`
	ExecutorId      string                 `protobuf:"bytes,9,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	ExecutorKey     string                 `protobuf:"bytes,10,opt,name=executor_key,json=executorKey,proto3" json:"executor_key,omitempty"`
	OutputArtifacts []*structpb.Struct     `protobuf:"bytes,11,rep,name=output_artifacts,json=outputArtifacts,proto3" json:"output_artifacts,omitempty"`
	LeaseId         string                 `protobuf:"bytes,12,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_velox_control_worker_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{9}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskResult) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TaskResult) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

func (x *TaskResult) GetMetrics() *structpb.Struct {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *TaskResult) GetPhaseMarkers() []*PhaseMarker {
	if x != nil {
		return x.PhaseMarkers
	}
	return nil
}

func (x *TaskResult) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *TaskResult) GetExecutorKey() string {
	if x != nil {
		return x.ExecutorKey
	}
	return ""
}

func (x *TaskResult) GetOutputArtifacts() []*structpb.Struct {
	if x != nil {
		return x.OutputArtifacts
	}
	return nil
}

func (x *TaskResult) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

// PhaseMarker records one canonical phase timing.
type PhaseMarker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Notes         string                 `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PhaseMarker) Reset() {
	*x = PhaseMarker{}
	mi := &file_velox_control_worker_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PhaseMarker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PhaseMarker) ProtoMessage() {}

func (x *PhaseMarker) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PhaseMarker.ProtoReflect.Descriptor instead.
func (*PhaseMarker) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{10}
}

func (x *PhaseMarker) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PhaseMarker) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *PhaseMarker) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *PhaseMarker) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PhaseMarker) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type ArtifactUploaded struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ArtifactUploaded — master-authoritative artifact boundary.
	//
	// The master is the authoritative source of truth for each artifact's
	// size and content hash; every other worker-supplied field is recomputed
	// by the master from the streamed bytes.
	// The worker is only allowed to declare WHICH artifact it uploaded (via
	// the upload_id returned by Service.BeginUpload); every other field the
	// worker submits is recomputed by the master from the streamed bytes.
	//
	// DEPRECATED FIELDS (kept on the wire for compat with pre-cutover workers;
	// master ignores them entirely):
	// by the master): artifact_path (4), artifact_size (5), upload_status (6),
	// error (7). The master recomputes size / sha / mime from the streamed
	// bytes; the worker-supplied path and size are NEVER used as sources of
	// truth in the new pipeline authorized via Service.Finalize.
	//
	// NEW REQUIRED FIELDS:
	//   - upload_id (8)        — the master-side session identifier returned
	//     by Service.BeginUpload. The worker forwards
	//     this and the master uses it to recover the
	//     artifact_uploads row + the streamed bytes.
	//   - lease_id   (9)       — copied from the JOB_RUNNING state, CAS-gated
	//     in Service.FinalizeArtifactAndCompleteJob.
	//   - attempt    (10)      — attempt_number the worker finished.
	//   - expected_revision (11) — the job.revision the worker observed when
	//     it accepted the lease; CAS-gated in
	//     Service.FinalizeArtifactAndCompleteJob.
	JobId            string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ArtifactId       string `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ArtifactType     string `protobuf:"bytes,3,opt,name=artifact_type,json=artifactType,proto3" json:"artifact_type,omitempty"`
	ArtifactPath     string `protobuf:"bytes,4,opt,name=artifact_path,json=artifactPath,proto3" json:"artifact_path,omitempty"`
	ArtifactSize     int64  `protobuf:"varint,5,opt,name=artifact_size,json=artifactSize,proto3" json:"artifact_size,omitempty"`
	UploadStatus     string `protobuf:"bytes,6,opt,name=upload_status,json=uploadStatus,proto3" json:"upload_status,omitempty"`
	Error            string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	UploadId         string `protobuf:"bytes,8,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	LeaseId          string `protobuf:"bytes,9,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Attempt          int32  `protobuf:"varint,10,opt,name=attempt,proto3" json:"attempt,omitempty"`
	ExpectedRevision int32  `protobuf:"varint,11,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ArtifactUploaded) Reset() {
	*x = ArtifactUploaded{}
	mi := &file_velox_control_worker_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactUploaded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactUploaded) ProtoMessage() {}

func (x *ArtifactUploaded) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactUploaded.ProtoReflect.Descriptor instead.
func (*ArtifactUploaded) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{11}
}

func (x *ArtifactUploaded) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ArtifactUploaded) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactUploaded) GetArtifactType() string {
	if x != nil {
		return x.ArtifactType
	}
	return ""
}

func (x *ArtifactUploaded) GetArtifactPath() string {
	if x != nil {
		return x.ArtifactPath
	}
	return ""
}

func (x *ArtifactUploaded) GetArtifactSize() int64 {
	if x != nil {
		return x.ArtifactSize
	}
	return 0
}

func (x *ArtifactUploaded) GetUploadStatus() string {
	if x != nil {
		return x.UploadStatus
	}
	return ""
}

func (x *ArtifactUploaded) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ArtifactUploaded) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *ArtifactUploaded) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ArtifactUploaded) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ArtifactUploaded) GetExpectedRevision() int32 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

type Goodbye struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goodbye) Reset() {
	*x = Goodbye{}
	mi := &file_velox_control_worker_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goodbye) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goodbye) ProtoMessage() {}

func (x *Goodbye) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goodbye.ProtoReflect.Descriptor instead.
func (*Goodbye) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{12}
}

// ---------------------------------------------------------
// Master -> Worker
// ---------------------------------------------------------
type MasterToWorkerEnvelope struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	WorkerId        string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SequenceNumber  int64                  `protobuf:"varint,4,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	SentAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// JobAvailable removed in Phase E (forward-only notification, dropped in gRPC cutover).
	//
	// The matching `reserved 21;` directive in the message-level reserved block
	// below exists for wire-level compatibility with previously-deployed
	// workers/masters: it prevents tag 21 from being accidentally reused in
	// future oneof additions. It does NOT participate in descriptor init — the
	// pre-existing `slice bounds out of range [:22] with capacity 21` init panic
	// (PR-3.11) was caused by `worker_control.pb.go` having drifted from this
	// schema after Phase E, not by the absence of a reserved directive. The
	// canonical fix is `bash scripts/gen-proto.sh`, which regenerates the
	// descriptor with `--go_opt=module=velox-shared` so the file lands at
	// `shared/controltransport/pb/worker_control.pb.go`.
	//
	// Types that are valid to be assigned to Msg:
	//
	//	*MasterToWorkerEnvelope_HelloAck
	//	*MasterToWorkerEnvelope_JobOffer
	//	*MasterToWorkerEnvelope_TaskOffer
	//	*MasterToWorkerEnvelope_JobLeaseGranted
	//	*MasterToWorkerEnvelope_TaskLeaseGranted
	//	*MasterToWorkerEnvelope_Command
	//	*MasterToWorkerEnvelope_CancelJob
	//	*MasterToWorkerEnvelope_Drain
	//	*MasterToWorkerEnvelope_ConfigurationUpdate
	//	*MasterToWorkerEnvelope_LeaseRevoked
	//	*MasterToWorkerEnvelope_Ping
	Msg           isMasterToWorkerEnvelope_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MasterToWorkerEnvelope) Reset() {
	*x = MasterToWorkerEnvelope{}
	mi := &file_velox_control_worker_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MasterToWorkerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterToWorkerEnvelope) ProtoMessage() {}

func (x *MasterToWorkerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterToWorkerEnvelope.ProtoReflect.Descriptor instead.
func (*MasterToWorkerEnvelope) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{13}
}

func (x *MasterToWorkerEnvelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MasterToWorkerEnvelope) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *MasterToWorkerEnvelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MasterToWorkerEnvelope) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *MasterToWorkerEnvelope) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *MasterToWorkerEnvelope) GetMsg() isMasterToWorkerEnvelope_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetJobOffer() *JobOffer {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_JobOffer); ok {
			return x.JobOffer
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetTaskOffer() *TaskOffer {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_TaskOffer); ok {
			return x.TaskOffer
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetJobLeaseGranted() *JobLeaseGranted {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_JobLeaseGranted); ok {
			return x.JobLeaseGranted
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetTaskLeaseGranted() *TaskLeaseGranted {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_TaskLeaseGranted); ok {
			return x.TaskLeaseGranted
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetCommand() *Command {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_Command); ok {
			return x.Command
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetCancelJob() *CancelJob {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_CancelJob); ok {
			return x.CancelJob
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetDrain() *Drain {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetConfigurationUpdate() *ConfigurationUpdate {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_ConfigurationUpdate); ok {
			return x.ConfigurationUpdate
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetLeaseRevoked() *LeaseRevoked {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_LeaseRevoked); ok {
			return x.LeaseRevoked
		}
	}
	return nil
}

func (x *MasterToWorkerEnvelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Msg.(*MasterToWorkerEnvelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isMasterToWorkerEnvelope_Msg interface {
	isMasterToWorkerEnvelope_Msg()
}

type MasterToWorkerEnvelope_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,20,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type MasterToWorkerEnvelope_JobOffer struct {
	JobOffer *JobOffer `protobuf:"bytes,22,opt,name=job_offer,json=jobOffer,proto3,oneof"`
}

type MasterToWorkerEnvelope_TaskOffer struct {
	TaskOffer *TaskOffer `protobuf:"bytes,30,opt,name=task_offer,json=taskOffer,proto3,oneof"`
}

type MasterToWorkerEnvelope_JobLeaseGranted struct {
	JobLeaseGranted *JobLeaseGranted `protobuf:"bytes,23,opt,name=job_lease_granted,json=jobLeaseGranted,proto3,oneof"`
}

type MasterToWorkerEnvelope_TaskLeaseGranted struct {
	TaskLeaseGranted *TaskLeaseGranted `protobuf:"bytes,31,opt,name=task_lease_granted,json=taskLeaseGranted,proto3,oneof"`
}

type MasterToWorkerEnvelope_Command struct {
	Command *Command `protobuf:"bytes,24,opt,name=command,proto3,oneof"`
}

type MasterToWorkerEnvelope_CancelJob struct {
	CancelJob *CancelJob `protobuf:"bytes,25,opt,name=cancel_job,json=cancelJob,proto3,oneof"`
}

type MasterToWorkerEnvelope_Drain struct {
	Drain *Drain `protobuf:"bytes,26,opt,name=drain,proto3,oneof"`
}

type MasterToWorkerEnvelope_ConfigurationUpdate struct {
	ConfigurationUpdate *ConfigurationUpdate `protobuf:"bytes,27,opt,name=configuration_update,json=configurationUpdate,proto3,oneof"`
}

type MasterToWorkerEnvelope_LeaseRevoked struct {
	LeaseRevoked *LeaseRevoked `protobuf:"bytes,28,opt,name=lease_revoked,json=leaseRevoked,proto3,oneof"`
}

type MasterToWorkerEnvelope_Ping struct {
	Ping *Ping `protobuf:"bytes,29,opt,name=ping,proto3,oneof"`
}

func (*MasterToWorkerEnvelope_HelloAck) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_JobOffer) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_TaskOffer) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_JobLeaseGranted) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_TaskLeaseGranted) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_Command) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_CancelJob) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_Drain) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_ConfigurationUpdate) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_LeaseRevoked) isMasterToWorkerEnvelope_Msg() {}

func (*MasterToWorkerEnvelope_Ping) isMasterToWorkerEnvelope_Msg() {}

type HelloAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_velox_control_worker_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{14}
}

type JobOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	VideoName     string                 `protobuf:"bytes,3,opt,name=video_name,json=videoName,proto3" json:"video_name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LeaseId       string                 `protobuf:"bytes,5,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseExpiry   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=lease_expiry,json=leaseExpiry,proto3" json:"lease_expiry,omitempty"`
	Attempt       int32                  `protobuf:"varint,7,opt,name=attempt,proto3" json:"attempt,omitempty"`
	MaxRetries    int32                  `protobuf:"varint,8,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	JobPayload    *structpb.Struct       `protobuf:"bytes,9,opt,name=job_payload,json=jobPayload,proto3" json:"job_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobOffer) Reset() {
	*x = JobOffer{}
	mi := &file_velox_control_worker_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobOffer) ProtoMessage() {}

func (x *JobOffer) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobOffer.ProtoReflect.Descriptor instead.
func (*JobOffer) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{15}
}

func (x *JobOffer) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobOffer) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *JobOffer) GetVideoName() string {
	if x != nil {
		return x.VideoName
	}
	return ""
}

func (x *JobOffer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JobOffer) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *JobOffer) GetLeaseExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiry
	}
	return nil
}

func (x *JobOffer) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *JobOffer) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *JobOffer) GetJobPayload() *structpb.Struct {
	if x != nil {
		return x.JobPayload
	}
	return nil
}

// TaskOffer is the task-native dispatch message (PR #4).
// Replaces JobOffer for task-based dispatching: the dispatcher claims
// a READY Task, creates a TaskAttempt, and sends this message.
type TaskOffer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TaskId          string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId           string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AttemptId       string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	ExecutorId      string                 `protobuf:"bytes,4,opt,name=executor_id,json=executorId,proto3" json:"executor_id,omitempty"`
	ExecutorVersion int32                  `protobuf:"varint,5,opt,name=executor_version,json=executorVersion,proto3" json:"executor_version,omitempty"`
	TaskSpec        *structpb.Struct       `protobuf:"bytes,6,opt,name=task_spec,json=taskSpec,proto3" json:"task_spec,omitempty"`
	LeaseId         string                 `protobuf:"bytes,7,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	LeaseDeadline   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=lease_deadline,json=leaseDeadline,proto3" json:"lease_deadline,omitempty"`
	Requirements    *structpb.Struct       `protobuf:"bytes,9,opt,name=requirements,proto3" json:"requirements,omitempty"`
	OutputContract  *structpb.Struct       `protobuf:"bytes,10,opt,name=output_contract,json=outputContract,proto3" json:"output_contract,omitempty"`
	AttemptNumber   int32                  `protobuf:"varint,11,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskOffer) Reset() {
	*x = TaskOffer{}
	mi := &file_velox_control_worker_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOffer) ProtoMessage() {}

func (x *TaskOffer) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOffer.ProtoReflect.Descriptor instead.
func (*TaskOffer) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{16}
}

func (x *TaskOffer) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskOffer) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskOffer) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskOffer) GetExecutorId() string {
	if x != nil {
		return x.ExecutorId
	}
	return ""
}

func (x *TaskOffer) GetExecutorVersion() int32 {
	if x != nil {
		return x.ExecutorVersion
	}
	return 0
}

func (x *TaskOffer) GetTaskSpec() *structpb.Struct {
	if x != nil {
		return x.TaskSpec
	}
	return nil
}

func (x *TaskOffer) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *TaskOffer) GetLeaseDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseDeadline
	}
	return nil
}

func (x *TaskOffer) GetRequirements() *structpb.Struct {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *TaskOffer) GetOutputContract() *structpb.Struct {
	if x != nil {
		return x.OutputContract
	}
	return nil
}

func (x *TaskOffer) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

// TaskAccepted is sent by a worker when it accepts a TaskOffer.
type TaskAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,4,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskAccepted) Reset() {
	*x = TaskAccepted{}
	mi := &file_velox_control_worker_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskAccepted) ProtoMessage() {}

func (x *TaskAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskAccepted.ProtoReflect.Descriptor instead.
func (*TaskAccepted) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{17}
}

func (x *TaskAccepted) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskAccepted) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *TaskAccepted) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskAccepted) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

// TaskRejected is sent by a worker when it rejects a TaskOffer.
type TaskRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRejected) Reset() {
	*x = TaskRejected{}
	mi := &file_velox_control_worker_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRejected) ProtoMessage() {}

func (x *TaskRejected) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRejected.ProtoReflect.Descriptor instead.
func (*TaskRejected) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{18}
}

func (x *TaskRejected) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskRejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type JobLeaseGranted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	LeaseId       string                 `protobuf:"bytes,4,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobLeaseGranted) Reset() {
	*x = JobLeaseGranted{}
	mi := &file_velox_control_worker_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobLeaseGranted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobLeaseGranted) ProtoMessage() {}

func (x *JobLeaseGranted) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobLeaseGranted.ProtoReflect.Descriptor instead.
func (*JobLeaseGranted) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{19}
}

func (x *JobLeaseGranted) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobLeaseGranted) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JobLeaseGranted) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobLeaseGranted) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

// TaskLeaseGranted is the task-scoped grant (PR #5 followup).
// Replaces JobLeaseGranted for task-native dispatch: the master
// sends this after the worker accepts a TaskOffer and the task
// transitions LEASED→RUNNING.
type TaskLeaseGranted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	LeaseId       string                 `protobuf:"bytes,2,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	AttemptId     string                 `protobuf:"bytes,3,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	JobId         string                 `protobuf:"bytes,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskLeaseGranted) Reset() {
	*x = TaskLeaseGranted{}
	mi := &file_velox_control_worker_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskLeaseGranted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskLeaseGranted) ProtoMessage() {}

func (x *TaskLeaseGranted) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskLeaseGranted.ProtoReflect.Descriptor instead.
func (*TaskLeaseGranted) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{20}
}

func (x *TaskLeaseGranted) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskLeaseGranted) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *TaskLeaseGranted) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *TaskLeaseGranted) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Params        *structpb.Struct       `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_velox_control_worker_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{21}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Command) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Command) GetParams() *structpb.Struct {
	if x != nil {
		return x.Params
	}
	return nil
}

type CancelJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJob) Reset() {
	*x = CancelJob{}
	mi := &file_velox_control_worker_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJob) ProtoMessage() {}

func (x *CancelJob) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJob.ProtoReflect.Descriptor instead.
func (*CancelJob) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{22}
}

func (x *CancelJob) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type Drain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drain) Reset() {
	*x = Drain{}
	mi := &file_velox_control_worker_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drain) ProtoMessage() {}

func (x *Drain) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drain.ProtoReflect.Descriptor instead.
func (*Drain) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{23}
}

func (x *Drain) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ConfigurationUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configuration *structpb.Struct       `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationUpdate) Reset() {
	*x = ConfigurationUpdate{}
	mi := &file_velox_control_worker_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationUpdate) ProtoMessage() {}

func (x *ConfigurationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationUpdate.ProtoReflect.Descriptor instead.
func (*ConfigurationUpdate) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{24}
}

func (x *ConfigurationUpdate) GetConfiguration() *structpb.Struct {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type LeaseRevoked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseRevoked) Reset() {
	*x = LeaseRevoked{}
	mi := &file_velox_control_worker_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseRevoked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseRevoked) ProtoMessage() {}

func (x *LeaseRevoked) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseRevoked.ProtoReflect.Descriptor instead.
func (*LeaseRevoked) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{25}
}

func (x *LeaseRevoked) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *LeaseRevoked) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_velox_control_worker_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{26}
}

var File_velox_control_worker_control_proto protoreflect.FileDescriptor

const file_velox_control_worker_control_proto_rawDesc = "" +
	"\n" +
	"\"velox/control/worker_control.proto\x12\rvelox.control\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xb5\b\n" +
	"\x16WorkerToMasterEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x03R\x0esequenceNumber\x123\n" +
	"\asent_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12)\n" +
	"\x10protocol_version\x18\x06 \x01(\tR\x0fprotocolVersion\x12,\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x14.velox.control.HelloH\x00R\x05hello\x128\n" +
	"\theartbeat\x18\v \x01(\v2\x18.velox.control.HeartbeatH\x00R\theartbeat\x12B\n" +
	"\rlease_renewal\x18\f \x01(\v2\x1b.velox.control.LeaseRenewalH\x00R\fleaseRenewal\x12?\n" +
	"\fjob_accepted\x18\r \x01(\v2\x1a.velox.control.JobAcceptedH\x00R\vjobAccepted\x12?\n" +
	"\fjob_rejected\x18\x0e \x01(\v2\x1a.velox.control.JobRejectedH\x00R\vjobRejected\x12B\n" +
	"\rtask_accepted\x18\x14 \x01(\v2\x1b.velox.control.TaskAcceptedH\x00R\ftaskAccepted\x12B\n" +
	"\rtask_rejected\x18\x15 \x01(\v2\x1b.velox.control.TaskRejectedH\x00R\ftaskRejected\x12<\n" +
	"\vtask_result\x18\x16 \x01(\v2\x19.velox.control.TaskResultH\x00R\n" +
	"taskResult\x12?\n" +
	"\fjob_progress\x18\x0f \x01(\v2\x1a.velox.control.JobProgressH\x00R\vjobProgress\x12<\n" +
	"\vcommand_ack\x18\x10 \x01(\v2\x19.velox.control.CommandAckH\x00R\n" +
	"commandAck\x129\n" +
	"\n" +
	"job_result\x18\x11 \x01(\v2\x18.velox.control.JobResultH\x00R\tjobResult\x12N\n" +
	"\x11artifact_uploaded\x18\x12 \x01(\v2\x1f.velox.control.ArtifactUploadedH\x00R\x10artifactUploaded\x122\n" +
	"\agoodbye\x18\x13 \x01(\v2\x16.velox.control.GoodbyeH\x00R\agoodbyeB\x05\n" +
	"\x03msg\"\xb3\x02\n" +
	"\x05Hello\x12\x1f\n" +
	"\vworker_name\x18\x01 \x01(\tR\n" +
	"workerName\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12%\n" +
	"\x0ebundle_version\x18\x04 \x01(\tR\rbundleVersion\x12\x1f\n" +
	"\vbundle_hash\x18\x05 \x01(\tR\n" +
	"bundleHash\x12%\n" +
	"\x0eengine_version\x18\x06 \x01(\tR\rengineVersion\x12'\n" +
	"\x0fcredential_hash\x18\a \x01(\tR\x0ecredentialHash\x12;\n" +
	"\fcapabilities\x18\b \x01(\v2\x17.google.protobuf.StructR\fcapabilities\"\xea\x03\n" +
	"\tHeartbeat\x12\x1f\n" +
	"\vworker_name\x18\x01 \x01(\tR\n" +
	"workerName\x12#\n" +
	"\rworker_status\x18\x02 \x01(\tR\fworkerStatus\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1f\n" +
	"\vcurrent_job\x18\x04 \x01(\tR\n" +
	"currentJob\x12!\n" +
	"\fcode_version\x18\x05 \x01(\tR\vcodeVersion\x12%\n" +
	"\x0ebundle_version\x18\x06 \x01(\tR\rbundleVersion\x12\x1f\n" +
	"\vbundle_hash\x18\a \x01(\tR\n" +
	"bundleHash\x12)\n" +
	"\x10protocol_version\x18\b \x01(\tR\x0fprotocolVersion\x12%\n" +
	"\x0eengine_version\x18\t \x01(\tR\rengineVersion\x12%\n" +
	"\x0ejobs_completed\x18\n" +
	" \x01(\x03R\rjobsCompleted\x12\x1f\n" +
	"\vjobs_failed\x18\v \x01(\x03R\n" +
	"jobsFailed\x12*\n" +
	"\x11active_jobs_count\x18\f \x01(\x05R\x0factiveJobsCount\x12-\n" +
	"\x05extra\x18\r \x01(\v2\x17.google.protobuf.StructR\x05extra\"\xa0\x01\n" +
	"\fLeaseRenewal\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x18\n" +
	"\aattempt\x18\x03 \x01(\x05R\aattempt\x12D\n" +
	"\x10lease_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\"]\n" +
	"\vJobAccepted\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1c\n" +
	"\n" +
	"job_run_id\x18\x02 \x01(\tR\bjobRunId\x12\x19\n" +
	"\blease_id\x18\x03 \x01(\tR\aleaseId\"<\n" +
	"\vJobRejected\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x9e\x01\n" +
	"\vJobProgress\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05stage\x18\x02 \x01(\tR\x05stage\x12)\n" +
	"\x10progress_percent\x18\x03 \x01(\x05R\x0fprogressPercent\x12\x14\n" +
	"\x05scene\x18\x04 \x01(\x05R\x05scene\x12!\n" +
	"\ftotal_scenes\x18\x05 \x01(\x05R\vtotalScenes\"[\n" +
	"\n" +
	"CommandAck\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xdd\x01\n" +
	"\tJobResult\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1c\n" +
	"\n" +
	"job_run_id\x18\x02 \x01(\tR\bjobRunId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"start_time\x18\x05 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x06 \x01(\tR\aendTime\x12\x19\n" +
	"\blease_id\x18\a \x01(\tR\aleaseId\x12\x18\n" +
	"\aattempt\x18\b \x01(\x05R\aattempt\"\xcc\x03\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12!\n" +
	"\ferror_detail\x18\x06 \x01(\tR\verrorDetail\x121\n" +
	"\ametrics\x18\a \x01(\v2\x17.google.protobuf.StructR\ametrics\x12?\n" +
	"\rphase_markers\x18\b \x03(\v2\x1a.velox.control.PhaseMarkerR\fphaseMarkers\x12\x1f\n" +
	"\vexecutor_id\x18\t \x01(\tR\n" +
	"executorId\x12!\n" +
	"\fexecutor_key\x18\n" +
	" \x01(\tR\vexecutorKey\x12B\n" +
	"\x10output_artifacts\x18\v \x03(\v2\x17.google.protobuf.StructR\x0foutputArtifacts\x12\x19\n" +
	"\blease_id\x18\f \x01(\tR\aleaseId\"\xc9\x01\n" +
	"\vPhaseMarker\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12=\n" +
	"\fcompleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05notes\x18\x05 \x01(\tR\x05notes\"\xf3\x02\n" +
	"\x10ArtifactUploaded\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12#\n" +
	"\rartifact_type\x18\x03 \x01(\tR\fartifactType\x12#\n" +
	"\rartifact_path\x18\x04 \x01(\tR\fartifactPath\x12#\n" +
	"\rartifact_size\x18\x05 \x01(\x03R\fartifactSize\x12#\n" +
	"\rupload_status\x18\x06 \x01(\tR\fuploadStatus\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x1b\n" +
	"\tupload_id\x18\b \x01(\tR\buploadId\x12\x19\n" +
	"\blease_id\x18\t \x01(\tR\aleaseId\x12\x18\n" +
	"\aattempt\x18\n" +
	" \x01(\x05R\aattempt\x12+\n" +
	"\x11expected_revision\x18\v \x01(\x05R\x10expectedRevision\"\t\n" +
	"\aGoodbye\"\xb8\a\n" +
	"\x16MasterToWorkerEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12'\n" +
	"\x0fsequence_number\x18\x04 \x01(\x03R\x0esequenceNumber\x123\n" +
	"\asent_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12)\n" +
	"\x10protocol_version\x18\x06 \x01(\tR\x0fprotocolVersion\x126\n" +
	"\thello_ack\x18\x14 \x01(\v2\x17.velox.control.HelloAckH\x00R\bhelloAck\x126\n" +
	"\tjob_offer\x18\x16 \x01(\v2\x17.velox.control.JobOfferH\x00R\bjobOffer\x129\n" +
	"\n" +
	"task_offer\x18\x1e \x01(\v2\x18.velox.control.TaskOfferH\x00R\ttaskOffer\x12L\n" +
	"\x11job_lease_granted\x18\x17 \x01(\v2\x1e.velox.control.JobLeaseGrantedH\x00R\x0fjobLeaseGranted\x12O\n" +
	"\x12task_lease_granted\x18\x1f \x01(\v2\x1f.velox.control.TaskLeaseGrantedH\x00R\x10taskLeaseGranted\x122\n" +
	"\acommand\x18\x18 \x01(\v2\x16.velox.control.CommandH\x00R\acommand\x129\n" +
	"\n" +
	"cancel_job\x18\x19 \x01(\v2\x18.velox.control.CancelJobH\x00R\tcancelJob\x12,\n" +
	"\x05drain\x18\x1a \x01(\v2\x14.velox.control.DrainH\x00R\x05drain\x12W\n" +
	"\x14configuration_update\x18\x1b \x01(\v2\".velox.control.ConfigurationUpdateH\x00R\x13configurationUpdate\x12B\n" +
	"\rlease_revoked\x18\x1c \x01(\v2\x1b.velox.control.LeaseRevokedH\x00R\fleaseRevoked\x12)\n" +
	"\x04ping\x18\x1d \x01(\v2\x13.velox.control.PingH\x00R\x04pingB\x05\n" +
	"\x03msgJ\x04\b\x15\x10\x16\"\n" +
	"\n" +
	"\bHelloAck\"\xe1\x02\n" +
	"\bJobOffer\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"video_name\x18\x03 \x01(\tR\tvideoName\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x19\n" +
	"\blease_id\x18\x05 \x01(\tR\aleaseId\x12=\n" +
	"\flease_expiry\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vleaseExpiry\x12\x18\n" +
	"\aattempt\x18\a \x01(\x05R\aattempt\x12\x1f\n" +
	"\vmax_retries\x18\b \x01(\x05R\n" +
	"maxRetries\x128\n" +
	"\vjob_payload\x18\t \x01(\v2\x17.google.protobuf.StructR\n" +
	"jobPayload\"\xe0\x03\n" +
	"\tTaskOffer\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12\x1f\n" +
	"\vexecutor_id\x18\x04 \x01(\tR\n" +
	"executorId\x12)\n" +
	"\x10executor_version\x18\x05 \x01(\x05R\x0fexecutorVersion\x124\n" +
	"\ttask_spec\x18\x06 \x01(\v2\x17.google.protobuf.StructR\btaskSpec\x12\x19\n" +
	"\blease_id\x18\a \x01(\tR\aleaseId\x12A\n" +
	"\x0elease_deadline\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\rleaseDeadline\x12;\n" +
	"\frequirements\x18\t \x01(\v2\x17.google.protobuf.StructR\frequirements\x12@\n" +
	"\x0foutput_contract\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\x0eoutputContract\x12%\n" +
	"\x0eattempt_number\x18\v \x01(\x05R\rattemptNumber\"x\n" +
	"\fTaskAccepted\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12\x19\n" +
	"\blease_id\x18\x04 \x01(\tR\aleaseId\"?\n" +
	"\fTaskRejected\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"x\n" +
	"\x0fJobLeaseGranted\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x19\n" +
	"\blease_id\x18\x04 \x01(\tR\aleaseId\"|\n" +
	"\x10TaskLeaseGranted\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\blease_id\x18\x02 \x01(\tR\aleaseId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x03 \x01(\tR\tattemptId\x12\x15\n" +
	"\x06job_id\x18\x04 \x01(\tR\x05jobId\"\xad\x01\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12/\n" +
	"\x06params\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06params\"\"\n" +
	"\tCancelJob\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x1f\n" +
	"\x05Drain\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"T\n" +
	"\x13ConfigurationUpdate\x12=\n" +
	"\rconfiguration\x18\x01 \x01(\v2\x17.google.protobuf.StructR\rconfiguration\"=\n" +
	"\fLeaseRevoked\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x06\n" +
	"\x04Ping2k\n" +
	"\rWorkerControl\x12Z\n" +
	"\x06Stream\x12%.velox.control.WorkerToMasterEnvelope\x1a%.velox.control.MasterToWorkerEnvelope(\x010\x01B\"Z velox-shared/controltransport/pbb\x06proto3"

var (
	file_velox_control_worker_control_proto_rawDescOnce sync.Once
	file_velox_control_worker_control_proto_rawDescData []byte
)

func file_velox_control_worker_control_proto_rawDescGZIP() []byte {
	file_velox_control_worker_control_proto_rawDescOnce.Do(func() {
		file_velox_control_worker_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_velox_control_worker_control_proto_rawDesc), len(file_velox_control_worker_control_proto_rawDesc)))
	})
	return file_velox_control_worker_control_proto_rawDescData
}

var file_velox_control_worker_control_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_velox_control_worker_control_proto_goTypes = []any{
	(*WorkerToMasterEnvelope)(nil), // 0: velox.control.WorkerToMasterEnvelope
	(*Hello)(nil),                  // 1: velox.control.Hello
	(*Heartbeat)(nil),              // 2: velox.control.Heartbeat
	(*LeaseRenewal)(nil),           // 3: velox.control.LeaseRenewal
	(*JobAccepted)(nil),            // 4: velox.control.JobAccepted
	(*JobRejected)(nil),            // 5: velox.control.JobRejected
	(*JobProgress)(nil),            // 6: velox.control.JobProgress
	(*CommandAck)(nil),             // 7: velox.control.CommandAck
	(*JobResult)(nil),              // 8: velox.control.JobResult
	(*TaskResult)(nil),             // 9: velox.control.TaskResult
	(*PhaseMarker)(nil),            // 10: velox.control.PhaseMarker
	(*ArtifactUploaded)(nil),       // 11: velox.control.ArtifactUploaded
	(*Goodbye)(nil),                // 12: velox.control.Goodbye
	(*MasterToWorkerEnvelope)(nil), // 13: velox.control.MasterToWorkerEnvelope
	(*HelloAck)(nil),               // 14: velox.control.HelloAck
	(*JobOffer)(nil),               // 15: velox.control.JobOffer
	(*TaskOffer)(nil),              // 16: velox.control.TaskOffer
	(*TaskAccepted)(nil),           // 17: velox.control.TaskAccepted
	(*TaskRejected)(nil),           // 18: velox.control.TaskRejected
	(*JobLeaseGranted)(nil),        // 19: velox.control.JobLeaseGranted
	(*TaskLeaseGranted)(nil),       // 20: velox.control.TaskLeaseGranted
	(*Command)(nil),                // 21: velox.control.Command
	(*CancelJob)(nil),              // 22: velox.control.CancelJob
	(*Drain)(nil),                  // 23: velox.control.Drain
	(*ConfigurationUpdate)(nil),    // 24: velox.control.ConfigurationUpdate
	(*LeaseRevoked)(nil),           // 25: velox.control.LeaseRevoked
	(*Ping)(nil),                   // 26: velox.control.Ping
	(*timestamppb.Timestamp)(nil),  // 27: google.protobuf.Timestamp
	(*structpb.Struct)(nil),        // 28: google.protobuf.Struct
}
var file_velox_control_worker_control_proto_depIdxs = []int32{
	27, // 0: velox.control.WorkerToMasterEnvelope.sent_at:type_name -> google.protobuf.Timestamp
	1,  // 1: velox.control.WorkerToMasterEnvelope.hello:type_name -> velox.control.Hello
	2,  // 2: velox.control.WorkerToMasterEnvelope.heartbeat:type_name -> velox.control.Heartbeat
	3,  // 3: velox.control.WorkerToMasterEnvelope.lease_renewal:type_name -> velox.control.LeaseRenewal
	4,  // 4: velox.control.WorkerToMasterEnvelope.job_accepted:type_name -> velox.control.JobAccepted
	5,  // 5: velox.control.WorkerToMasterEnvelope.job_rejected:type_name -> velox.control.JobRejected
	17, // 6: velox.control.WorkerToMasterEnvelope.task_accepted:type_name -> velox.control.TaskAccepted
	18, // 7: velox.control.WorkerToMasterEnvelope.task_rejected:type_name -> velox.control.TaskRejected
	9,  // 8: velox.control.WorkerToMasterEnvelope.task_result:type_name -> velox.control.TaskResult
	6,  // 9: velox.control.WorkerToMasterEnvelope.job_progress:type_name -> velox.control.JobProgress
	7,  // 10: velox.control.WorkerToMasterEnvelope.command_ack:type_name -> velox.control.CommandAck
	8,  // 11: velox.control.WorkerToMasterEnvelope.job_result:type_name -> velox.control.JobResult
	11, // 12: velox.control.WorkerToMasterEnvelope.artifact_uploaded:type_name -> velox.control.ArtifactUploaded
	12, // 13: velox.control.WorkerToMasterEnvelope.goodbye:type_name -> velox.control.Goodbye
	28, // 14: velox.control.Hello.capabilities:type_name -> google.protobuf.Struct
	28, // 15: velox.control.Heartbeat.extra:type_name -> google.protobuf.Struct
	27, // 16: velox.control.LeaseRenewal.lease_expires_at:type_name -> google.protobuf.Timestamp
	28, // 17: velox.control.TaskResult.metrics:type_name -> google.protobuf.Struct
	10, // 18: velox.control.TaskResult.phase_markers:type_name -> velox.control.PhaseMarker
	28, // 19: velox.control.TaskResult.output_artifacts:type_name -> google.protobuf.Struct
	27, // 20: velox.control.PhaseMarker.started_at:type_name -> google.protobuf.Timestamp
	27, // 21: velox.control.PhaseMarker.completed_at:type_name -> google.protobuf.Timestamp
	27, // 22: velox.control.MasterToWorkerEnvelope.sent_at:type_name -> google.protobuf.Timestamp
	14, // 23: velox.control.MasterToWorkerEnvelope.hello_ack:type_name -> velox.control.HelloAck
	15, // 24: velox.control.MasterToWorkerEnvelope.job_offer:type_name -> velox.control.JobOffer
	16, // 25: velox.control.MasterToWorkerEnvelope.task_offer:type_name -> velox.control.TaskOffer
	19, // 26: velox.control.MasterToWorkerEnvelope.job_lease_granted:type_name -> velox.control.JobLeaseGranted
	20, // 27: velox.control.MasterToWorkerEnvelope.task_lease_granted:type_name -> velox.control.TaskLeaseGranted
	21, // 28: velox.control.MasterToWorkerEnvelope.command:type_name -> velox.control.Command
	22, // 29: velox.control.MasterToWorkerEnvelope.cancel_job:type_name -> velox.control.CancelJob
	23, // 30: velox.control.MasterToWorkerEnvelope.drain:type_name -> velox.control.Drain
	24, // 31: velox.control.MasterToWorkerEnvelope.configuration_update:type_name -> velox.control.ConfigurationUpdate
	25, // 32: velox.control.MasterToWorkerEnvelope.lease_revoked:type_name -> velox.control.LeaseRevoked
	26, // 33: velox.control.MasterToWorkerEnvelope.ping:type_name -> velox.control.Ping
	27, // 34: velox.control.JobOffer.created_at:type_name -> google.protobuf.Timestamp
	27, // 35: velox.control.JobOffer.lease_expiry:type_name -> google.protobuf.Timestamp
	28, // 36: velox.control.JobOffer.job_payload:type_name -> google.protobuf.Struct
	28, // 37: velox.control.TaskOffer.task_spec:type_name -> google.protobuf.Struct
	27, // 38: velox.control.TaskOffer.lease_deadline:type_name -> google.protobuf.Timestamp
	28, // 39: velox.control.TaskOffer.requirements:type_name -> google.protobuf.Struct
	28, // 40: velox.control.TaskOffer.output_contract:type_name -> google.protobuf.Struct
	27, // 41: velox.control.Command.timestamp:type_name -> google.protobuf.Timestamp
	28, // 42: velox.control.Command.params:type_name -> google.protobuf.Struct
	28, // 43: velox.control.ConfigurationUpdate.configuration:type_name -> google.protobuf.Struct
	0,  // 44: velox.control.WorkerControl.Stream:input_type -> velox.control.WorkerToMasterEnvelope
	13, // 45: velox.control.WorkerControl.Stream:output_type -> velox.control.MasterToWorkerEnvelope
	45, // [45:46] is the sub-list for method output_type
	44, // [44:45] is the sub-list for method input_type
	44, // [44:44] is the sub-list for extension type_name
	44, // [44:44] is the sub-list for extension extendee
	0,  // [0:44] is the sub-list for field type_name
}

func init() { file_velox_control_worker_control_proto_init() }
func file_velox_control_worker_control_proto_init() {
	if File_velox_control_worker_control_proto != nil {
		return
	}
	file_velox_control_worker_control_proto_msgTypes[0].OneofWrappers = []any{
		(*WorkerToMasterEnvelope_Hello)(nil),
		(*WorkerToMasterEnvelope_Heartbeat)(nil),
		(*WorkerToMasterEnvelope_LeaseRenewal)(nil),
		(*WorkerToMasterEnvelope_JobAccepted)(nil),
		(*WorkerToMasterEnvelope_JobRejected)(nil),
		(*WorkerToMasterEnvelope_TaskAccepted)(nil),
		(*WorkerToMasterEnvelope_TaskRejected)(nil),
		(*WorkerToMasterEnvelope_TaskResult)(nil),
		(*WorkerToMasterEnvelope_JobProgress)(nil),
		(*WorkerToMasterEnvelope_CommandAck)(nil),
		(*WorkerToMasterEnvelope_JobResult)(nil),
		(*WorkerToMasterEnvelope_ArtifactUploaded)(nil),
		(*WorkerToMasterEnvelope_Goodbye)(nil),
	}
	file_velox_control_worker_control_proto_msgTypes[13].OneofWrappers = []any{
		(*MasterToWorkerEnvelope_HelloAck)(nil),
		(*MasterToWorkerEnvelope_JobOffer)(nil),
		(*MasterToWorkerEnvelope_TaskOffer)(nil),
		(*MasterToWorkerEnvelope_JobLeaseGranted)(nil),
		(*MasterToWorkerEnvelope_TaskLeaseGranted)(nil),
		(*MasterToWorkerEnvelope_Command)(nil),
		(*MasterToWorkerEnvelope_CancelJob)(nil),
		(*MasterToWorkerEnvelope_Drain)(nil),
		(*MasterToWorkerEnvelope_ConfigurationUpdate)(nil),
		(*MasterToWorkerEnvelope_LeaseRevoked)(nil),
		(*MasterToWorkerEnvelope_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_velox_control_worker_control_proto_rawDesc), len(file_velox_control_worker_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_velox_control_worker_control_proto_goTypes,
		DependencyIndexes: file_velox_control_worker_control_proto_depIdxs,
		MessageInfos:      file_velox_control_worker_control_proto_msgTypes,
	}.Build()
	File_velox_control_worker_control_proto = out.File
	file_velox_control_worker_control_proto_goTypes = nil
	file_velox_control_worker_control_proto_depIdxs = nil
}
