// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: velox/control/worker_events.proto

// Worker event messages for the Velox Worker-Control stream (split from
// worker_control.proto). Imported by worker_to_master.proto.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactUploaded struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	JobId            string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	ArtifactId       string                 `protobuf:"bytes,2,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ArtifactType     string                 `protobuf:"bytes,3,opt,name=artifact_type,json=artifactType,proto3" json:"artifact_type,omitempty"`
	ArtifactPath     string                 `protobuf:"bytes,4,opt,name=artifact_path,json=artifactPath,proto3" json:"artifact_path,omitempty"`
	ArtifactSize     int64                  `protobuf:"varint,5,opt,name=artifact_size,json=artifactSize,proto3" json:"artifact_size,omitempty"`
	UploadStatus     string                 `protobuf:"bytes,6,opt,name=upload_status,json=uploadStatus,proto3" json:"upload_status,omitempty"`
	Error            string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	UploadId         string                 `protobuf:"bytes,8,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	LeaseId          string                 `protobuf:"bytes,9,opt,name=lease_id,json=leaseId,proto3" json:"lease_id,omitempty"`
	Attempt          int32                  `protobuf:"varint,10,opt,name=attempt,proto3" json:"attempt,omitempty"`
	ExpectedRevision int32                  `protobuf:"varint,11,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	// Canonical attempt ID (UUID). Enables the master to stamp the
	// authoritative artifact_sha256 on the winning attempt row
	// (migration 148). Pre-v1 workers send empty; the master resolves
	// it from the tasks table when missing.
	AttemptId     string `protobuf:"bytes,12,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactUploaded) Reset() {
	*x = ArtifactUploaded{}
	mi := &file_velox_control_worker_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactUploaded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactUploaded) ProtoMessage() {}

func (x *ArtifactUploaded) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactUploaded.ProtoReflect.Descriptor instead.
func (*ArtifactUploaded) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_events_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactUploaded) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ArtifactUploaded) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactUploaded) GetArtifactType() string {
	if x != nil {
		return x.ArtifactType
	}
	return ""
}

func (x *ArtifactUploaded) GetArtifactPath() string {
	if x != nil {
		return x.ArtifactPath
	}
	return ""
}

func (x *ArtifactUploaded) GetArtifactSize() int64 {
	if x != nil {
		return x.ArtifactSize
	}
	return 0
}

func (x *ArtifactUploaded) GetUploadStatus() string {
	if x != nil {
		return x.UploadStatus
	}
	return ""
}

func (x *ArtifactUploaded) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ArtifactUploaded) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *ArtifactUploaded) GetLeaseId() string {
	if x != nil {
		return x.LeaseId
	}
	return ""
}

func (x *ArtifactUploaded) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ArtifactUploaded) GetExpectedRevision() int32 {
	if x != nil {
		return x.ExpectedRevision
	}
	return 0
}

func (x *ArtifactUploaded) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type Goodbye struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Goodbye) Reset() {
	*x = Goodbye{}
	mi := &file_velox_control_worker_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Goodbye) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Goodbye) ProtoMessage() {}

func (x *Goodbye) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Goodbye.ProtoReflect.Descriptor instead.
func (*Goodbye) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_events_proto_rawDescGZIP(), []int{1}
}

// AssetDownloadProgress is emitted by the worker's canonical
// DownloadManager checkpoint hook. It is a latest-state message, not an
// append-only byte event: the master upserts the worker/transfer row and
// replaces the job references for that physical transfer.
type AssetJobReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SceneIds      []string               `protobuf:"bytes,3,rep,name=scene_ids,json=sceneIds,proto3" json:"scene_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetJobReference) Reset() {
	*x = AssetJobReference{}
	mi := &file_velox_control_worker_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetJobReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetJobReference) ProtoMessage() {}

func (x *AssetJobReference) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetJobReference.ProtoReflect.Descriptor instead.
func (*AssetJobReference) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_events_proto_rawDescGZIP(), []int{2}
}

func (x *AssetJobReference) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AssetJobReference) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssetJobReference) GetSceneIds() []string {
	if x != nil {
		return x.SceneIds
	}
	return nil
}

type AssetDownloadProgress struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	WorkerId           string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TransferId         string                 `protobuf:"bytes,2,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	AssetKey           string                 `protobuf:"bytes,3,opt,name=asset_key,json=assetKey,proto3" json:"asset_key,omitempty"`
	AssetId            string                 `protobuf:"bytes,4,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	Role               string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	State              string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	BytesDownloaded    int64                  `protobuf:"varint,7,opt,name=bytes_downloaded,json=bytesDownloaded,proto3" json:"bytes_downloaded,omitempty"`
	BytesTotal         int64                  `protobuf:"varint,8,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	BytesPerSecond     float64                `protobuf:"fixed64,9,opt,name=bytes_per_second,json=bytesPerSecond,proto3" json:"bytes_per_second,omitempty"`
	EtaSeconds         int64                  `protobuf:"varint,10,opt,name=eta_seconds,json=etaSeconds,proto3" json:"eta_seconds,omitempty"`
	Attempt            int32                  `protobuf:"varint,11,opt,name=attempt,proto3" json:"attempt,omitempty"`
	SharedWaiters      int32                  `protobuf:"varint,12,opt,name=shared_waiters,json=sharedWaiters,proto3" json:"shared_waiters,omitempty"`
	CacheHit           bool                   `protobuf:"varint,13,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	QueuedAtUnixMs     int64                  `protobuf:"varint,14,opt,name=queued_at_unix_ms,json=queuedAtUnixMs,proto3" json:"queued_at_unix_ms,omitempty"`
	StartedAtUnixMs    int64                  `protobuf:"varint,15,opt,name=started_at_unix_ms,json=startedAtUnixMs,proto3" json:"started_at_unix_ms,omitempty"`
	UpdatedAtUnixMs    int64                  `protobuf:"varint,16,opt,name=updated_at_unix_ms,json=updatedAtUnixMs,proto3" json:"updated_at_unix_ms,omitempty"`
	CompletedAtUnixMs  int64                  `protobuf:"varint,17,opt,name=completed_at_unix_ms,json=completedAtUnixMs,proto3" json:"completed_at_unix_ms,omitempty"`
	JobIds             []string               `protobuf:"bytes,18,rep,name=job_ids,json=jobIds,proto3" json:"job_ids,omitempty"`
	TaskId             string                 `protobuf:"bytes,19,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SceneIds           []string               `protobuf:"bytes,20,rep,name=scene_ids,json=sceneIds,proto3" json:"scene_ids,omitempty"`
	MimeType           string                 `protobuf:"bytes,21,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Sha256             string                 `protobuf:"bytes,22,opt,name=sha256,proto3" json:"sha256,omitempty"`
	ErrorCode          string                 `protobuf:"bytes,23,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorDetail        string                 `protobuf:"bytes,24,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	JobRefs            []*AssetJobReference   `protobuf:"bytes,25,rep,name=job_refs,json=jobRefs,proto3" json:"job_refs,omitempty"`
	CheckpointSequence int64                  `protobuf:"varint,26,opt,name=checkpoint_sequence,json=checkpointSequence,proto3" json:"checkpoint_sequence,omitempty"`
	TransferGeneration int64                  `protobuf:"varint,27,opt,name=transfer_generation,json=transferGeneration,proto3" json:"transfer_generation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AssetDownloadProgress) Reset() {
	*x = AssetDownloadProgress{}
	mi := &file_velox_control_worker_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetDownloadProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetDownloadProgress) ProtoMessage() {}

func (x *AssetDownloadProgress) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetDownloadProgress.ProtoReflect.Descriptor instead.
func (*AssetDownloadProgress) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_events_proto_rawDescGZIP(), []int{3}
}

func (x *AssetDownloadProgress) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *AssetDownloadProgress) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *AssetDownloadProgress) GetAssetKey() string {
	if x != nil {
		return x.AssetKey
	}
	return ""
}

func (x *AssetDownloadProgress) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *AssetDownloadProgress) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AssetDownloadProgress) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AssetDownloadProgress) GetBytesDownloaded() int64 {
	if x != nil {
		return x.BytesDownloaded
	}
	return 0
}

func (x *AssetDownloadProgress) GetBytesTotal() int64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

func (x *AssetDownloadProgress) GetBytesPerSecond() float64 {
	if x != nil {
		return x.BytesPerSecond
	}
	return 0
}

func (x *AssetDownloadProgress) GetEtaSeconds() int64 {
	if x != nil {
		return x.EtaSeconds
	}
	return 0
}

func (x *AssetDownloadProgress) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *AssetDownloadProgress) GetSharedWaiters() int32 {
	if x != nil {
		return x.SharedWaiters
	}
	return 0
}

func (x *AssetDownloadProgress) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *AssetDownloadProgress) GetQueuedAtUnixMs() int64 {
	if x != nil {
		return x.QueuedAtUnixMs
	}
	return 0
}

func (x *AssetDownloadProgress) GetStartedAtUnixMs() int64 {
	if x != nil {
		return x.StartedAtUnixMs
	}
	return 0
}

func (x *AssetDownloadProgress) GetUpdatedAtUnixMs() int64 {
	if x != nil {
		return x.UpdatedAtUnixMs
	}
	return 0
}

func (x *AssetDownloadProgress) GetCompletedAtUnixMs() int64 {
	if x != nil {
		return x.CompletedAtUnixMs
	}
	return 0
}

func (x *AssetDownloadProgress) GetJobIds() []string {
	if x != nil {
		return x.JobIds
	}
	return nil
}

func (x *AssetDownloadProgress) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AssetDownloadProgress) GetSceneIds() []string {
	if x != nil {
		return x.SceneIds
	}
	return nil
}

func (x *AssetDownloadProgress) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *AssetDownloadProgress) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *AssetDownloadProgress) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *AssetDownloadProgress) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

func (x *AssetDownloadProgress) GetJobRefs() []*AssetJobReference {
	if x != nil {
		return x.JobRefs
	}
	return nil
}

func (x *AssetDownloadProgress) GetCheckpointSequence() int64 {
	if x != nil {
		return x.CheckpointSequence
	}
	return 0
}

func (x *AssetDownloadProgress) GetTransferGeneration() int64 {
	if x != nil {
		return x.TransferGeneration
	}
	return 0
}

// PrefetchLifecycleEvent is a lightweight worker-to-master event for
// prefetch lifecycle milestones. The Master persists these into the
// job_events journal so `fleetctl job inspect` shows the full prefetch
// timeline (future_plan_received, future_plan_applied, prefetch_prepared).
// The Master-side events (reservation_created, future_plan_sent) are
// logged directly by the Master during refreshFutureAssetPlan.
type PrefetchLifecycleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "future_plan_received" | "future_plan_applied" | "prefetch_prepared"
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,4,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	PlanId        string                 `protobuf:"bytes,5,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	PlanVersion   int64                  `protobuf:"varint,6,opt,name=plan_version,json=planVersion,proto3" json:"plan_version,omitempty"`
	ReservationId string                 `protobuf:"bytes,7,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Distance      int32                  `protobuf:"varint,8,opt,name=distance,proto3" json:"distance,omitempty"`
	// For prefetch_prepared: asset-level details.
	AssetId        string `protobuf:"bytes,9,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	AssetSha256    string `protobuf:"bytes,10,opt,name=asset_sha256,json=assetSha256,proto3" json:"asset_sha256,omitempty"`
	AssetSizeBytes int64  `protobuf:"varint,11,opt,name=asset_size_bytes,json=assetSizeBytes,proto3" json:"asset_size_bytes,omitempty"`
	LocalPath      string `protobuf:"bytes,12,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	// ISO-8601 timestamp of when this event occurred on the worker.
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// Task revision fence for reservation-scoped PREPARED evidence.
	TaskRevision int32 `protobuf:"varint,14,opt,name=task_revision,json=taskRevision,proto3" json:"task_revision,omitempty"`
	// Stable failure detail for prejob_prepare_failed events.
	ErrorReason string `protobuf:"bytes,15,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	// Canonical timing/provenance fields for asset-level prefetch evidence.
	DownloadStartedAt   *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=download_started_at,json=downloadStartedAt,proto3" json:"download_started_at,omitempty"`
	AssetReadyAt        *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=asset_ready_at,json=assetReadyAt,proto3" json:"asset_ready_at,omitempty"`
	JobStartedAt        *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=job_started_at,json=jobStartedAt,proto3" json:"job_started_at,omitempty"`
	PrefetchReadyLeadMs int64                  `protobuf:"varint,19,opt,name=prefetch_ready_lead_ms,json=prefetchReadyLeadMs,proto3" json:"prefetch_ready_lead_ms,omitempty"`
	CacheHit            bool                   `protobuf:"varint,20,opt,name=cache_hit,json=cacheHit,proto3" json:"cache_hit,omitempty"`
	Origin              string                 `protobuf:"bytes,21,opt,name=origin,proto3" json:"origin,omitempty"` // prefetch | runtime_download | warm_cache
	AssetKey            string                 `protobuf:"bytes,22,opt,name=asset_key,json=assetKey,proto3" json:"asset_key,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PrefetchLifecycleEvent) Reset() {
	*x = PrefetchLifecycleEvent{}
	mi := &file_velox_control_worker_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrefetchLifecycleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrefetchLifecycleEvent) ProtoMessage() {}

func (x *PrefetchLifecycleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrefetchLifecycleEvent.ProtoReflect.Descriptor instead.
func (*PrefetchLifecycleEvent) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_events_proto_rawDescGZIP(), []int{4}
}

func (x *PrefetchLifecycleEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PrefetchLifecycleEvent) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *PrefetchLifecycleEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *PrefetchLifecycleEvent) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *PrefetchLifecycleEvent) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *PrefetchLifecycleEvent) GetPlanVersion() int64 {
	if x != nil {
		return x.PlanVersion
	}
	return 0
}

func (x *PrefetchLifecycleEvent) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *PrefetchLifecycleEvent) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *PrefetchLifecycleEvent) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *PrefetchLifecycleEvent) GetAssetSha256() string {
	if x != nil {
		return x.AssetSha256
	}
	return ""
}

func (x *PrefetchLifecycleEvent) GetAssetSizeBytes() int64 {
	if x != nil {
		return x.AssetSizeBytes
	}
	return 0
}

func (x *PrefetchLifecycleEvent) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *PrefetchLifecycleEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *PrefetchLifecycleEvent) GetTaskRevision() int32 {
	if x != nil {
		return x.TaskRevision
	}
	return 0
}

func (x *PrefetchLifecycleEvent) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

func (x *PrefetchLifecycleEvent) GetDownloadStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DownloadStartedAt
	}
	return nil
}

func (x *PrefetchLifecycleEvent) GetAssetReadyAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AssetReadyAt
	}
	return nil
}

func (x *PrefetchLifecycleEvent) GetJobStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.JobStartedAt
	}
	return nil
}

func (x *PrefetchLifecycleEvent) GetPrefetchReadyLeadMs() int64 {
	if x != nil {
		return x.PrefetchReadyLeadMs
	}
	return 0
}

func (x *PrefetchLifecycleEvent) GetCacheHit() bool {
	if x != nil {
		return x.CacheHit
	}
	return false
}

func (x *PrefetchLifecycleEvent) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *PrefetchLifecycleEvent) GetAssetKey() string {
	if x != nil {
		return x.AssetKey
	}
	return ""
}

var File_velox_control_worker_events_proto protoreflect.FileDescriptor

const file_velox_control_worker_events_proto_rawDesc = "" +
	"\n" +
	"!velox/control/worker_events.proto\x12\rvelox.control\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x03\n" +
	"\x10ArtifactUploaded\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vartifact_id\x18\x02 \x01(\tR\n" +
	"artifactId\x12#\n" +
	"\rartifact_type\x18\x03 \x01(\tR\fartifactType\x12#\n" +
	"\rartifact_path\x18\x04 \x01(\tR\fartifactPath\x12#\n" +
	"\rartifact_size\x18\x05 \x01(\x03R\fartifactSize\x12#\n" +
	"\rupload_status\x18\x06 \x01(\tR\fuploadStatus\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12\x1b\n" +
	"\tupload_id\x18\b \x01(\tR\buploadId\x12\x19\n" +
	"\blease_id\x18\t \x01(\tR\aleaseId\x12\x18\n" +
	"\aattempt\x18\n" +
	" \x01(\x05R\aattempt\x12+\n" +
	"\x11expected_revision\x18\v \x01(\x05R\x10expectedRevision\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\f \x01(\tR\tattemptId\"\t\n" +
	"\aGoodbye\"`\n" +
	"\x11AssetJobReference\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tscene_ids\x18\x03 \x03(\tR\bsceneIds\"\xc7\a\n" +
	"\x15AssetDownloadProgress\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1f\n" +
	"\vtransfer_id\x18\x02 \x01(\tR\n" +
	"transferId\x12\x1b\n" +
	"\tasset_key\x18\x03 \x01(\tR\bassetKey\x12\x19\n" +
	"\basset_id\x18\x04 \x01(\tR\aassetId\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12)\n" +
	"\x10bytes_downloaded\x18\a \x01(\x03R\x0fbytesDownloaded\x12\x1f\n" +
	"\vbytes_total\x18\b \x01(\x03R\n" +
	"bytesTotal\x12(\n" +
	"\x10bytes_per_second\x18\t \x01(\x01R\x0ebytesPerSecond\x12\x1f\n" +
	"\veta_seconds\x18\n" +
	" \x01(\x03R\n" +
	"etaSeconds\x12\x18\n" +
	"\aattempt\x18\v \x01(\x05R\aattempt\x12%\n" +
	"\x0eshared_waiters\x18\f \x01(\x05R\rsharedWaiters\x12\x1b\n" +
	"\tcache_hit\x18\r \x01(\bR\bcacheHit\x12)\n" +
	"\x11queued_at_unix_ms\x18\x0e \x01(\x03R\x0equeuedAtUnixMs\x12+\n" +
	"\x12started_at_unix_ms\x18\x0f \x01(\x03R\x0fstartedAtUnixMs\x12+\n" +
	"\x12updated_at_unix_ms\x18\x10 \x01(\x03R\x0fupdatedAtUnixMs\x12/\n" +
	"\x14completed_at_unix_ms\x18\x11 \x01(\x03R\x11completedAtUnixMs\x12\x17\n" +
	"\ajob_ids\x18\x12 \x03(\tR\x06jobIds\x12\x17\n" +
	"\atask_id\x18\x13 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tscene_ids\x18\x14 \x03(\tR\bsceneIds\x12\x1b\n" +
	"\tmime_type\x18\x15 \x01(\tR\bmimeType\x12\x16\n" +
	"\x06sha256\x18\x16 \x01(\tR\x06sha256\x12\x1d\n" +
	"\n" +
	"error_code\x18\x17 \x01(\tR\terrorCode\x12!\n" +
	"\ferror_detail\x18\x18 \x01(\tR\verrorDetail\x12;\n" +
	"\bjob_refs\x18\x19 \x03(\v2 .velox.control.AssetJobReferenceR\ajobRefs\x12/\n" +
	"\x13checkpoint_sequence\x18\x1a \x01(\x03R\x12checkpointSequence\x12/\n" +
	"\x13transfer_generation\x18\x1b \x01(\x03R\x12transferGeneration\"\xe6\x06\n" +
	"\x16PrefetchLifecycleEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tworker_id\x18\x04 \x01(\tR\bworkerId\x12\x17\n" +
	"\aplan_id\x18\x05 \x01(\tR\x06planId\x12!\n" +
	"\fplan_version\x18\x06 \x01(\x03R\vplanVersion\x12%\n" +
	"\x0ereservation_id\x18\a \x01(\tR\rreservationId\x12\x1a\n" +
	"\bdistance\x18\b \x01(\x05R\bdistance\x12\x19\n" +
	"\basset_id\x18\t \x01(\tR\aassetId\x12!\n" +
	"\fasset_sha256\x18\n" +
	" \x01(\tR\vassetSha256\x12(\n" +
	"\x10asset_size_bytes\x18\v \x01(\x03R\x0eassetSizeBytes\x12\x1d\n" +
	"\n" +
	"local_path\x18\f \x01(\tR\tlocalPath\x12;\n" +
	"\voccurred_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12#\n" +
	"\rtask_revision\x18\x0e \x01(\x05R\ftaskRevision\x12!\n" +
	"\ferror_reason\x18\x0f \x01(\tR\verrorReason\x12J\n" +
	"\x13download_started_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\x11downloadStartedAt\x12@\n" +
	"\x0easset_ready_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\fassetReadyAt\x12@\n" +
	"\x0ejob_started_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\fjobStartedAt\x123\n" +
	"\x16prefetch_ready_lead_ms\x18\x13 \x01(\x03R\x13prefetchReadyLeadMs\x12\x1b\n" +
	"\tcache_hit\x18\x14 \x01(\bR\bcacheHit\x12\x16\n" +
	"\x06origin\x18\x15 \x01(\tR\x06origin\x12\x1b\n" +
	"\tasset_key\x18\x16 \x01(\tR\bassetKeyB\"Z velox-shared/controltransport/pbb\x06proto3"

var (
	file_velox_control_worker_events_proto_rawDescOnce sync.Once
	file_velox_control_worker_events_proto_rawDescData []byte
)

func file_velox_control_worker_events_proto_rawDescGZIP() []byte {
	file_velox_control_worker_events_proto_rawDescOnce.Do(func() {
		file_velox_control_worker_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_velox_control_worker_events_proto_rawDesc), len(file_velox_control_worker_events_proto_rawDesc)))
	})
	return file_velox_control_worker_events_proto_rawDescData
}

var file_velox_control_worker_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_velox_control_worker_events_proto_goTypes = []any{
	(*ArtifactUploaded)(nil),       // 0: velox.control.ArtifactUploaded
	(*Goodbye)(nil),                // 1: velox.control.Goodbye
	(*AssetJobReference)(nil),      // 2: velox.control.AssetJobReference
	(*AssetDownloadProgress)(nil),  // 3: velox.control.AssetDownloadProgress
	(*PrefetchLifecycleEvent)(nil), // 4: velox.control.PrefetchLifecycleEvent
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_velox_control_worker_events_proto_depIdxs = []int32{
	2, // 0: velox.control.AssetDownloadProgress.job_refs:type_name -> velox.control.AssetJobReference
	5, // 1: velox.control.PrefetchLifecycleEvent.occurred_at:type_name -> google.protobuf.Timestamp
	5, // 2: velox.control.PrefetchLifecycleEvent.download_started_at:type_name -> google.protobuf.Timestamp
	5, // 3: velox.control.PrefetchLifecycleEvent.asset_ready_at:type_name -> google.protobuf.Timestamp
	5, // 4: velox.control.PrefetchLifecycleEvent.job_started_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_velox_control_worker_events_proto_init() }
func file_velox_control_worker_events_proto_init() {
	if File_velox_control_worker_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_velox_control_worker_events_proto_rawDesc), len(file_velox_control_worker_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_velox_control_worker_events_proto_goTypes,
		DependencyIndexes: file_velox_control_worker_events_proto_depIdxs,
		MessageInfos:      file_velox_control_worker_events_proto_msgTypes,
	}.Build()
	File_velox_control_worker_events_proto = out.File
	file_velox_control_worker_events_proto_goTypes = nil
	file_velox_control_worker_events_proto_depIdxs = nil
}
