// Code generated by shared/contract/cmd/contractgen; DO NOT EDIT.
// Source: shared/contract/schema/*.schema.json
package payloadfield

// job_payload_v2.schema.json
const AudioLanguageForSRT = "audio_language_for_srt"
const ChannelID = "channel_id"
const CompiledRenderPlanJSON = "compiled_render_plan_json"
const CompiledRenderPlanSHA256 = "compiled_render_plan_sha256"
const ContractVersion = "contract_version"
const CorrelationID = "correlation_id"
const CreatedAt = "created_at"
const DeliveryPlan = "delivery_plan"
const DriveOutputFolder = "drive_output_folder"
const Effect = "effect"
const ImageSourceMap = "image_source_map"
const Items = "items"
const JobFingerprint = "job_fingerprint"
const JobID = "job_id"
const JobRunID = "job_run_id"
const JobType = "job_type"
const Layers = "layers"
const ManifestRef = "manifest_ref"
const ManifestSHA256 = "manifest_sha256"
const Orientation = "orientation"
const OutputPath = "output_path"
const OutputVideoID = "output_video_id"
const PayloadContractVersion = "payload_contract_version"
const Priority = "priority"
const RenderManifest = "render_manifest"
const RenderPlanJSON = "render_plan_json"
const RenderPlanSHA256 = "render_plan_sha256"
const SceneCount = "scene_count"
const SceneDurationSecs = "scene_duration_secs"
const SceneImagePaths = "scene_image_paths"
const Scenes = "scenes"
const ScenesJSON = "scenes_json"
const ScriptText = "script_text"
const Source = "source"
const Status = "status"
const SubmittedVia = "submitted_via"
const TemplateID = "template_id"
const TemplateVersion = "template_version"
const TimeoutSecs = "timeout_secs"
const TotalDurationSecs = "total_duration_secs"
const UpdatedAt = "updated_at"
const Version = "version"
const VideoMetadata = "video_metadata"
const VideoMode = "video_mode"
const VideoName = "video_name"
const VoiceoverCount = "voiceover_count"
const VoiceoverPaths = "voiceover_paths"

// JobPayloadV2Keys returns the canonical top-level key set in
// deterministic (sorted) order. It is a fresh slice on every call.
func JobPayloadV2Keys() []string {
	return []string{
		AudioLanguageForSRT,
		ChannelID,
		CompiledRenderPlanJSON,
		CompiledRenderPlanSHA256,
		ContractVersion,
		CorrelationID,
		CreatedAt,
		DeliveryPlan,
		DriveOutputFolder,
		Effect,
		ImageSourceMap,
		Items,
		JobFingerprint,
		JobID,
		JobRunID,
		JobType,
		Layers,
		ManifestRef,
		ManifestSHA256,
		Orientation,
		OutputPath,
		OutputVideoID,
		PayloadContractVersion,
		Priority,
		RenderManifest,
		RenderPlanJSON,
		RenderPlanSHA256,
		SceneCount,
		SceneDurationSecs,
		SceneImagePaths,
		Scenes,
		ScenesJSON,
		ScriptText,
		Source,
		Status,
		SubmittedVia,
		TemplateID,
		TemplateVersion,
		TimeoutSecs,
		TotalDurationSecs,
		UpdatedAt,
		Version,
		VideoMetadata,
		VideoMode,
		VideoName,
		VoiceoverCount,
		VoiceoverPaths,
	}
}

// render_manifest_v1.schema.json
const RenderManifestAssets = "assets"
const RenderManifestAssetsDurationMS = "duration_ms"
const RenderManifestAssetsFormat = "format"
const RenderManifestAssetsID = "id"
const RenderManifestAssetsKind = "kind"
const RenderManifestAssetsSHA256 = "sha256"
const RenderManifestAssetsSizeBytes = "size_bytes"
const RenderManifestAssetsURI = "uri"
const RenderManifestCanvas = "canvas"
const RenderManifestCanvasFPSDen = "fps_den"
const RenderManifestCanvasFPSNum = "fps_num"
const RenderManifestCanvasHeight = "height"
const RenderManifestCanvasPixelFormat = "pixel_format"
const RenderManifestCanvasWidth = "width"
const RenderManifestLayers = "layers"
const RenderManifestLayersAnimation = "animation"
const RenderManifestLayersAsset = "asset"
const RenderManifestLayersDurationSeconds = "duration_seconds"
const RenderManifestLayersFont = "font"
const RenderManifestLayersFontSize = "font_size"
const RenderManifestLayersID = "id"
const RenderManifestLayersPosition = "position"
const RenderManifestLayersPreset = "preset"
const RenderManifestLayersRole = "role"
const RenderManifestLayersSource = "source"
const RenderManifestLayersStartSeconds = "start_seconds"
const RenderManifestLayersText = "text"
const RenderManifestLayersType = "type"
const RenderManifestOutput = "output"
const RenderManifestOutputAudioChannels = "audio_channels"
const RenderManifestOutputAudioCodec = "audio_codec"
const RenderManifestOutputAudioSampleRate = "audio_sample_rate"
const RenderManifestOutputContainer = "container"
const RenderManifestOutputVideoCodec = "video_codec"
const RenderManifestSchema = "schema"
const RenderManifestTracks = "tracks"
const RenderManifestTracksAssetID = "asset_id"
const RenderManifestTracksBurnIn = "burn_in"
const RenderManifestTracksEvents = "events"
const RenderManifestTracksEventsAssetID = "asset_id"
const RenderManifestTracksEventsDuckUnderVoiceover = "duck_under_voiceover"
const RenderManifestTracksEventsDurationMS = "duration_ms"
const RenderManifestTracksEventsFadeInMS = "fade_in_ms"
const RenderManifestTracksEventsFadeOutMS = "fade_out_ms"
const RenderManifestTracksEventsGainDB = "gain_db"
const RenderManifestTracksEventsSourceStartMS = "source_start_ms"
const RenderManifestTracksEventsTimelineStartMS = "timeline_start_ms"
const RenderManifestTracksID = "id"
const RenderManifestTracksKind = "kind"

// delivery_plan_v1.schema.json
const DeliveryPlanDestinationID = "destination_id"
const DeliveryPlanEnabled = "enabled"
const DeliveryPlanExternalDestinationID = "external_destination_id"
const DeliveryPlanMetadata = "metadata"
const DeliveryPlanPlatform = "platform"
const DeliveryPlanPriority = "priority"
const DeliveryPlanRetryBudget = "retry_budget"
