-- 045_add_job_required_resource_columns.sql
--
-- PR-04.5: Adds two dedicated columns to the jobs table that mirror
-- `request_json._requirements.resource_class` and
-- `request_json._requirements.temporal_mode`. We persist these on
-- columns so that:
--
--   * Future query-time filtering (ClaimNext / ListByStatus) can filter
--     by resource class without parsing the request_json blob.
--   * The cost-model eligibility layer (PR-04.4) reads Requirements off
--     the column without re-reading request_json.
--
-- Deterministic + Cacheable continue to live JSON-only inside
-- request_json because the rank layer (PR-04.6+) does not need
-- query-time filtering on those flags today, and the dedicated columns
-- would balloon the schema without ROI at this slice.
--
-- Mirroring (column ↔ JSON) is enforced at the repository Create layer
-- (see internal/store/sqlite_jobs_writer.go::CreateJob). The existing
-- pre-PR-04.5 rows have DEFAULT '' for both columns, which the
-- reconstruction path in toJobsJob folds into JobRequirements{} = the
-- permissive default (matches GetSchedulableWorkers behavior pre-PR-04.5).
--
-- SQLite >= 3.35.0 required for ALTER TABLE ADD COLUMN (with DEFAULT).
--
-- PLACEMENT / RENUMBERING NOTE: This file is a relocation of the
-- legacy migrations/039_add_job_required_resource_columns.sql. The
-- reason for moving onto the recursive `migrations/sqlite/` embed
-- track (served by migrations.SQLiteMigrationsFS()) is documented in
-- sqlite.go's NewSQLiteStoreFromHandle and runner.go's package doc:
-- the production boot path was switched from the legacy non-recursive
-- `migrationsFS` to SQLiteMigrationsFS() + "sqlite" so future
-- migrations on the SQLite track are picked up automatically.
--
-- Renumbered 039 → 045 because migrations/sqlite/039_tasks.sql already
-- occupies version 039 on this track (creating the canonical tasks
-- table for distributed rendering) and 040_task_specs.sql occupies v40
-- (task_specs DDL). 044_stub_dark_editor_projects.sql occupies v44.
-- Version 045 is the next free slot, and appending past all other
-- sqlite/ migrations keeps the version-order monotonic for new DBs.
--
-- PRODUCTION IDEMPOTENCY: any pre-Path-B production DB that already
-- applied the legacy root's 039_add_job_required_resource_columns.sql
-- has these columns on its jobs table. When that DB is next opened
-- through NewSQLiteStore (now reading from SQLiteMigrationsFS() +
-- "sqlite"), this 045 replays the same ALTER TABLE ADD COLUMN. The
-- runner's applyMigration (in migrations.go) detects "duplicate
-- column name: …" on ADD COLUMN statements and treats it as a no-op,
-- so the surrounding tx continues and records v045 in
-- schema_migrations. End-state and post-migration checksum
-- verification are unchanged for both fresh DBs and pre-Path-B
-- production DBs; the runner handles both paths identically.

ALTER TABLE jobs ADD COLUMN job_required_resource_class TEXT NOT NULL DEFAULT '';

ALTER TABLE jobs ADD COLUMN job_required_temporal_mode  TEXT NOT NULL DEFAULT '';
