-- migrations/sqlite/064_task_output_declarations_required.sql
--
-- Artifact Commit Protocol (Phase 1.5 follow-up) — add the
-- `required` boolean column to task_output_declarations.
--
-- Invariant query #2 in scripts/ci/check-completion-protocol-invariants.sh
-- relies on this column to detect the canonical failure mode
-- "Task SUCCEEDED while a required output is still pending READY":
--
--   SELECT t.task_id FROM tasks t
--   WHERE t.status='SUCCEEDED'
--     AND EXISTS (
--       SELECT 1 FROM task_output_declarations d
--       LEFT JOIN artifacts a
--         ON a.id = d.artifact_id AND a.status='READY'
--       WHERE d.task_id = t.task_id
--         AND d.required = 1
--         AND a.id IS NULL
--     );
--
-- Without this column that query is a SQL error (no such column),
-- which means the invariant guard cannot run on a fresh DB and a
-- regression at the master layer would silently slip past CI.
--
-- default 0 keeps every pre-existing declaration NON-required by
-- default — the master decides requiredness from
-- task_specs.required_outputs_json at DeclareOutputs time and
-- UPDATE-stamps each corresponding row to required=1. Phase 2 wires
-- the master-side stamping. Until then all declarations are
-- informational only, and the invariant query returns zero rows
-- from a freshly migrated DB (no rows have required=1).

ALTER TABLE task_output_declarations
    ADD COLUMN required INTEGER NOT NULL DEFAULT 0;
