#!/usr/bin/env bash
# Offline tests for check-new-production-loc.py.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
CHECK="$ROOT/scripts/ci/check-new-production-loc.py"
WORK="$(mktemp -d /tmp/velox-new-production-loc.XXXXXX)"
trap 'rm -rf "$WORK"' EXIT

fail() { printf 'new-production-loc-test: FAIL: %s\n' "$*" >&2; exit 1; }
pass() { printf 'new-production-loc-test: %s\n' "$*"; }

run_git() { git -C "$WORK/repo" "$@"; }
setup_repo() {
  mkdir -p "$WORK/repo"
  run_git init -q
  run_git config user.email test@example.invalid
  run_git config user.name loc-test
  printf 'base\n' >"$WORK/repo/base.go"
  run_git add .
  run_git commit -qm base
  run_git branch -M main
}

setup_repo
BASE="$(run_git rev-parse HEAD)"
mkdir -p "$WORK/repo/fixtures" "$WORK/repo/generated" "$WORK/repo/tests" "$WORK/repo/docs" "$WORK/repo/bin"
python3 - "$WORK/repo/large.go" "$WORK/repo/small.go" "$WORK/repo/fixtures/large.go" "$WORK/repo/generated/generated.go" "$WORK/repo/tests/large.go" "$WORK/repo/docs/large.md" "$WORK/repo/bin/blob.bin" <<'PY'
from pathlib import Path
import sys

large, small, fixture, generated, test, doc, binary = map(Path, sys.argv[1:])
large.write_text("package large\n" * 7)
small.write_text("package small\n" * 2)
fixture.write_text("package fixture\n" * 20)
generated.write_text("// Code generated by test. DO NOT EDIT.\n" + "package generated\n" * 20)
test.write_text("package test\n" * 20)
doc.write_text("documentation\n" * 20)
Path(large.parent / "openapi-schema.yaml").write_text("schema\n" * 20)
binary.write_bytes(b"\x00\x01\x02\x03\n" * 20)
PY
run_git add .
run_git commit -qm additions
HEAD="$(run_git rev-parse HEAD)"

# Default threshold 600: the seven-line production file passes.
(cd "$WORK/repo" && BASE_REF="$BASE" HEAD_REF="$HEAD" python3 "$CHECK") >"$WORK/pass.out"
grep -q 'PASS: no new production file exceeds' "$WORK/pass.out"
grep -q 'scanned 2 new production file(s), excluded 6' "$WORK/pass.out"

# Configurable low threshold: large.go becomes a CI-style violation.
if (cd "$WORK/repo" && BASE_REF="$BASE" HEAD_REF="$HEAD" NEW_PRODUCTION_FILE_LOC_THRESHOLD=5 python3 "$CHECK") >"$WORK/fail.out" 2>&1; then
  fail 'threshold violation unexpectedly passed'
fi
grep -q '::error file=large.go::' "$WORK/fail.out"
grep -q 'new production file(s) exceed 5 LOC' "$WORK/fail.out"

# An all-zero event.before represents a branch creation; compare with the
# empty tree so the base commit is included rather than hiding additions.
(cd "$WORK/repo" && BASE_REF=0000000000000000000000000000000000000000 HEAD_REF="$HEAD" \
  python3 "$CHECK") >"$WORK/zero-base.out"
grep -q 'scanned 3 new production file(s), excluded 6' "$WORK/zero-base.out"

# An invalid HEAD is a configuration error, not an empty repository.
if (cd "$WORK/repo" && BASE_REF="$BASE" HEAD_REF=not-a-real-ref python3 "$CHECK") >/dev/null 2>&1; then
  fail 'invalid HEAD unexpectedly passed'
fi

# The manual/scheduled HEAD^ fallback also handles a root commit.
ROOT_WORK="$WORK/root-repo"
mkdir -p "$ROOT_WORK"
git -C "$ROOT_WORK" init -q
git -C "$ROOT_WORK" config user.email test@example.invalid
git -C "$ROOT_WORK" config user.name loc-test
printf 'package root\\n' >"$ROOT_WORK/root.go"
git -C "$ROOT_WORK" add root.go
git -C "$ROOT_WORK" commit -qm root
ROOT_HEAD="$(git -C "$ROOT_WORK" rev-parse HEAD)"
(cd "$ROOT_WORK" && BASE_REF=HEAD^ HEAD_REF="$ROOT_HEAD" python3 "$CHECK") >"$WORK/root.out"
grep -q 'scanned 1 new production file(s), excluded 0' "$WORK/root.out"

# Invalid configuration and missing base are distinct configuration errors.
if (cd "$WORK/repo" && NEW_PRODUCTION_FILE_LOC_THRESHOLD=0 BASE_REF="$BASE" HEAD_REF="$HEAD" python3 "$CHECK") >/dev/null 2>&1; then
  fail 'zero threshold unexpectedly passed'
fi
if (cd "$WORK/repo" && BASE_REF="$WORK/no-such-base" HEAD_REF="$HEAD" python3 "$CHECK") >/dev/null 2>&1; then
  fail 'missing base unexpectedly passed'
fi

pass 'threshold, exclusions, invalid config, and missing-base tests passed'
