// Command api-docs-gen regenerates the `paths` block of
// DataServer/api/openapi.yaml from DataServer/api/api_docs_manifest.yaml
// while preserving every other section (info, servers, tags,
// components, security, ...) verbatim.
//
// Why a custom codegen instead of swag/oapi-codegen/ogen:
//
//   - Zero new third-party dependencies. yaml.v3 is already vendored.
//   - The hand-curated narrative (operation descriptions, response
//     examples, schema explanations) stays untouched. swag requires
//     `// @Description` annotation on every handler; the cost of
//     porting 30+ handlers is far higher than the maintenance cost
//     of a small, declarative manifest.
//   - The schema block (components/schemas) remains hand-curated
//     because the validator's invariants (minLength, minimum,
//     pattern, enum) mirror Go-side constants (MaxVideoNameBytes,
//     MinSceneDurationSeconds, ...) — a fully-generated schema
//     drifts the moment a Go constant changes by 1.
//
// The manifest is the canonical record of "what routes does the
// Master publish". The validator (scripts/api/validate_openapi.py)
// has migrated from a hard-coded ROUTE_INVARIANTS list to a
// correctness-only check; the drift detector in this program is the
// complementary coverage check that tells maintainers when a
// hand-edit to openapi.yaml has silently diverged from the manifest.
//
// Exit codes:
//
//	0 — codegen succeeded AND drift is clean
//	1 — codegen succeeded BUT drift detected (re-run with -apply)
//	2 — codegen failed (manifest invalid, $ref unresolved, ...)
//
// Usage:
//
//	api-docs-gen                          # write to .api-docs-gen.out, print drift
//	api-docs-gen -apply                   # write back into openapi.yaml
//	api-docs-gen -apply -ci               # silence drift warnings (treat as drifted)
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"sort"

	"gopkg.in/yaml.v3"
)

const (
	exitDrift       = 1
	exitGenerr      = 2
	manifestVersion = 1

	headerBanner = "# AUTO-GENERATED by cmd/api-schema-gen. DO NOT EDIT.\n" +
		"# Source: DataServer/internal/apiwire (validate:\"...\" tags).\n" +
		"# Re-run `go run ./cmd/api-schema-gen -apply` after editing those types.\n"
)

// VALID_OPERATIONS is the set of HTTP verbs the codegen emits paths
// for. Anything outside this set is treated as an OpenAPI extension
// field (e.g. x-* metadata) and skipped during drift computation.
var VALID_OPERATIONS = map[string]bool{
	"get":     true,
	"post":    true,
	"put":     true,
	"delete":  true,
	"patch":   true,
	"head":    true,
	"options": true,
}

// Manifest mirrors the YAML structure of api/api_docs_manifest.yaml.
// Every field is required except Summary (which is only used to seed
// an empty operation's summary on first-generation).
//
// ResponseRef is the shape used for both requestBody and per-status
// responses. It is a MAPPING (not a string) so we can declare "no
// $ref" explicitly via a `null` (or absent) value AND validate $ref
// shape uniformly. Earlier code declared the response map as
// map[string]*string — which doesn't unmarshal a YAML map value
// (e.g. "201:\n  $ref: ...") and produced
// `cannot unmarshal !!map into string` at parse.
type Manifest struct {
	Version int          `yaml:"version"`
	Routes  []RouteEntry `yaml:"routes"`
}

type RouteEntry struct {
	Path        string               `yaml:"path"`
	Method      string               `yaml:"method"`
	OperationID string               `yaml:"operationId"`
	Tag         string               `yaml:"tag"`
	Summary     string               `yaml:"summary,omitempty"`
	Parameters  []string             `yaml:"parameters"`
	Security    string               `yaml:"security,omitempty"`
	RequestBody *RefEntry            `yaml:"requestBody,omitempty"`
	Responses   map[string]*RefEntry `yaml:"responses"`
}

// RefEntry is the standard `$ref` shape used everywhere a manifest
// references a component. The yaml:"$ref" tag captures the dollar
// sign (which would otherwise require a struct-tag escape).
type RefEntry struct {
	Ref string `yaml:"$ref"`
}

func (r *RouteEntry) Validate() error {
	if r.Path == "" {
		return errors.New("route.path is empty")
	}
	if r.OperationID == "" {
		return fmt.Errorf("route %q: operationId is empty", r.Path)
	}
	switch r.Method {
	case "get", "post", "put", "delete", "patch", "head", "options":
	default:
		return fmt.Errorf("route %q: method %q is not a valid HTTP verb", r.Path, r.Method)
	}
	if r.RequestBody != nil && r.RequestBody.Ref == "" {
		return fmt.Errorf("route %q: requestBody.$ref is empty (use requestBody: null for inline bodies)", r.Path)
	}
	for code, refPtr := range r.Responses {
		if code == "" {
			return fmt.Errorf("route %q: response status code is empty", r.Path)
		}
		if !isHTTPStatusCode(code) {
			return fmt.Errorf("route %q: response status %q is not a 3-digit HTTP status", r.Path, code)
		}
		if refPtr != nil && refPtr.Ref == "" {
			return fmt.Errorf("route %q: response %s $ref is empty (use response: null for inline schemas / no-body responses)", r.Path, code)
		}
	}
	if r.Method == "get" || r.Method == "delete" || r.Method == "head" {
		if r.RequestBody != nil {
			return fmt.Errorf("route %q: %s requests MUST NOT carry a requestBody", r.Path, r.Method)
		}
	}
	return nil
}

func isHTTPStatusCode(code string) bool {
	if len(code) != 3 {
		return false
	}
	for _, c := range code {
		if c < '0' || c > '9' {
			return false
		}
	}
	return true
}

// driftEntry is one row in the drift summary. Same shape for "added",
// "removed", and "mismatched" entries — the Kind discriminator drives
// display + machine parsing.
type driftEntry struct {
	Kind      string `json:"kind"` // "added" | "removed" | "mismatched"
	Path      string `json:"path"`
	Method    string `json:"method"`
	Field     string `json:"field,omitempty"` // which subfield drifted
	Preimage  string `json:"preimage,omitempty"`
	Generated string `json:"generated,omitempty"`
	Operation string `json:"operationId,omitempty"`
}

func main() {
	var (
		applyFlag  = flag.Bool("apply", false, "write the regenerated openapi.yaml back to disk")
		ciMode     = flag.Bool("ci", false, "CI mode: exit 1 on drift, exit 0 on clean (default behavior in non-CI mode prints drift but exits 0)")
		manifestIn = flag.String("manifest", "api/api_docs_manifest.yaml", "path to the manifest file")
		specIn     = flag.String("spec", "api/openapi.yaml", "path to the curated openapi.yaml (preimage)")
		outTmp     = flag.String("out-tmp", "", "if set, write the generated spec to this file instead of STDOUT for diffing")
	)
	flag.Parse()

	manifest, err := loadManifest(*manifestIn)
	if err != nil {
		fmt.Fprintf(os.Stderr, "FAIL: load manifest %s: %v\n", *manifestIn, err)
		os.Exit(exitGenerr)
	}
	if manifest.Version != manifestVersion {
		fmt.Fprintf(os.Stderr, "FAIL: manifest version=%d, want=%d (regenerate the manifest with the current tool)\n", manifest.Version, manifestVersion)
		os.Exit(exitGenerr)
	}
	for i := range manifest.Routes {
		if err := manifest.Routes[i].Validate(); err != nil {
			fmt.Fprintf(os.Stderr, "FAIL: manifest validation error on entry %d: %v\n", i, err)
			os.Exit(exitGenerr)
		}
	}

	preimage, err := loadSpec(*specIn)
	if err != nil {
		fmt.Fprintf(os.Stderr, "FAIL: load spec %s: %v\n", *specIn, err)
		os.Exit(exitGenerr)
	}

	// Pre-ref validation: every $ref the manifest wants to emit MUST
	// already resolve in the preimage components — otherwise the codegen
	// produces an internally-inconsistent spec that would only fail at
	// the validator-level (and obscure the root cause). Catches the
	// class of "manifest typo" bugs at the source.
	if err := checkRefsResolvable(manifest, preimage); err != nil {
		fmt.Fprintf(os.Stderr, "FAIL: manifest $ref check failed: %v\n", err)
		os.Exit(exitGenerr)
	}

	// operationId continuity: the manifest's operationId MUST equal the
	// one currently in the preimage for the same path+method (when the
	// preimage has an operation for it). This is the cross-file pin:
	// changing a manifest operationId without changing the handler is a
	// silent break, so we surface the drift explicitly.
	operationIDPins := operationIDContinuity(manifest, preimage)

	// 1) Build the new paths block from the manifest.
	generated := buildPathsBlock(manifest)

	// 2) Emit drift summary (manifest paths vs preimage paths).
	drift := computeDrift(manifest, preimage)
	if pins := operationIDPins; len(pins) > 0 {
		drift = append(drift, pins...)
	}
	sort.SliceStable(drift, func(i, j int) bool {
		if drift[i].Path != drift[j].Path {
			return drift[i].Path < drift[j].Path
		}
		return drift[i].Method < drift[j].Method
	})

	// 3) Compose the new spec: copy everything from preimage EXCEPT
	// paths, which we replace with the generated block.
	composed := composeSpec(preimage, generated)

	// 4) Emit the composed spec (possibly to disk).
	marshaled, err := yaml.Marshal(composed)
	if err != nil {
		fmt.Fprintf(os.Stderr, "FAIL: marshal composed spec: %v\n", err)
		os.Exit(exitGenerr)
	}
	generatedOut := append([]byte(headerBanner), marshaled...)
	if *outTmp != "" {
		if err := os.WriteFile(*outTmp, generatedOut, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "FAIL: write %s: %v\n", *outTmp, err)
			os.Exit(exitGenerr)
		}
	}
	preimageBytes, err := os.ReadFile(*specIn)
	if err != nil {
		fmt.Fprintf(os.Stderr, "FAIL: read preimage for diff: %v\n", err)
		os.Exit(exitGenerr)
	}

	// 5) Print the drift report.
	printDrift(drift)
	clean := len(drift) == 0
	switch {
	case *applyFlag:
		// Re-read the preimage as a doc and replace paths.
		if err := os.WriteFile(*specIn, generatedOut, 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "FAIL: write back %s: %v\n", *specIn, err)
			os.Exit(exitGenerr)
		}
		fmt.Fprintf(os.Stderr, "OK: wrote regenerated spec to %s\n", *specIn)
		if clean {
			return
		}
		fmt.Fprintf(os.Stderr, "WARN: applied despite drift — re-read the manifest entries if operationId continuity changed\n")
		os.Exit(exitDrift)
	case *ciMode || !bytes.Equal(preimageBytes, generatedOut):
		if !clean {
			fmt.Fprintf(os.Stderr, "DRIFT: %d drift entries; rerun with -apply\n", len(drift))
			os.Exit(exitDrift)
		}
		// clean drift but bytes differ (e.g. whitespace reorder): still exit 1 in CI to surface the format change.
		if !bytes.Equal(preimageBytes, generatedOut) {
			fmt.Fprintf(os.Stderr, "DRIFT: byte-form differs from preimage; rerun with -apply to format-normalise\n")
			os.Exit(exitDrift)
		}
	default:
		// Default mode: write the regenerated file to .api-docs-gen.out
		// so callers can `diff` it. Don't touch openapi.yaml.
		stagingPath := ".api-docs-gen.out"
		if *outTmp != "" {
			stagingPath = *outTmp
		} else {
			if err := os.WriteFile(stagingPath, generatedOut, 0o644); err != nil {
				fmt.Fprintf(os.Stderr, "FAIL: write %s: %v\n", stagingPath, err)
				os.Exit(exitGenerr)
			}
		}
		if clean {
			fmt.Fprintf(os.Stderr, "OK: codegen clean; staging at %s\n", stagingPath)
			return
		}
		fmt.Fprintf(os.Stderr, "DRIFT: %d entries; staging at %s; rerun with -apply or amend the manifest to clear drift\n", len(drift), stagingPath)
		os.Exit(exitDrift)
	}
}
