package uploads

import (
	"log"
	"net/http"
	"strconv"

	"github.com/gin-gonic/gin"

	"velox-server/internal/artifacts"
)

// ChunkedUploadHandler groups the three chunked upload HTTP handlers behind
// the persistent ChunkedUploadService. Replaces the old global in-memory map.
//
// The worker protocol uses job_id in the URL path; the persistent storage
// uses upload_id (generated by BeginUpload). The handler bridges this via
// ChunkedUploadService.GetUploadByJob.
type ChunkedUploadHandler struct {
	svc *artifacts.ChunkedUploadService
}

// NewChunkedUploadHandler creates a handler group.
func NewChunkedUploadHandler(svc *artifacts.ChunkedUploadService) *ChunkedUploadHandler {
	return &ChunkedUploadHandler{svc: svc}
}

// InitChunkedUpload initializes a persistent chunked upload session.
// POST /api/v1/video/chunked/init
func (h *ChunkedUploadHandler) InitChunkedUpload() gin.HandlerFunc {
	return func(c *gin.Context) {
		var body struct {
			JobID       string `json:"job_id" binding:"required"`
			WorkerID    string `json:"worker_id"`
			LeaseID     string `json:"lease_id"`
			Filename    string `json:"filename"`
			TotalChunks int    `json:"total_chunks"`
			ChunkSize   int64  `json:"chunk_size"`
			TotalSize   int64  `json:"total_size"`
			Attempt     int    `json:"attempt"`
			Revision    int    `json:"revision"`
		}
		if err := c.ShouldBindJSON(&body); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"ok": false, "error": "invalid request"})
			return
		}
		if body.JobID == "" {
			c.JSON(http.StatusBadRequest, gin.H{"ok": false, "error": "job_id is required"})
			return
		}

		// If there's an existing active session for this job, return it for resume.
		if existing, err := h.svc.GetUploadByJob(c.Request.Context(), body.JobID); err == nil && existing != nil {
			chunkState, stateErr := h.svc.GetChunkState(c.Request.Context(), existing.UploadID)
			uploaded := []bool{}
			totalChunks := 0
			if stateErr == nil && chunkState != nil {
				uploaded = chunkState.Uploaded
				totalChunks = chunkState.TotalChunks
			}
			c.JSON(http.StatusOK, gin.H{
				"ok":           true,
				"upload_id":    existing.UploadID,
				"artifact_id":  existing.ArtifactID,
				"job_id":       body.JobID,
				"uploaded":     uploaded,
				"total_chunks": totalChunks,
				"resuming":     true,
			})
			return
		}

		attempt := body.Attempt
		if attempt < 1 {
			attempt = 1
		}

		kind := "video"
		if body.Filename != "" {
			kind = body.Filename
		}

		// BeginUpload creates artifacts + artifact_uploads atomically.
		session, beginErr := h.svc.InitChunkedSession(c.Request.Context(), artifacts.BeginUploadCommand{
			JobID:            body.JobID,
			WorkerID:         body.WorkerID,
			LeaseID:          body.LeaseID,
			AttemptNumber:    attempt,
			ExpectedRevision: body.Revision,
			Kind:             kind,
		})
		if beginErr != nil {
			log.Printf("[CHUNKED] InitChunkedSession failed for %s: %v", body.JobID, beginErr)
			c.JSON(http.StatusBadRequest, gin.H{
				"ok":     false,
				"error":  beginErr.Error(),
				"job_id": body.JobID,
			})
			return
		}

		totalChunks := body.TotalChunks
		if totalChunks < 1 {
			totalChunks = 1
		}

		c.JSON(http.StatusOK, gin.H{
			"ok":           true,
			"upload_id":    session.UploadID,
			"artifact_id":  session.ArtifactID,
			"job_id":       body.JobID,
			"uploaded":     []bool{},
			"total_chunks": totalChunks,
			"resuming":     false,
		})
	}
}

// UploadChunk handles a single chunk upload.
// POST /api/v1/video/chunked/:job_id/:chunk_index
func (h *ChunkedUploadHandler) UploadChunk() gin.HandlerFunc {
	return func(c *gin.Context) {
		jobID := c.Param("job_id")
		chunkIndexStr := c.Param("chunk_index")

		chunkIndex, err := strconv.Atoi(chunkIndexStr)
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"ok": false, "error": "invalid chunk_index"})
			return
		}
		if chunkIndex < 0 {
			c.JSON(http.StatusBadRequest, gin.H{"ok": false, "error": "chunk_index must be >= 0"})
			return
		}

		// Look up the active upload session for this job_id.
		session, lookupErr := h.svc.GetUploadByJob(c.Request.Context(), jobID)
		if lookupErr != nil || session == nil {
			c.JSON(http.StatusBadRequest, gin.H{"ok": false, "error": "no active upload session for job"})
			return
		}

		file, _, err := c.Request.FormFile("chunk")
		if err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"ok": false, "error": "chunk file required"})
			return
		}
		defer file.Close()

		if err := h.svc.UploadChunk(c.Request.Context(), artifacts.ChunkedUploadCommand{
			UploadID:   session.UploadID,
			ChunkIndex: chunkIndex,
			Reader:     file,
		}); err != nil {
			log.Printf("[CHUNKED] UploadChunk failed upload=%s idx=%d: %v", session.UploadID, chunkIndex, err)
			c.JSON(http.StatusInternalServerError, gin.H{"ok": false, "error": err.Error()})
			return
		}

		// Check completion status.
		chunkState, stateErr := h.svc.GetChunkState(c.Request.Context(), session.UploadID)
		uploadedCount := 0
		totalChunks := 0
		isComplete := false
		if stateErr == nil && chunkState != nil {
			totalChunks = chunkState.TotalChunks
			for _, u := range chunkState.Uploaded {
				if u {
					uploadedCount++
				}
			}
			isComplete = uploadedCount > 0 && uploadedCount == totalChunks
		}

		c.JSON(http.StatusOK, gin.H{
			"ok":           true,
			"chunk":        chunkIndex,
			"uploaded":     uploadedCount,
			"total_chunks": totalChunks,
			"complete":     isComplete,
		})
	}
}

// CompleteChunkedUpload assembles all chunks and runs the artifact pipeline
// (Receive → Finalize) to promote the job to SUCCEEDED.
// POST /api/v1/video/chunked/:job_id/complete
func (h *ChunkedUploadHandler) CompleteChunkedUpload() gin.HandlerFunc {
	return func(c *gin.Context) {
		jobID := c.Param("job_id")
		if jobID == "" {
			c.JSON(http.StatusBadRequest, gin.H{"ok": false, "error": "job_id required"})
			return
		}

		// Look up the active upload session for this job_id.
		session, lookupErr := h.svc.GetUploadByJob(c.Request.Context(), jobID)
		if lookupErr != nil || session == nil {
			c.JSON(http.StatusBadRequest, gin.H{"ok": false, "error": "no active upload session for job"})
			return
		}

		// Parse optional auth fields from query params (worker sends minimal info).
		workerID := c.Query("worker_id")
		if workerID == "" {
			workerID = session.WorkerID
		}
		leaseID := c.Query("lease_id")
		if leaseID == "" {
			leaseID = session.LeaseID
		}
		attemptStr := c.Query("attempt")
		attempt := session.AttemptNumber
		if attemptStr != "" {
			if parsed, err := strconv.Atoi(attemptStr); err == nil && parsed > 0 {
				attempt = parsed
			}
		}
		revisionStr := c.Query("revision")
		revision := session.ExpectedRevision
		if revisionStr != "" {
			if parsed, err := strconv.Atoi(revisionStr); err == nil {
				revision = parsed
			}
		}

		art, err := h.svc.CompleteChunked(c.Request.Context(), artifacts.ChunkedCompleteCommand{
			UploadID:         session.UploadID,
			JobID:            jobID,
			WorkerID:         workerID,
			LeaseID:          leaseID,
			AttemptNumber:    attempt,
			ExpectedRevision: revision,
		})
		if err != nil {
			log.Printf("[CHUNKED] CompleteChunked failed job=%s: %v", jobID, err)
			c.JSON(http.StatusInternalServerError, gin.H{
				"ok":     false,
				"error":  err.Error(),
				"job_id": jobID,
			})
			return
		}

		log.Printf("[CHUNKED] Artifact pipeline complete via chunked upload: job=%s artifact=%s upload=%s sha256=%s size=%d",
			jobID, art.ID, session.UploadID, art.SHA256[:16]+"...", art.SizeBytes)

		c.JSON(http.StatusOK, gin.H{
			"ok":            true,
			"job_id":        jobID,
			"artifact_id":   art.ID,
			"upload_id":     session.UploadID,
			"status":        "SUCCEEDED",
			"size":          art.SizeBytes,
			"sha256":        art.SHA256,
			"output_sha256": art.SHA256, // worker compatibility field
			"video_path":    art.StorageKey,
		})
	}
}

// Ensure compile-time check.
var _ = (*ChunkedUploadHandler)(nil)
