package calendar

import (
	"bytes"
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"strconv"
	"testing"
	"time"

	"github.com/gin-gonic/gin"

	"velox-server/internal/queue"
	"velox-server/internal/store"
)

type listResponse struct {
	Events []store.CalendarEvent `json:"events"`
	Count  int                   `json:"count"`
}

func setupCalendarTestEnv(t *testing.T) (*store.SQLiteStore, *queue.FileQueue, *gin.Engine) {
	t.Helper()
	gin.SetMode(gin.TestMode)

	dbPath := filepath.Join(t.TempDir(), "calendar.sqlite")
	db, err := store.NewSQLiteStore(dbPath)
	if err != nil {
		t.Fatalf("new store: %v", err)
	}
	t.Cleanup(func() { _ = db.Close() })

	q, err := queue.NewFileQueue(&queue.FileQueueConfig{DBStore: db, MaxRetries: 3})
	if err != nil {
		t.Fatalf("new queue: %v", err)
	}

	r := gin.New()
	v1 := r.Group("/api/v1")
	sched := NewCalendarScheduler(db, q)
	RegisterRoutes(v1, db, q, sched)

	return db, q, r
}

func postJSON(t *testing.T, r http.Handler, path string, payload any) *httptest.ResponseRecorder {
	t.Helper()
	body, err := json.Marshal(payload)
	if err != nil {
		t.Fatalf("marshal payload: %v", err)
	}
	w := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodPost, path, bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	r.ServeHTTP(w, req)
	return w
}

func putJSON(t *testing.T, r http.Handler, path string, payload any) *httptest.ResponseRecorder {
	t.Helper()
	body, err := json.Marshal(payload)
	if err != nil {
		t.Fatalf("marshal payload: %v", err)
	}
	w := httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodPut, path, bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	r.ServeHTTP(w, req)
	return w
}

func decodeEvent(t *testing.T, body *httptest.ResponseRecorder) store.CalendarEvent {
	t.Helper()
	var event store.CalendarEvent
	if err := json.Unmarshal(body.Body.Bytes(), &event); err != nil {
		t.Fatalf("decode event: %v body=%s", err, body.Body.String())
	}
	return event
}

func decodeList(t *testing.T, body *httptest.ResponseRecorder) listResponse {
	t.Helper()
	var res listResponse
	if err := json.Unmarshal(body.Body.Bytes(), &res); err != nil {
		t.Fatalf("decode list: %v body=%s", err, body.Body.String())
	}
	return res
}

func fullAgentEvent() store.CalendarEvent {
	return makeAgentEvent(time.Now().UTC(), "agent-test-wnba-001", "Test Video WNBA Agent", "This is a test script generated by an agent.")
}

func futureAgentEvent() store.CalendarEvent {
	return makeAgentEvent(time.Now().UTC().Add(24*time.Hour), "agent-test-wnba-003", "Future Test Video", "This is a future script generated by an agent.")
}

func makeAgentEvent(d time.Time, externalID, title, script string) store.CalendarEvent {
	return store.CalendarEvent{
		ExternalID:        externalID,
		Source:            "agent",
		Title:             title,
		Date:              d.Day(),
		Month:             int(d.Month()),
		Year:              d.Year(),
		YouTubeGroup:      "WNBA Zone",
		Category:          "wnba",
		ScriptText:        script,
		Titles:            []string{"Caitlin Clark Just Changed Everything", "The WNBA Was Not Ready For This"},
		Status:            "scheduled",
		StockFootage:      []store.VideoClip{{Type: "stock", URL: "https://example.com/stock1.mp4"}},
		InitialClips:      []store.VideoClip{{Type: "clip", URL: "https://example.com/intro.mp4"}},
		IntermediateClips: []store.VideoClip{{Type: "clip", URL: "https://example.com/middle.mp4"}},
		FinalClips:        []store.VideoClip{{Type: "clip", URL: "https://example.com/final.mp4"}},
	}
}

func incompleteAgentEvent() store.CalendarEvent {
	return store.CalendarEvent{
		ExternalID:   "agent-test-wnba-002",
		Source:       "agent",
		Title:        "Video Without Clips",
		Date:         time.Now().UTC().Day(),
		Month:        int(time.Now().UTC().Month()),
		Year:         time.Now().UTC().Year(),
		YouTubeGroup: "WNBA Zone",
		Category:     "wnba",
		ScriptText:   "Test script without clips.",
		Titles:       []string{"Test Title"},
	}
}

func TestCalendarStore_PersistsFullEventPayload(t *testing.T) {
	db, _, _ := setupCalendarTestEnv(t)

	event := fullAgentEvent()
	if err := db.CreateCalendarEvent(context.Background(), &event); err != nil {
		t.Fatalf("create calendar event: %v", err)
	}

	got, err := db.GetCalendarEvent(context.Background(), event.ID)
	if err != nil {
		t.Fatalf("get calendar event: %v", err)
	}
	if got == nil {
		t.Fatal("expected persisted event")
	}
	if got.ExternalID != event.ExternalID {
		t.Fatalf("externalId mismatch: got %q want %q", got.ExternalID, event.ExternalID)
	}
	if got.Source != event.Source {
		t.Fatalf("source mismatch: got %q want %q", got.Source, event.Source)
	}
	if got.Title != event.Title || got.Date != event.Date || got.Month != event.Month || got.Year != event.Year {
		t.Fatalf("basic fields not preserved: %+v", got)
	}
	if got.YouTubeGroup != event.YouTubeGroup || got.Category != event.Category || got.ScriptText != event.ScriptText {
		t.Fatalf("metadata not preserved: %+v", got)
	}
	if len(got.Titles) != len(event.Titles) || got.Titles[0] != event.Titles[0] {
		t.Fatalf("titles not preserved: %+v", got.Titles)
	}
	if len(got.StockFootage) != 1 || got.StockFootage[0].URL != "https://example.com/stock1.mp4" {
		t.Fatalf("stock footage not preserved: %+v", got.StockFootage)
	}
	if len(got.InitialClips) != 1 || len(got.IntermediateClips) != 1 || len(got.FinalClips) != 1 {
		t.Fatalf("clip arrays not preserved: %+v", got)
	}
}

func TestCalendarAPI_CreateQueuesAndReturnsAgentFields(t *testing.T) {
	_, _, r := setupCalendarTestEnv(t)

	w := postJSON(t, r, "/api/v1/calendar/events", fullAgentEvent())
	if w.Code != http.StatusCreated {
		t.Fatalf("want status 201, got %d body=%s", w.Code, w.Body.String())
	}

	event := decodeEvent(t, w)
	if event.ID == "" || event.JobID == "" {
		t.Fatalf("expected event id and job id, got %+v", event)
	}
	if event.Status != "queued" {
		t.Fatalf("expected queued status, got %q", event.Status)
	}
	if event.JobStatus != string(queue.StatusPending) {
		t.Fatalf("expected pending jobStatus, got %q", event.JobStatus)
	}
	if event.QueueError != "" {
		t.Fatalf("expected no queue error, got %q", event.QueueError)
	}

	w = httptest.NewRecorder()
	now := time.Now().UTC()
	req := httptest.NewRequest(http.MethodGet, "/api/v1/calendar/events?month="+strconv.Itoa(int(now.Month()))+"&year="+strconv.Itoa(now.Year()), nil)
	r.ServeHTTP(w, req)
	if w.Code != http.StatusOK {
		t.Fatalf("want list 200, got %d body=%s", w.Code, w.Body.String())
	}
	res := decodeList(t, w)
	if res.Count != 1 || len(res.Events) != 1 {
		t.Fatalf("expected 1 event in list, got %+v", res)
	}
	got := res.Events[0]
	if got.ScriptText != fullAgentEvent().ScriptText {
		t.Fatalf("script text not returned: %+v", got)
	}
	if got.YouTubeGroup != fullAgentEvent().YouTubeGroup || got.Category != fullAgentEvent().Category {
		t.Fatalf("agent fields missing: %+v", got)
	}
	if got.JobID == "" || got.Status != "queued" {
		t.Fatalf("queued fields missing: %+v", got)
	}
}

func TestCalendarAPI_IncompleteEventDoesNotEnqueue(t *testing.T) {
	db, q, r := setupCalendarTestEnv(t)

	w := postJSON(t, r, "/api/v1/calendar/events", incompleteAgentEvent())
	if w.Code != http.StatusCreated {
		t.Fatalf("want status 201, got %d body=%s", w.Code, w.Body.String())
	}

	event := decodeEvent(t, w)
	if event.Status != "needs_assets" {
		t.Fatalf("expected needs_assets status, got %q", event.Status)
	}
	if event.JobID != "" {
		t.Fatalf("expected no job id, got %q", event.JobID)
	}

	stats, err := q.Stats(context.Background())
	if err != nil {
		t.Fatalf("queue stats: %v", err)
	}
	if stats["total"] != 0 {
		t.Fatalf("expected no queued jobs, got %v", stats)
	}

	events, err := db.ListCalendarEvents(context.Background(), store.CalendarEventFilter{})
	if err != nil {
		t.Fatalf("list calendar events: %v", err)
	}
	if len(events) != 1 {
		t.Fatalf("expected one calendar event in db, got %d", len(events))
	}
}

func TestCalendarAPI_UpdateCompletesQueuedJobWithoutDuplicate(t *testing.T) {
	_, q, r := setupCalendarTestEnv(t)

	create := incompleteAgentEvent()
	create.ScriptText = "Test script without clips."
	w := postJSON(t, r, "/api/v1/calendar/events", create)
	if w.Code != http.StatusCreated {
		t.Fatalf("create status: %d body=%s", w.Code, w.Body.String())
	}
	created := decodeEvent(t, w)

	update := store.CalendarEvent{
		StockFootage:      []store.VideoClip{{Type: "stock", URL: "https://example.com/stock1.mp4"}},
		InitialClips:      []store.VideoClip{{Type: "clip", URL: "https://example.com/intro.mp4"}},
		IntermediateClips: []store.VideoClip{{Type: "clip", URL: "https://example.com/middle.mp4"}},
		FinalClips:        []store.VideoClip{{Type: "clip", URL: "https://example.com/final.mp4"}},
	}
	w = putJSON(t, r, "/api/v1/calendar/events/"+created.ID, update)
	if w.Code != http.StatusOK {
		t.Fatalf("update status: %d body=%s", w.Code, w.Body.String())
	}
	updated := decodeEvent(t, w)
	if updated.Status != "queued" {
		t.Fatalf("expected queued after update, got %q", updated.Status)
	}
	if updated.JobID == "" {
		t.Fatal("expected job id after update")
	}

	stats, err := q.Stats(context.Background())
	if err != nil {
		t.Fatalf("queue stats: %v", err)
	}
	if stats["total"] != 1 {
		t.Fatalf("expected one queued job, got %v", stats)
	}

	job, err := q.GetJob(context.Background(), updated.JobID)
	if err != nil {
		t.Fatalf("get job: %v", err)
	}
	if job == nil {
		t.Fatal("expected job in queue")
	}
	if job.Payload["calendar_event_id"] != updated.ID {
		t.Fatalf("job not linked to event: %+v", job.Payload)
	}
}

func TestCalendarAPI_ExternalIDIsIdempotent(t *testing.T) {
	db, q, r := setupCalendarTestEnv(t)

	payload := fullAgentEvent()
	w := postJSON(t, r, "/api/v1/calendar/events", payload)
	if w.Code != http.StatusCreated {
		t.Fatalf("first create status: %d body=%s", w.Code, w.Body.String())
	}
	first := decodeEvent(t, w)

	w = postJSON(t, r, "/api/v1/calendar/events", payload)
	if w.Code != http.StatusOK {
		t.Fatalf("second create status: %d body=%s", w.Code, w.Body.String())
	}
	second := decodeEvent(t, w)

	if second.ID != first.ID {
		t.Fatalf("expected same event id, got %q and %q", first.ID, second.ID)
	}

	events, err := db.ListCalendarEvents(context.Background(), store.CalendarEventFilter{})
	if err != nil {
		t.Fatalf("list calendar events: %v", err)
	}
	if len(events) != 1 {
		t.Fatalf("expected one calendar event after idempotent create, got %d", len(events))
	}

	stats, err := q.Stats(context.Background())
	if err != nil {
		t.Fatalf("queue stats: %v", err)
	}
	if stats["total"] != 1 {
		t.Fatalf("expected one job after idempotent create, got %v", stats)
	}
}

func TestCalendarAPI_FutureEventStaysScheduled(t *testing.T) {
	_, q, r := setupCalendarTestEnv(t)

	w := postJSON(t, r, "/api/v1/calendar/events", futureAgentEvent())
	if w.Code != http.StatusCreated {
		t.Fatalf("future create status: %d body=%s", w.Code, w.Body.String())
	}
	event := decodeEvent(t, w)
	if event.Status != "scheduled" {
		t.Fatalf("expected scheduled status for future event, got %q", event.Status)
	}
	if event.JobID != "" {
		t.Fatalf("expected no job for future event, got %q", event.JobID)
	}

	stats, err := q.Stats(context.Background())
	if err != nil {
		t.Fatalf("queue stats: %v", err)
	}
	if stats["total"] != 0 {
		t.Fatalf("expected zero jobs for future scheduled event, got %v", stats)
	}
}

func TestCalendarAPI_StatusLifecycleAndOutputs(t *testing.T) {
	_, q, r := setupCalendarTestEnv(t)

	w := postJSON(t, r, "/api/v1/calendar/events", fullAgentEvent())
	if w.Code != http.StatusCreated {
		t.Fatalf("create status: %d body=%s", w.Code, w.Body.String())
	}
	event := decodeEvent(t, w)

	if err := q.UpdateJobFields(context.Background(), event.JobID, map[string]interface{}{
		"status":            string(queue.StatusProcessing),
		"master_video_path": "/tmp/output.mp4",
		"drive_url":         "https://drive.example.com/video",
	}); err != nil {
		t.Fatalf("set processing: %v", err)
	}

	w = httptest.NewRecorder()
	req := httptest.NewRequest(http.MethodGet, "/api/v1/calendar/events/"+event.ID, nil)
	r.ServeHTTP(w, req)
	if w.Code != http.StatusOK {
		t.Fatalf("get processing status: %d body=%s", w.Code, w.Body.String())
	}
	processing := decodeEvent(t, w)
	if processing.Status != "processing" {
		t.Fatalf("expected processing, got %q", processing.Status)
	}

	if err := q.UpdateJobFields(context.Background(), event.JobID, map[string]interface{}{
		"status":            string(queue.StatusCompleted),
		"master_video_path": "/tmp/output.mp4",
		"drive_url":         "https://drive.example.com/video",
	}); err != nil {
		t.Fatalf("set completed: %v", err)
	}

	w = httptest.NewRecorder()
	req = httptest.NewRequest(http.MethodGet, "/api/v1/calendar/events/"+event.ID, nil)
	r.ServeHTTP(w, req)
	if w.Code != http.StatusOK {
		t.Fatalf("get completed status: %d body=%s", w.Code, w.Body.String())
	}
	completed := decodeEvent(t, w)
	if completed.Status != "completed" {
		t.Fatalf("expected completed, got %q", completed.Status)
	}
	if completed.OutputVideoPath != "/tmp/output.mp4" {
		t.Fatalf("expected output video path, got %+v", completed)
	}
	if completed.OutputVideoURL != "https://drive.example.com/video" {
		t.Fatalf("expected output video url, got %+v", completed)
	}
	if completed.PublishStatus != "manual" {
		t.Fatalf("expected manual publish status, got %q", completed.PublishStatus)
	}
}
