// Proto definition for Velox Worker-Control bidirectional stream.
// Both master (DataServer) and worker (worker-agent-go) use this contract
// for typed, versioned control-plane communication.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: velox/control/worker_control.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransportMessage is the wire format for all control-plane messages.
// It mirrors controltransport.ControlMessage in shared/controltransport/message.go.
type TransportMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MessageId       string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // Maps to ControlMessageType (e.g. "heartbeat", "job_offer")
	WorkerId        string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SequenceNumber  int64                  `protobuf:"varint,5,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	SentAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,7,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Payload         *structpb.Struct       `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-like payload for existing ControlMessage.Payload
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransportMessage) Reset() {
	*x = TransportMessage{}
	mi := &file_velox_control_worker_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportMessage) ProtoMessage() {}

func (x *TransportMessage) ProtoReflect() protoreflect.Message {
	mi := &file_velox_control_worker_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportMessage.ProtoReflect.Descriptor instead.
func (*TransportMessage) Descriptor() ([]byte, []int) {
	return file_velox_control_worker_control_proto_rawDescGZIP(), []int{0}
}

func (x *TransportMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *TransportMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TransportMessage) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *TransportMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TransportMessage) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *TransportMessage) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *TransportMessage) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *TransportMessage) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_velox_control_worker_control_proto protoreflect.FileDescriptor

const file_velox_control_worker_control_proto_rawDesc = "" +
	"\n" +
	"\"velox/control/worker_control.proto\x12\rvelox.control\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xbd\x02\n" +
	"\x10TransportMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12'\n" +
	"\x0fsequence_number\x18\x05 \x01(\x03R\x0esequenceNumber\x123\n" +
	"\asent_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12)\n" +
	"\x10protocol_version\x18\a \x01(\tR\x0fprotocolVersion\x121\n" +
	"\apayload\x18\b \x01(\v2\x17.google.protobuf.StructR\apayload2_\n" +
	"\rWorkerControl\x12N\n" +
	"\x06Stream\x12\x1f.velox.control.TransportMessage\x1a\x1f.velox.control.TransportMessage(\x010\x01B\"Z velox-shared/controltransport/pbb\x06proto3"

var (
	file_velox_control_worker_control_proto_rawDescOnce sync.Once
	file_velox_control_worker_control_proto_rawDescData []byte
)

func file_velox_control_worker_control_proto_rawDescGZIP() []byte {
	file_velox_control_worker_control_proto_rawDescOnce.Do(func() {
		file_velox_control_worker_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_velox_control_worker_control_proto_rawDesc), len(file_velox_control_worker_control_proto_rawDesc)))
	})
	return file_velox_control_worker_control_proto_rawDescData
}

var file_velox_control_worker_control_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_velox_control_worker_control_proto_goTypes = []any{
	(*TransportMessage)(nil),      // 0: velox.control.TransportMessage
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 2: google.protobuf.Struct
}
var file_velox_control_worker_control_proto_depIdxs = []int32{
	1, // 0: velox.control.TransportMessage.sent_at:type_name -> google.protobuf.Timestamp
	2, // 1: velox.control.TransportMessage.payload:type_name -> google.protobuf.Struct
	0, // 2: velox.control.WorkerControl.Stream:input_type -> velox.control.TransportMessage
	0, // 3: velox.control.WorkerControl.Stream:output_type -> velox.control.TransportMessage
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_velox_control_worker_control_proto_init() }
func file_velox_control_worker_control_proto_init() {
	if File_velox_control_worker_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_velox_control_worker_control_proto_rawDesc), len(file_velox_control_worker_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_velox_control_worker_control_proto_goTypes,
		DependencyIndexes: file_velox_control_worker_control_proto_depIdxs,
		MessageInfos:      file_velox_control_worker_control_proto_msgTypes,
	}.Build()
	File_velox_control_worker_control_proto = out.File
	file_velox_control_worker_control_proto_goTypes = nil
	file_velox_control_worker_control_proto_depIdxs = nil
}
