package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	telemetry "velox-shared/telemetry"
)

func main() {
	input := flag.String("input", "catalog.json", "language-neutral catalog source (validated by the telemetry package)")
	output := flag.String("output", "", "generated C++ header path")
	check := flag.Bool("check", false, "check that output is up to date without writing it")
	flag.Parse()

	source, err := os.ReadFile(*input)
	if err != nil {
		fmt.Fprintf(os.Stderr, "cataloggen: read source %s: %v\n", *input, err)
		os.Exit(1)
	}
	if !bytes.Equal(source, telemetry.CatalogJSON()) {
		fmt.Fprintf(os.Stderr, "cataloggen: source %s differs from the embedded catalog\n", *input)
		os.Exit(1)
	}
	if *output == "" {
		fmt.Fprintln(os.Stderr, "cataloggen: -output is required")
		os.Exit(2)
	}
	generated := renderHeader()
	if *check {
		existing, err := os.ReadFile(*output)
		if err != nil {
			fmt.Fprintf(os.Stderr, "cataloggen: read %s: %v\n", *output, err)
			os.Exit(1)
		}
		if string(existing) != generated {
			fmt.Fprintf(os.Stderr, "cataloggen: %s is stale\n", *output)
			os.Exit(1)
		}
		return
	}
	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "cataloggen: create output directory: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*output, []byte(generated), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "cataloggen: write %s: %v\n", *output, err)
		os.Exit(1)
	}
}

func renderHeader() string {
	entries := telemetry.Catalog.Entries()
	keys := make([]string, 0, len(entries))
	for key := range entries {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	var b strings.Builder
	b.WriteString("// Code generated by shared/telemetry/cmd/cataloggen; DO NOT EDIT.\n")
	b.WriteString("// Source: shared/telemetry/catalog.json\n")
	b.WriteString("#pragma once\n\n")
	b.WriteString("#include <array>\n#include <string_view>\n\n")
	b.WriteString("namespace velox::telemetry::catalog {\n\n")
	fmt.Fprintf(&b, "inline constexpr int kSchemaVersion = %d;\n\n", telemetry.SchemaVersion)

	writeVocabulary(&b, "kOriginMaster", telemetry.OriginMaster)
	writeVocabulary(&b, "kOriginWorker", telemetry.OriginWorker)
	writeVocabulary(&b, "kOriginEngine", telemetry.OriginEngine)
	writeVocabulary(&b, "kOriginFFmpeg", telemetry.OriginFFmpeg)
	writeVocabulary(&b, "kOriginUpload", telemetry.OriginUpload)
	writeVocabulary(&b, "kOriginValidation", telemetry.OriginValidation)
	writeVocabulary(&b, "kScopeJob", telemetry.ScopeJob)
	writeVocabulary(&b, "kScopeTask", telemetry.ScopeTask)
	writeVocabulary(&b, "kScopeAttempt", telemetry.ScopeAttempt)
	writeVocabulary(&b, "kScopeSegment", telemetry.ScopeSegment)
	writeVocabulary(&b, "kScopeAudioTrack", telemetry.ScopeAudioTrack)
	writeVocabulary(&b, "kScopeSubtitleTrack", telemetry.ScopeSubtitleTrack)
	writeVocabulary(&b, "kScopeArtifact", telemetry.ScopeArtifact)

	b.WriteString("struct EventDescriptor {\n")
	b.WriteString("    std::string_view key;\n")
	b.WriteString("    std::string_view component;\n")
	b.WriteString("    std::string_view action;\n")
	b.WriteString("    std::string_view origin;\n")
	b.WriteString("    std::string_view scope;\n")
	b.WriteString("    std::string_view phase;\n")
	b.WriteString("    std::string_view event_type;\n")
	b.WriteString("    std::string_view kind;\n")
	b.WriteString("    std::string_view unit;\n")
	b.WriteString("    std::string_view timing_mode;\n")
	b.WriteString("    std::string_view aggregation;\n")
	b.WriteString("    std::string_view cardinality;\n")
	b.WriteString("    std::string_view owner;\n")
	b.WriteString("};\n\n")
	fmt.Fprintf(&b, "inline constexpr std::array<EventDescriptor, %d> kEvents = {{\n", len(keys))
	for _, key := range keys {
		spec := entries[key]
		fmt.Fprintf(&b, "    { %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s },\n",
			cppString(key), cppString(spec.Component), cppString(spec.Action),
			cppString(spec.Origin), cppString(spec.Scope), cppString(spec.Phase),
			cppString(spec.EventType), cppString(string(spec.Kind)), cppString(string(spec.Unit)),
			cppString(string(spec.TimingMode)), cppString(string(spec.Aggregation)),
			cppString(string(spec.Cardinality)), cppString(string(spec.Owner)))
	}
	b.WriteString("}};\n\n")

	owners := telemetry.AllFactOwners()
	factNames := make([]string, 0, len(owners))
	for fact := range owners {
		factNames = append(factNames, fact)
	}
	sort.Strings(factNames)
	b.WriteString("struct FactOwner {\n    std::string_view name;\n    std::string_view owner;\n};\n\n")
	fmt.Fprintf(&b, "inline constexpr std::array<FactOwner, %d> kFacts = {{\n", len(factNames))
	for _, fact := range factNames {
		fmt.Fprintf(&b, "    { %s, %s },\n", cppString(fact), cppString(string(owners[fact])))
	}
	b.WriteString("}};\n\n")

	b.WriteString("constexpr bool IsCanonicalOrigin(std::string_view value) {\n")
	b.WriteString("    return value == kOriginMaster || value == kOriginWorker || value == kOriginEngine ||\n")
	b.WriteString("           value == kOriginFFmpeg || value == kOriginUpload || value == kOriginValidation;\n")
	b.WriteString("}\n\n")
	b.WriteString("constexpr bool IsCanonicalScope(std::string_view value) {\n")
	b.WriteString("    return value == kScopeJob || value == kScopeTask || value == kScopeAttempt ||\n")
	b.WriteString("           value == kScopeSegment || value == kScopeAudioTrack ||\n")
	b.WriteString("           value == kScopeSubtitleTrack || value == kScopeArtifact;\n")
	b.WriteString("}\n\n")
	b.WriteString("constexpr const EventDescriptor* FindEvent(std::string_view component, std::string_view action) {\n")
	b.WriteString("    for (const auto& event : kEvents) {\n")
	b.WriteString("        if (event.component == component && event.action == action) return &event;\n")
	b.WriteString("    }\n")
	b.WriteString("    return nullptr;\n")
	b.WriteString("}\n\n")
	b.WriteString("constexpr bool IsCatalogEvent(std::string_view component, std::string_view action) {\n")
	b.WriteString("    return FindEvent(component, action) != nullptr;\n")
	b.WriteString("}\n\n")
	b.WriteString("} // namespace velox::telemetry::catalog\n")
	return b.String()
}

func writeVocabulary(b *strings.Builder, name, value string) {
	fmt.Fprintf(b, "inline constexpr std::string_view %s = %s;\n", name, cppString(value))
}

func cppString(value string) string {
	return `"` + strings.ReplaceAll(strings.ReplaceAll(value, `\\`, `\\\\`), `"`, `\\"`) + `"`
}
