package store

import (
	"context"
	"database/sql"
	"fmt"
	"time"
)

// ArtifactRepository is the narrow persistence contract for job output artifacts.
//
// Per spec §5: narrow interfaces live in the package that consumes them. This
// declaration lives alongside the SQLite backing store today so existing
// *SQLiteStore callers can continue to use it; future PRs will define even
// narrower views in HTTP handler / service packages as the consumer refactors.
// Operations that require atomicity (e.g. finalize + job status change) remain
// a single method on this interface — callers do NOT see BeginTx/Commit.
type ArtifactRepository interface {
	// Insert creates a new artifact record in 'pending' status.
	// ID is generated by the caller (or by the repo if blank).
	Insert(ctx context.Context, artifact *Artifact) error
	// FinalizeAndComplete marks an artifact finished and bumps its parent job
	// to SUCCEEDED in the same transaction. jobID/sha256 may be empty to skip
	// the job-side update.
	FinalizeAndComplete(ctx context.Context, artifactID, status, storageURL, jobID, sha256 string) error
	// GetByID returns a single artifact. Missing → (nil, nil).
	GetByID(ctx context.Context, artifactID string) (*Artifact, error)
	// ListByJob returns up to limit artifacts for a job, newest first.
	ListByJob(ctx context.Context, jobID string, limit int) ([]Artifact, error)
}

// SQLiteArtifactRepository implements ArtifactRepository against a SQLiteStore.
//
// This is reference-typed so the connection (db/sql.DB) is reused across
// callers; we do not pool here, the underlying *sql.DB handles that.
type SQLiteArtifactRepository struct {
	store *SQLiteStore
}

// NewSQLiteArtifactRepository wraps a SQLiteStore as an ArtifactRepository.
func NewSQLiteArtifactRepository(store *SQLiteStore) *SQLiteArtifactRepository {
	return &SQLiteArtifactRepository{store: store}
}

// Insert creates an artifact row with sane defaults.
func (r *SQLiteArtifactRepository) Insert(ctx context.Context, artifact *Artifact) error {
	if artifact == nil {
		return fmt.Errorf("artifact is nil")
	}
	if artifact.ID == "" {
		artifact.ID = fmt.Sprintf("artifact_%d", time.Now().UnixNano())
	}
	if artifact.Status == "" {
		artifact.Status = "pending"
	}
	if artifact.StorageProvider == "" {
		artifact.StorageProvider = "local"
	}
	if artifact.CreatedAt == "" {
		artifact.CreatedAt = time.Now().UTC().Format(time.RFC3339)
	}
	_, err := r.store.db.ExecContext(ctx,
		`INSERT INTO artifacts (id, job_id, attempt_id, type, storage_provider, storage_key,
		                        storage_url, local_path, sha256, size_bytes, duration_seconds, status, created_at)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		artifact.ID, artifact.JobID, nullInt(artifact.AttemptID), artifact.Type,
		artifact.StorageProvider, artifact.StorageKey, artifact.StorageURL,
		artifact.LocalPath, artifact.SHA256, artifact.SizeBytes,
		artifact.DurationSeconds, artifact.Status, artifact.CreatedAt,
	)
	return err
}

// FinalizeAndComplete atomically:
//  1. updates artifacts.status and storage_url, and
//  2. (if jobID supplied) bumps the job to SUCCEEDED with completed_at + sha256.
//
// Atomicity is enforced by a single SQL transaction — callers do not see Begin/Commit.
func (r *SQLiteArtifactRepository) FinalizeAndComplete(ctx context.Context, artifactID, status, storageURL, jobID, sha256 string) error {
	if artifactID == "" {
		return fmt.Errorf("artifactID is required")
	}
	tx, err := r.store.db.BeginTx(ctx, nil)
	if err != nil {
		return err
	}
	defer func() { _ = tx.Rollback() }()

	if _, err := tx.ExecContext(ctx,
		`UPDATE artifacts SET status=?, storage_url=? WHERE id=?`,
		status, storageURL, artifactID); err != nil {
		return err
	}
	if jobID != "" {
		now := time.Now().UTC().Format(time.RFC3339)
		if _, err := tx.ExecContext(ctx,
			`UPDATE jobs SET status=?, completed_at=?, updated_at=?
			 WHERE job_id=? AND UPPER(COALESCE(status,'')) NOT IN ('SUCCEEDED','COMPLETED','CANCELLED','FAILED')`,
			"SUCCEEDED", now, now, jobID); err != nil {
			return err
		}
		if sha256 != "" {
			if _, err := tx.ExecContext(ctx,
				`UPDATE jobs SET output_sha256=? WHERE job_id=?`,
				sha256, jobID); err != nil {
				return err
			}
		}
	}
	return tx.Commit()
}

// GetByID returns one artifact, or (nil, nil) on missing.
func (r *SQLiteArtifactRepository) GetByID(ctx context.Context, artifactID string) (*Artifact, error) {
	row := r.store.db.QueryRowContext(ctx,
		`SELECT id, job_id, COALESCE(attempt_id,0), type, storage_provider,
		        COALESCE(storage_key,''), COALESCE(storage_url,''), COALESCE(local_path,''),
		        COALESCE(sha256,''), COALESCE(size_bytes,0), COALESCE(duration_seconds,0.0),
		        status, created_at
		 FROM artifacts WHERE id=?`, artifactID)
	var a Artifact
	err := row.Scan(&a.ID, &a.JobID, &a.AttemptID, &a.Type, &a.StorageProvider,
		&a.StorageKey, &a.StorageURL, &a.LocalPath, &a.SHA256,
		&a.SizeBytes, &a.DurationSeconds, &a.Status, &a.CreatedAt)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &a, nil
}

// ListByJob returns newest-first artifacts for a job, capped at limit.
func (r *SQLiteArtifactRepository) ListByJob(ctx context.Context, jobID string, limit int) ([]Artifact, error) {
	if limit <= 0 {
		limit = 20
	}
	rows, err := r.store.db.QueryContext(ctx,
		`SELECT id, job_id, COALESCE(attempt_id,0), type, storage_provider,
		        COALESCE(storage_key,''), COALESCE(storage_url,''), COALESCE(local_path,''),
		        COALESCE(sha256,''), COALESCE(size_bytes,0), COALESCE(duration_seconds,0.0),
		        status, created_at
		 FROM artifacts WHERE job_id=? ORDER BY created_at DESC LIMIT ?`,
		jobID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var artifacts []Artifact
	for rows.Next() {
		var a Artifact
		if err := rows.Scan(&a.ID, &a.JobID, &a.AttemptID, &a.Type, &a.StorageProvider,
			&a.StorageKey, &a.StorageURL, &a.LocalPath, &a.SHA256,
			&a.SizeBytes, &a.DurationSeconds, &a.Status, &a.CreatedAt); err != nil {
			continue
		}
		artifacts = append(artifacts, a)
	}
	return artifacts, rows.Err()
}

// Compile-time check that SQLiteArtifactRepository satisfies ArtifactRepository.
var _ ArtifactRepository = (*SQLiteArtifactRepository)(nil)
