package remoteengine

import (
	_ "embed"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

// goldenWorkerPayload is embedded so normal test runs do not depend on the
// process working directory or the test binary's filesystem location.
//
//go:embed testdata/worker_payload.golden.json
var goldenWorkerPayload []byte

// TestToWorkerPayload_Golden locks the renderer-facing projection at the
// remote-engine adapter boundary. The fixture is intentionally independent of
// timestamps, UUIDs, filesystem paths, and database state so changes to the
// worker contract produce a reviewable golden diff.
func TestToWorkerPayload_Golden(t *testing.T) {
	raw := map[string]interface{}{
		"job_id":      "golden-worker-job-001",
		"status":      "completed",
		"video_name":  "Golden render",
		"script_text": "A deterministic worker payload.",
		"voiceover_paths": []interface{}{
			"velox-asset://audio/scene-0.mp3",
			"velox-asset://audio/legacy.mp3",
		},
		"scenes": []interface{}{
			map[string]interface{}{
				"scene_id":         "scene-0",
				"index":            float64(0),
				"kind":             "clip",
				"text":             "Opening scene",
				"clip_link":        "velox-asset://clips/opening.mp4",
				"duration_seconds": float64(4.5),
				"clip": map[string]interface{}{
					"asset_id": "clip-001",
					"url":      "velox-asset://clips/opening.mp4",
					"start_ms": float64(100),
					"end_ms":   float64(4600),
				},
				"voiceover": map[string]interface{}{
					"url":      "velox-asset://audio/scene-0.mp3",
					"language": "en",
				},
				"subtitles": map[string]interface{}{
					"url":      "velox-asset://subtitles/opening.srt",
					"format":   "srt",
					"language": "en",
				},
			},
			map[string]interface{}{
				"scene_id":         "scene-1",
				"index":            float64(1),
				"kind":             "image",
				"text":             "Closing scene",
				"image_link":       "velox-asset://images/closing.jpg",
				"duration_seconds": float64(2),
			},
		},
		"layers": []interface{}{
			map[string]interface{}{
				"id":   "title",
				"type": "text",
				"role": "title",
				"text": "Golden render",
			},
		},
		"subtitle_tracks": []interface{}{
			map[string]interface{}{
				"source": "velox-asset://subtitles/opening.srt",
				"preset": "default",
				"font":   "Inter",
			},
		},
		"audio_tracks": []interface{}{
			map[string]interface{}{
				"source_url": "velox-asset://audio/music.mp3",
				"role":       "background_music",
				"volume":     0.2,
			},
		},
		"delivery_plan": []interface{}{
			map[string]interface{}{
				"destination_id": "youtube-en",
				"priority":       1,
				"retry_budget":   3,
				"metadata": map[string]interface{}{
					"title":       "Publication title must not leak",
					"description": "Publication description must not leak",
				},
			},
		},
		"video_metadata": map[string]interface{}{
			"width":          1920,
			"height":         1080,
			"fps_num":        30,
			"title":          "Editorial title must not leak",
			"privacy_status": "private",
		},
		"publications": []interface{}{
			map[string]interface{}{"metadata": map[string]interface{}{"title": "Publication must not leak"}},
		},
		"output_path": "/var/lib/velox/output/golden.mp4",
	}

	dto, err := ParseRemotePipelineResult(raw)
	if err != nil {
		t.Fatalf("ParseRemotePipelineResult: %v", err)
	}
	payload := dto.ToWorkerPayload()
	encoded, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		t.Fatalf("marshal worker payload: %v", err)
	}
	encoded = append(encoded, '\n')

	_, testFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	goldenPath := filepath.Join(filepath.Dir(testFile), "testdata", "worker_payload.golden.json")
	if os.Getenv("UPDATE_GOLDEN") == "1" {
		tmp, err := os.CreateTemp(filepath.Dir(goldenPath), ".worker_payload.golden.*.tmp")
		if err != nil {
			t.Fatalf("create temporary golden file: %v", err)
		}
		tmpName := tmp.Name()
		defer os.Remove(tmpName)
		if _, err := tmp.Write(encoded); err != nil {
			tmp.Close()
			t.Fatalf("write temporary golden file: %v", err)
		}
		if err := tmp.Close(); err != nil {
			t.Fatalf("close temporary golden file: %v", err)
		}
		if err := os.Chmod(tmpName, 0o644); err != nil {
			t.Fatalf("chmod temporary golden file: %v", err)
		}
		if err := os.Rename(tmpName, goldenPath); err != nil {
			t.Fatalf("replace golden file: %v", err)
		}
	}

	want := goldenWorkerPayload
	if os.Getenv("UPDATE_GOLDEN") == "1" {
		// The fixture is compiled into this test binary before the update,
		// so compare against the freshly generated bytes in this invocation.
		want = encoded
	}
	if len(want) == 0 {
		t.Fatalf("embedded golden file %s is empty (run UPDATE_GOLDEN=1 to create it)", goldenPath)
	}
	if string(encoded) != string(want) {
		t.Fatalf("worker payload differs from golden %s:\n--- got ---\n%s--- want ---\n%s", goldenPath, encoded, want)
	}

	for _, key := range []string{"publications", "metadata", "title", "description", "privacy", "privacy_status", "publish_at", "delivery_plan", "destination_id", "destination_ids"} {
		if _, present := payload[key]; present {
			t.Fatalf("publication field %q leaked into worker payload", key)
		}
	}
	if _, present := payload["video_metadata"]; !present {
		t.Fatal("technical video_metadata should remain in worker payload")
	}
}
