package repository

import "context"

// Artifact is the persistence projection of a job output artifact row.
type Artifact struct {
	ID              string  `json:"id"`
	JobID           string  `json:"job_id"`
	AttemptID       int     `json:"attempt_id,omitempty"`
	Type            string  `json:"type"`
	StorageProvider string  `json:"storage_provider"`
	StorageKey      string  `json:"storage_key,omitempty"`
	StorageURL      string  `json:"storage_url,omitempty"`
	LocalPath       string  `json:"local_path,omitempty"`
	SHA256          string  `json:"sha256,omitempty"`
	SizeBytes       int64   `json:"size_bytes"`
	DurationSeconds float64 `json:"duration_seconds,omitempty"`
	DurationMs      int64   `json:"duration_ms,omitempty"`
	Status          string  `json:"status"`
	VerifiedAt      string  `json:"verified_at,omitempty"`
	MimeType        string  `json:"mime_type,omitempty"`
	CreatedAt       string  `json:"created_at"`
}

// ArtifactRepository is the narrow persistence contract for job output artifacts.
//
// Operations that require atomicity (e.g. finalize + job status change) remain
// a single method on this interface — callers do NOT see BeginTx/Commit.
type ArtifactRepository interface {
	// Insert creates a new artifact record in 'pending' status.
	// ID is generated by the caller (or by the repo if blank).
	Insert(ctx context.Context, artifact *Artifact) error
	// GetByID returns a single artifact. Missing → (nil, nil).
	GetByID(ctx context.Context, artifactID string) (*Artifact, error)
	// ListByJob returns up to limit artifacts for a job, newest first.
	ListByJob(ctx context.Context, jobID string, limit int) ([]Artifact, error)
}
